### ISSUE TITLE
Support for DataTabels (Helpers - Database)

### ISSUE THREAD

**Issue by pixelspezi** [simple-mvc-framework/framework#126]
It would be great if there would be a support for this:

http://www.datatables.net/examples/server_side/post.html
https://github.com/DataTables/DataTables/blob/master/examples/server_side/scripts/ssp.class.php

**Comment by BlueFreakLP** [comment]
Its PHP and the Bot dont use any php

**Comment by daveismyname** [comment]
i this not something I'm looking to build into the core.

**Comment by jimgwhit** [comment]
If you get good enough at your html tables and jquery, you have data tables already.  You can make headers with links built in to resort your data.  Take a look at how cakephp's cakebake does it.  But when I have used cake, I didn't bake, rather I still wrote my own code.  But I did do some test with bake and got some ideas. I do not like widgets and ready things like data tables, I like coding my own stuff.  That is why I like SMVC, and the keep it simple logo.  That's not to say that you can't add in a third party program, that's totally up to you. If you know what you're doing, the sky is the limit as to what other things you can add to the framework.
