### ISSUE TITLE
Multilanguage website

### ISSUE THREAD

**Issue by raffe90** [simple-mvc-framework/framework#133]
Has anyone succesfully managed to get a multi language website going? If so, can you explained how you managed to actually change the lang, I am trying to do it through sessions, but for some reason it is not setting and keeps the same language no matter what.

**Comment by Dybo** [comment]
Yes I have a multilanguage website. I did it with a cookie and when you load in the page you can use the cookie to set the language.

**Comment by raffe90** [comment]
I managed to get it working with cookies a couple of days ago. But this does not seem like a propper implementation. For example if the user disables cookies then our site does not work correctly.

**Comment by Volter9** [comment]
@raffe90 specify also a fallback/default language (en_US, for example), in case if language wasn't selected, or cookies are disabled.

**Comment by autotim** [comment]
```php
 public function changeLang()
    {
        $segments = Url::segments();
        $last = Url::lastsegment($segments);

        if(isset($last))
        {
            $code = Data::input($last); // just do some cleaning from input
            // here is the poor filter to get the only thing we want, nothing more
            if($code != $this->settings_model->getLang() && $code  == 'ro' || $code == 'en' || $code == 'fr')
            {

                $postdata = ['value' => $code];
                $where = ['name' => 'Lang'];

                $this->settings_model->update($postdata,$where); // update db with new language

                Session::destroy('lang'); // destroy the language session
                Session::set('lang', $code); // set new language session
                Url::redirect(); // redirect to see the changes.. you cand do it with javascript if you want to

            }
            else
            {
                Url::redirect();
            }

        }
        Url::redirect();
    }
```
Above method is from my navbar controller
The `router` 
```php
Router::get('/q/(:any)', 'Controllers\Navbar@change_lang');
```
The `settings` table from database
```sql
id name value
1 Lang en
```
The `html`
```html
<--! It would be preferable to dynamically generate the output !-->
<a href="http://your-site.com/q/en">Change my language</a>
```

**Comment by ymakux** [comment]
I think the best solution would be to add language suffix to base path. So we need a function to get the base path instead of DIR constant  as suggested here https://github.com/simple-mvc-framework/framework/issues/159 In this case routes stay as is
