### ISSUE TITLE
Simple MVC, Visual Studio PHP Tools

### ISSUE THREAD

**Issue by cblaze22** [simple-mvc-framework/framework#137]
I can't get my Simple MVC project to work in Visual Studio with the plugin PHP Tools.  I keep getting a 404 below saying no routes found.  This works in Apache.

`Router::post('/launch', '\controllers\ToolLaunchController@handleRootToolLaunch');`

Any clue on where to start or look?

**Comment by cblaze22** [comment]
I responded on that chat althought I am getting a `You don't have permission to access /forum/viewtopic.php on this server.` now for some reason.

**Comment by cblaze22** [comment]
My $_SERVER['PHP_SELF'] = "/index.php/launch".  Is that by design?

**Comment by cblaze22** [comment]
Looks like I got it working with `http://localhost:30711/index.php/launch`

**Comment by daveismyname** [comment]
OK that suggests it's an issue with mod-rewrite, if your using apache then mod rewrite needs to be turned on if using IIS or Nginx they will need to be setup for rewriting urls

btw 2.2 has just been released.

**Comment by daveismyname** [comment]
realised why you had problems getting on the forum, that's been fixed now.

**Comment by daveismyname** [comment]
have you solved this nor or still an issue?

**Comment by cblaze22** [comment]
Yes just by using the path above which works for me.
