### ISSUE TITLE
double use of helpers class

### ISSUE THREAD

**Issue by nekomajin** [simple-mvc-framework/framework#149]
@daveismyname,

in `app/templates/default/header.php` and `app/templates/default/footer.php` you include the helper classes

```php
use Helpers\Assets;
use Helpers\Url;
use Helpers\Hooks;
```

twice. Is that necessary? Only a question.

**Comment by daveismyname** [comment]
each file needs the alias creating if you want to use short calls like Url::redirect unfortunately I cannot add it to header.php and use it in footer.php without the alias.

**Comment by Volter9** [comment]
@daveismyname What about introducing the class aliases (like Laravel does)?
http://php.net/manual/en/function.class-alias.php

**Comment by daveismyname** [comment]
I've tried using that but unable to get it to work, I think Laravel used it for pre v5 since namespacing is used in v5 now but I could be wrong on that.
