### ISSUE TITLE
DIR constant

### ISSUE THREAD

**Issue by kopiyka** [simple-mvc-framework/framework#159]
Do we really need to hardcode site URL in the DIR constant?
What's about

Helpers\Url

    public static function base($full = false)
    {
        if($full) {
            return sprintf("%s://%s%s", isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off' 
            ? 'https' : 'http', $_SERVER['SERVER_NAME'], $_SERVER['REQUEST_URI']);
        }
        
        return str_replace(array('\\',' '), array('/','%20'), dirname($_SERVER['SCRIPT_NAME']));
    }

**Comment by daveismyname** [comment]
You could that that with a helper as you've suggested but as the config file needs to be edited with connection details when using a database you may as well set the url at the same time, plus with a constant you can use it anywhere without needing to set anything up.

**Comment by kopiyka** [comment]
Ок, thanks for explanation
