### ISSUE TITLE
Module views appears after the body tag 

### ISSUE THREAD

**Issue by hoekie** [simple-mvc-framework/framework#161]
Hi!

When I create a module according your screencast in a clean installation, the blog view appears on top of every page (welcome and subpage) right after the body tag. (see image)

When I create another view it also apperears on top of the page.

Is this a bug or am I doing something wrong?

Thanks for your hard work.
I really like this framework!

Richard

![image](https://cloud.githubusercontent.com/assets/2049572/8761374/c492bb58-2d4e-11e5-8ca0-9350c928daeb.png)

**Comment by daveismyname** [comment]
Ah it's a bug I've updated helpers/hooks.php if you replace your version it should then work as expected.

Thanks Richard.

Sent from my iPhone

On 18 Jul 2015, at 12:20, Richard Hoek <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi!

When I create a module according your screencast in a clean installation, the blog view appears on top of every page (welcome and subpage) right after the body tag. (see image)

When I create another view it also apperears on top of the page.

Is this a bug or am I doing something wrong?

Thanks for your hard work.
I really like this framework!

Richard

[image]<https://cloud.githubusercontent.com/assets/2049572/8761374/c492bb58-2d4e-11e5-8ca0-9350c928daeb.png>

-

**Comment by hoekie** [comment]
Wow! Youre fast Dave! Thanks!

**Comment by daveismyname** [comment]
I realised yesterday before I did the screencast I've set the hooks to only auto load the name.module.php file as that file determines what hooks to use.

Sent from my iPhone

On 18 Jul 2015, at 12:26, Richard Hoek <notifications@github.com<mailto:notifications@github.com>> wrote:


Wow! Youre fast Dave! Thanks!

-

**Comment by hoekie** [comment]
Ah oke, well it works as aspected now.

Thanks for the update!
