### ISSUE TITLE
logger

### ISSUE THREAD

**Issue by jimgwhit** [simple-mvc-framework/framework#165]
the logger filer is causing errors when trying to test the frame on php 7.  Got this from apache error log:  
~~~
[Sat Aug 01 12:02:26.643500 2015] [:error] [pid 6604:tid 1156] [client ::1:53193] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Core\\Logger::newMessage() must be an instance of Exception, instance of Error given, called in C:\\Bitnami\\wampstack-7.0.0beta2-1\\apache2\\htdocs\\fm\\app\\Core\\Logger.php on line 56 and defined in C:\\Bitnami\\wampstack-7.0.0beta2-1\\apache2\\htdocs\\fm\\app\\Core\\Logger.php:86\nStack trace:\n#0 C:\\Bitnami\\wampstack-7.0.0beta2-1\\apache2\\htdocs\\fm\\app\\Core\\Logger.php(56): Core\\Logger::newMessage(Object(Error))\n#1 [internal function]: Core\\Logger::exceptionHandler(Object(Error))\n#2 {main}\n  thrown in C:\\Bitnami\\wampstack-7.0.0beta2-1\\apache2\\htdocs\\fm\\app\\Core\\Logger.php on line 86
~~~
Is there a way to test for php ver, and have the framework also work on php 7.  I'm sure other want to test/play with php 7 as well.

**Comment by pandory-network** [comment]
SMVC currently does not support PHP7. PHP7 is officially not yet finished.

U can edit Logger.php Line: 86

public static function newMessage(\Exception $exception)

to 

public static function newMessage($exception)

and the next error is triggered in the router.

**Comment by jimgwhit** [comment]
Thanks for the code.  One more question, is there a way to test for php version and if php 7 do this otherwise do that sort of thing?

**Comment by jimgwhit** [comment]
Got as for as list page, but now blank page when trying to edit a record.  Getting this:  
~~~
[Sun Aug 02 11:35:29.734605 2015] [:error] [pid 3016:tid 1132] [client ::1:50346] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Core\\Logger::newMessage() must be an instance of EngineException, instance of Error given, called in C:\\Bitnami\\wampstack-7.0.0beta2-1\\apache2\\htdocs\\tjhs\\app\\Core\\Logger.php on line 56 and defined in C:\\Bitnami\\wampstack-7.0.0beta2-1\\apache2\\htdocs\\tjhs\\app\\Core\\Logger.php:87\nStack trace:\n#0 C:\\Bitnami\\wampstack-7.0.0beta2-1\\apache2\\htdocs\\tjhs\\app\\Core\\Logger.php(56): Core\\Logger::newMessage(Object(Error))\n#1 [internal function]: Core\\Logger::exceptionHandler(Object(Error))\n#2 {main}\n  thrown in C:\\Bitnami\\wampstack-7.0.0beta2-1\\apache2\\htdocs\\tjhs\\app\\Core\\Logger.php on line 87, referer: http://localhost/tjhs/dog/edit?dogid=117%22:  
~~~
referer: http://localhost/tjhs/dog/edit?dogid=117%22
~~~
Any ideas here?  At least part is now working.

**Comment by jimgwhit** [comment]
A side note on this, Dave when you do re-write the framework for php 7 compatability, you will include conditions for php versions correct?  Something like:  
~~~
<?php
 
class DummyError {
  // common code
}

if (version_compare(PHP_VERSION, '7.0.0-dev') >= 0) {
  class Error extends DummyError {
    // copy-paste code that used to use \Exception in type hints
  }
}
else {
  class Error extends DummyError {
    //  code that uses \Exception in type hints
  }
}
?>
~~~
I just don't know how to write the various error codes for different versions.  Any way you can put together a version of the frame work that works with php 7 and has backwards compatibility with at least php 5.5.*?

**Comment by jimgwhit** [comment]
Well so far by changing the function edit from:  
~~~
    function edit()
    {
        //function edit($id, $tvar){
        //if(isset($_POST['dogid'])){
        if (isset($_POST['submit'])) {
            if (!isset($_SESSION['token'])) {
                $_SESSION['token'] = md5(uniqid(rand(), TRUE));
            }
            if ($_POST['token'] != $_SESSION['token']) {
                Url::redirect('admin/login');
            }

            $dogpic = Cln::fixValue($_POST['dogpic']);
            $dogid = $_POST['dogid'];
            $dogname = Cln::fixValue($_POST['dogname']);
            $sex = $_POST['sex'];
            $comments = Cln::fixValue($_POST['comments']);
            //$adopted = (isset($_POST['adopted'])=='1'?'1':'0'); ///added 
            $adopted = $_POST['adopted']; ///added 
            $lastedit = date("Y-m-d H:i:s");
            echo $adopted;
            if (!isset($error)) {
                $postdata = array(
                    'dogpic' => $dogpic,
                    'dogname' => $dogname,
                    'sex' => $sex,
                    'comments' => $comments,
                    'adopted' => $adopted,
                    'lastedit' => $lastedit
                );
                $where = array('dogid' => $dogid);
                $this->Dog->update($postdata, $where);

                Url::redirect('dog/indexadmin?p=' . Session::get('dogpage') . '&psch=' . Session::get('dogsearch') . '&aval=' . Session::get('dogaval'));
            }
        }

        $dogid = $_REQUEST['dogid'];
        $data['row'] = $this->Dog->getDog($dogid);
        $this->view->renderTemplate('edithd', $data);
        $this->view->render('dog/edit', $data, $error);
        $this->view->renderTemplate('editft', $data);
    }

~~~
TO:  
~~~
    function edit()
    {
        if (isset($_POST['submit'])) {
            if (!isset($_SESSION['token'])) {
                $_SESSION['token'] = md5(uniqid(rand(), TRUE));
            }
            if ($_POST['token'] != $_SESSION['token']) {
                Url::redirect('admin/login');
            }

            $dogpic = Cln::fixValue($_POST['dogpic']);
            $dogid = $_POST['dogid'];
            $dogname = Cln::fixValue($_POST['dogname']);
            $sex = $_POST['sex'];
            $comments = Cln::fixValue($_POST['comments']);
            $adopted = $_POST['adopted']; 
            $lastedit = date("Y-m-d H:i:s");
            echo $adopted;
            
            try {
    			// Code that may throw an Exception or Error.
    			$dogpic = Cln::fixValue($_POST['dogpic']);
	            $dogid = $_POST['dogid'];
	            $dogname = Cln::fixValue($_POST['dogname']);
	            $sex = $_POST['sex'];
	            $comments = Cln::fixValue($_POST['comments']);
	            $adopted = $_POST['adopted']; 
	            $lastedit = date("Y-m-d H:i:s");
	            echo $adopted;
	            $postdata = array(
                    'dogpic' => $dogpic,
                    'dogname' => $dogname,
                    'sex' => $sex,
                    'comments' => $comments,
                    'adopted' => $adopted,
                    'lastedit' => $lastedit
                );
                $where = array('dogid' => $dogid);
                $this->Dog->update($postdata, $where);
                Url::redirect('dog/indexadmin?p=' . Session::get('dogpage') . '&psch=' . Session::get('dogsearch') . '&aval=' . Session::get('dogaval'));

			} catch (Throwable $t) {
    			echo "error";
    		} catch (Exception $e) {
    			// Executed only in PHP 5.x, will not be reached in PHP 7
    			echo "hello";
			}
            
        }

        $dogid = $_REQUEST['dogid'];
        $data['row'] = $this->Dog->getDog($dogid);
        $this->view->renderTemplate('edithd', $data);
        $this->view->render('dog/edit', $data, $error);
        $this->view->renderTemplate('editft', $data);
    }

~~~
Allows me to edit.  I am just dumb when it comes to error handling.

**Comment by jimgwhit** [comment]
Any help on re-writing logger.php in core would be appreciated.  I know php 7 isn't out yet, but Laravel framework 5.1 already works in php 7 and is also backwards compatible to php 5.5.9. So please, in the next version make it php 7 and back to php 5.5.* compatible.

**Comment by daveismyname** [comment]
thanks for raising this I haven't until now tried to run php 7, I'm got it running on a VM currently have to say I don't like that approach feels very awkward using terminal for editing the files. Much prefer an external editor. 

I may try installing 7 manually that I can test better unless anyone know's of a good resource for getting up and running with 7?

As you've mentioned there are a few things that need changing by the looks of it they are not major things so a full rewrite won't be needed but tweaks in a few placed to do things differently. That way it will be function for 5.4 and up, next month I'll be dropping 5.4 and stating 5.5, the framework will still work on 5.4 but not officially supporting it. 14th of Sept is when 5.4 is end of life.

Your comment about Laravel is not relevant, I'm not trying to match or outdo what Laravel does. PHP 7 is still in beta and not close to been production ready yet.

I need to do my own tests for I can better answer your questions.

**Comment by jimgwhit** [comment]
Are all the final votes in for the final version that PHP 7 will be? I guess there has been changes from EngineException to Throwable.

**Comment by daveismyname** [comment]
no not yet the next beta release is to be released on the 6th of August it's a work in progress by the looks of it with a lot more beta versions due to be released until the final version is released. https://wiki.php.net/todo/php70#timetable

**Comment by jimgwhit** [comment]
I figured there would be more changes.  It's just good to hear that when you do write a new version that it will support php 5.5 through php 7.  That way I may develop in php 7 on local machine but a host company may still have 5.5 or 5.6.  Dave you don't know how that eased my mind when you said that, thanks. Can't wait till final release. Hopefully you will have a new version of framework by December, that would make a nice Christmas present.

**Comment by daveismyname** [comment]
Thanks glad for sticking with it, once I have a php7 test environment setup I'll be able to ensure all is working as expected I don't foresee many issues , the php dev team are doing a great job building in as much backward compatibility as they can, quite different when upgrading from 4 to 5.

**Comment by jimgwhit** [comment]
Closing for now, please read my new comments on pull request #168.
