### ISSUE TITLE
Route error, space URI

### ISSUE THREAD

**Issue by yoelrola** [simple-mvc-framework/framework#170]
Hi, i'm testing the code, and i have an space in my URL, if i specify the route Router::any('asd', 'Controllers\Section@index');
URL is like:  http://localhost:8080/CLIENT%202015/web.com/asd
AND the URI is read like: /CLIENT 2015/web.com/asd

 In the Router.php dispatch() function, says:
if (in_array($uri, self::$routes)) {
}

But, return false because the route and uri are different.

Sorry by my english, i hope i can help.

**Comment by pandory-network** [comment]
first u can edit the .htaccess 

RewriteBase /

to

RewriteBase /CLIENT 2015/web.com/

and remember empty spaced looks not so good in urls/uri  use another folder 

example like this /CLIENT-2015/web.com

**Comment by daveismyname** [comment]
I agree with @pandory-network set your project url to not use spaces then you won't have any problems.
