### ISSUE TITLE
Should Core\Controller be regular class, not abstract

### ISSUE THREAD

**Issue by jimgwhit** [simple-mvc-framework/framework#174]
I know somehow the router is working, however in netbeans ide I get:
```
Abstract class \Core\Controller can not be instantiated
```
It happens here at line 126:
```
$c = new $controller;
```
The new key word isn't supposed to work with an abstract class, but yet the router is working.  
I am no expert on writing router code, so could someone shed some light on how the router is still working anyway -- thanks.

**Comment by volter9** [comment]
Just ignore this warning. In the past, netbeans gave me loads of useless warnings.

The router works following way:
1. Match given route with given request url and method
2. If the route is found, execute it by creating controller instance and invoking method in the given route
3. Else, 404

**Comment by jimgwhit** [comment]
I found out something about the router code.  
This code in the public static function invokeObject($callback, $matched = null, $msg = null) function works in php 5.5 and php 7.--:
```
public static function invokeObject($callback, $matched = null, $msg = null)
    {

        $last = explode('/', $callback);
        $last = end($last);

        //grab the controller name and method call
        list($controller, $method) = explode('@', $last);

        //instanitate controller with optional msg (used for errorCallback)
        $controller = new $controller($msg);

        if ($matched == null) {
            //call method
            $controller->{$method}();
        } else {
            //call method and pass in array keys as params
            call_user_func_array(array($controller, $method), $matched);
        }
    }
```
But the original code that's present now does not work in php 7.  
I will probably do a pull request, any thoughts.  Changing this one function in router makes the framework work in php 5.--- and php 7.---  
This is the only function that would have to be changed in the router.

**Comment by jimgwhit** [comment]
Above code came from @pandory-network, another SMVC contributor, I just never thought to  
try it the other way around, using it in php 5.5 and php 7.---

**Comment by jimgwhit** [comment]
Oh,  @pandory-networkline said that line 92 in router causes it not to work in php 7.  
Why doesn't
```
 $controller->$segments[1]();
```
not work in php 7?

**Comment by volter9** [comment]
Because it's treated as `$controller->{$segments[1]}();`.
Read about the changes in code parsing in PHP7.

**Comment by jimgwhit** [comment]
Thanks for reply, @volter9 how would you write line 92 to work in both versions of php?

**Comment by volter9** [comment]
I'm not really sure. I installed php7, but I'm too lazy to test it. Therefore, I installed only php7 for CLI, not really sure how to bind it to apache. Did you tried the code I suggested from issue #173 with php7?

**Comment by jimgwhit** [comment]
I tryed, it did not work, just blank screen.  I thing this:
```
public static function invokeObject($callback, $matched = null, $msg = null)
    {

        $last = explode('/', $callback);
        $last = end($last);

        //grab the controller name and method call
        list($controller, $method) = explode('@', $last);

        //instanitate controller with optional msg (used for errorCallback)
        $controller = new $controller($msg);

        if ($matched == null) {
            //call method
            $controller->{$method}();
        } else {
            //call method and pass in array keys as params
            call_user_func_array(array($controller, $method), $matched);
        }
    }
```
is probably the way to go.  I have tested and it works in bith versions of php, and it seems  
like good clean code.  Remember credit is @pandory-networkline. I have not test it on php 5.4.  
But 5.5 through 7.--- ok.

**Comment by volter9** [comment]
If you have blank screen, it means that you should look into the error log or turn on the error displaying. What's the error message?

**Comment by jimgwhit** [comment]
Let me re-try and see if there is an error in log.  
Meanwhile, I tested @pandory-networkline  code on php 5.4.25 also, and it works.  
So it's good on php 5.4.25 through php 7.----

**Comment by jimgwhit** [comment]
The error is:
```
Error on Aug 25, 2015 19:36PM - call_user_func_array() expects parameter 2 to be array, null given in C:\BitNami\wampstack-5.6.2-0\apache2\htdocs\crudv22p7\app\Core\Router.php on line 90
```

**Comment by jimgwhit** [comment]
@volter9 The code you gave me:
```
$last = explode('/', $callback);
$last = end($last);

$segments = explode('@', $last);

$controller = $segments[0];
$method = $segments[1];

$controller = new $controller($msg);

call_user_func_array(array($controller, $method), $matched);
```
Gave the error, however the below works:
```
$last = explode('/', $callback);
        $last = end($last);

        $segments = explode('@', $last);

        $controller = $segments[0];
        $method = $segments[1];

        $controller = new $controller($msg);

        if ($matched == null) {
            //call method
            $controller->{$segments[1]}();
        } else {
            //call method and pass in array keys as params
            call_user_func_array(array($controller, $segments[1]), $matched);
        }
```
Or whole thing
```
 public static function invokeObject($callback, $matched = null, $msg = null)
    {

        $last = explode('/', $callback);
        $last = end($last);

        $segments = explode('@', $last);

        $controller = $segments[0];
        $method = $segments[1];

        $controller = new $controller($msg);

        if ($matched == null) {
            //call method
            $controller->{$segments[1]}();
        } else {
            //call method and pass in array keys as params
            call_user_func_array(array($controller, $segments[1]), $matched);
        }
    }
```
tested only on php 5.5 so far, I wil test on php 7 and let you know.

**Comment by volter9** [comment]
Try this one:

```php
$last = explode('/', $callback);
$last = end($last);

$segments = explode('@', $last);

$controller = $segments[0];
$method = $segments[1];

$controller = new $controller($msg);

call_user_func_array(array($controller, $method), $matched ?: []);
```

**Comment by jimgwhit** [comment]
Yes it works in php 7, still need to check php 5.4 and 5.5, but is seems that:
```
public static function invokeObject($callback, $matched = null, $msg = null)
    {

       	$last = explode('/', $callback);
		$last = end($last);
		
		$segments = explode('@', $last);
		
		$controller = $segments[0];
		$method = $segments[1];
		
		$controller = new $controller($msg);
		
		call_user_func_array(array($controller, $method), $matched ?: []);    }
		

```
AND
```
public static function invokeObject($callback, $matched = null, $msg = null)
    {

        $last = explode('/', $callback);
        $last = end($last);

        $segments = explode('@', $last);

        $controller = $segments[0];
        $method = $segments[1];

        $controller = new $controller($msg);

        if ($matched == null) {
            //call method
            $controller->{$segments[1]}();
        } else {
            //call method and pass in array keys as params
            call_user_func_array(array($controller, $segments[1]), $matched);
        }
    }

```
AND
```
public static function invokeObject($callback, $matched = null, $msg = null)
    {

        $last = explode('/', $callback);
        $last = end($last);

        //grab the controller name and method call
        list($controller, $method) = explode('@', $last);

        //instanitate controller with optional msg (used for errorCallback)
        $controller = new $controller($msg);

        if ($matched == null) {
            //call method
            $controller->{$method}();
        } else {
            //call method and pass in array keys as params
            call_user_func_array(array($controller, $method), $matched);
        }
    }
```
all work in all versions
I'd like more testing, maybe Dave will pick one, or if you do more testin you could do a pull request.  
I notice your don't have the if -- else part:
```
        if ($matched == null) {
            //call method
            $controller->{$segments[1]}();
        } else {
            //call method and pass in array keys as params
            call_user_func_array(array($controller, $segments[1]), $matched);
        }
```
Should this part be there?

**Comment by jimgwhit** [comment]
I hope Dave jumps in here, and views the previous issue #173 also. I know that he will have to test all aspects of everything prior to calling it php 7 ready.

**Comment by volter9** [comment]
If you can avoid the "if" part, why bothering keeping it. My rules of thumb:

1. Smaller code, simpler code
2. Small methods are easier to debug
3. And other OOP principles...

If the list version is working in both versions, then:

**Comment by jimgwhit** [comment]
What are you calling list version?

**Comment by volter9** [comment]
See the update.

... or even condensed to:

```php
$last = explode('/', $callback);

list($controller, $method) = explode('@', end($last));

$controller = new $controller($msg);

call_user_func_array(array($controller, $method), $matched ?: []);
```

**Comment by volter9** [comment]
Just wonder, in the code:

```php
$controller = new $controller($msg);

call_user_func_array(array($controller, $method), $matched ?: []);
```

Where is variable message comes from?

**Comment by jimgwhit** [comment]
What does this part do?
```
if ($matched == null) {
            //call method
            $controller->{$segments[1]}();

```

**Comment by jimgwhit** [comment]
Isn't that a way to just jump to a default controller, I'm probably wrong.

**Comment by volter9** [comment]
Well, look: the `$matched` variable is an array of captured variables from URL. `preg_match` can return `array` or `null` if the regular expression was matched with given string.

In the code, in the `if` part, it's checking for `null`. If the `$matched` is null, it probably means that there was no segments in URL matched, we're just invoking the controller's method without arguments, in other case, we invoke the method with given arguments.

> just jump to a default controller

`DEFAULT_CONTROLLER` constant used only in autoDispatch method.

P.S.: The suggested code by me going to work only on PHP5.4+. You should keep it in mind (because of the `?:` operator and shorthand array literal `[]`). It's easy to adapt for PHP5.3+, though:

```php
$last = explode('/', $callback);
$last = end($last);

$segments = explode('@', $last);

$controller = $segments[0];
$method = $segments[1];

$controller = new $controller($msg);

call_user_func_array(array($controller, $method), $matched ? $matched : array());
```

**Comment by jimgwhit** [comment]
The original has:
```
//instanitate controller with optional msg (used for errorCallback)
        $controller = new $segments[0]($msg);

```
I have no idea ho it works.

**Comment by jimgwhit** [comment]
Later I will try:
```
$last = explode('/', $callback);
$last = end($last);

$segments = explode('@', $last);

$controller = $segments[0];
$method = $segments[1];

$controller = new $controller($msg);

call_user_func_array(array($controller, $method), $matched ? $matched : array());
```
on all three versions, php 5.4, 5.5, and 7.0.0RC1-0

**Comment by jimgwhit** [comment]
Ok,
```
public static function invokeObject($callback, $matched = null, $msg = null)
    {
        $last = explode('/', $callback);
        $last = end($last);

        $segments = explode('@', $last);

        $controller = $segments[0];
        $method = $segments[1];

        $controller = new $controller($msg);

        call_user_func_array(array($controller, $method), $matched ? $matched : array());
    }
```
Works on php 5.4,  php 5.5, and php 7.0.0RC1-0  
Now if they don't go changing things til final release, we are good to go, tell Dave.  
@volter9 Are you doing a pull request?

**Comment by volter9** [comment]
@jimgwhit, yeah, I'll do it.

**Comment by jimgwhit** [comment]
Thanks, i worry less about php 7 changes now.  Of course it will be a while before my hosting has it, godaddy waits a while on shared host to ensure all is tested.

**Comment by jimgwhit** [comment]
P.S. I guess I am one of those "want it now, got to have it people".

**Comment by daveismyname** [comment]
Thanks again to you both, I'm eager to test further with php 7
