### ISSUE TITLE
invokeObject method in router for PHP7

### ISSUE THREAD

**Issue by jimgwhit** [simple-mvc-framework/framework#184]
Have you had a chance to fully test @volter9  #175 pull request? I ask since I see you made some recent updates, and upped ver to 5.5 or greater php.  Remember, in issue  #174 three different techniques worked.  Of course I relize you may be waiting till final release of php 7. But could you at least put one of the newer methods in the invokeObject method in router, that way it would already work in php 7.  That's not to say later you could do more  tweaks here and there in framework in November when final realease of php 7 hits. My test was on a windows development machine with php 7.0.0RC1 (anything prior is null and void due to massive changes), I hope you can test on a linux enviroment with php 7 (latest release candidate).

**Comment by daveismyname** [comment]
Hi the changes I made only changed the status 5.4 to 5.5 nothing was changed in the router class since the merge @volter9 made everything as far as I'm aware is working correctly. I haven't tested this out myself on 7 myself yet. 

I've been going the through the docs and realised it said 5.4 as that's no longer supported from the 14th it makes sense to up it to 5.5. Ideally use 5.6 and 7 when it comes out.

**Comment by jimgwhit** [comment]
#175 pull request was never merged.

**Comment by volter9** [comment]
@daveismyname I think (IMHO) you should merge this pull request, or at least commit it by yourself (and let us know). :)

This pull request not only adapts router for PHP7, but also improves code quality and readability in this method (another IMHO).

**Comment by jimgwhit** [comment]
Of course test on a Linux server running PHP 7 latest first. My test was under windows.

**Comment by daveismyname** [comment]
Apologies I thought I had merged it, I've done so now and I'll do my own tests asap on a Linux server for 7, I've tested the updated router with a production site for both legacy an routed calls.

**Comment by volter9** [comment]
Thank you @daveismyname! :)
