### ISSUE TITLE
Move routes to it's own file

### ISSUE THREAD

**Issue by daveismyname** [simple-mvc-framework/framework#186]
Hi All,

I recently had a PR with to move routes to it's own file, the more I think about it the more I like it, before making a change I want to ask what are people's thoughts on this?

Functionality wise it would work the same the routes would be placed in a separate file called routes.php inside the Core folder. The reason it's routes.php and not Routes.php is the file would not be a class.

the index.php file where routes are would be replaced with an include to look like this:

````
//call config
new Core\Config();

require 'app/Core/routes.php';
````

**Comment by volter9** [comment]
I think that this is a great idea! :+1:

**Comment by geomorillo** [comment]
Yes i was thinking the same thing

**Comment by jimgwhit** [comment]
Is there a way to give user a choice, so one could pick which way they wanted to go with this?  
But please if you implement it, give good instructions on new usage, comment it well, user could always remove detailed comments later. Thanks

**Comment by geomorillo** [comment]
Well i think the instructions are:
1) Put your routes inside /Core/routes.php
2)Enjoy

**Comment by daveismyname** [comment]
the choice would be use the routes.php file or copy its contents back to index.php other then that it's identical no detailed instructions required.

@geomorillo agreed.

No argument against this and no negative effect I will implement this as stated you can do it the old way if you prefer.

**Comment by volter9** [comment]
> But please if you implement it, give good instructions on new usage, comment it well, user could always remove detailed comments later. Thanks

There's not much of the changes. All what is happened is that routes are moved to other files, and that's it. @geomorillo even gave us pretty cute instruction :smile:
