### ISSUE TITLE
Twig does not get permission to render...

### ISSUE THREAD

**Issue by BeCreativeHD** [simple-mvc-framework/framework#190]
I have installed Twig successfully and made a helper file for it etc, everything is working fine (I think) 
but when I go to a controller, use the helper, instantiate the $twig in the constructor and then do the following:

$this->twig->render('welcome/subpage.php', array('title' => 'variables'));

An error gets into my errorlog.html file and it's the following:

Error on Sep 16, 2015 14:09PM - mkdir(): Permission denied in /Applications/XAMPP/xamppfiles/htdocs/Projects/Prj-CMS/Quasar/vendor/twig/twig/lib/Twig/Cache/Filesystem.php on line 67

Error on Sep 16, 2015 14:09PM - mkdir(): Permission denied in /Applications/XAMPP/xamppfiles/htdocs/Projects/Prj-CMS/Quasar/vendor/twig/twig/lib/Twig/Cache/Filesystem.php on line 67

Error on Sep 16, 2015 14:09PM - mkdir(): Permission denied in /Applications/XAMPP/xamppfiles/htdocs/Projects/Prj-CMS/Quasar/vendor/twig/twig/lib/Twig/Cache/Filesystem.php on line 67

(Btw: Projects/Prj-CMS/Quasar/ is the root folder of my project)

**Comment by daveismyname** [comment]
I've installed twig and run the default example:

````
Router::any('twig', function(){

    $loader = new Twig_Loader_Array(array(
        'index' => 'Hello {{ name }}!',
    ));
    $twig = new Twig_Environment($loader);

    echo $twig->render('index', array('name' => 'Fabien'));

});
````

That worked, can you share your helper so I can try what you've done.

**Comment by BeCreativeHD** [comment]
Oh, thank you very much for your answer @daveismyname but I just fixed it like a minute ago.
I had cache enabled in twig but it doesn't seem to get permission to create folders in there, doesn't really matter tho, anything else works perfect now! But thank you anyway.

**Comment by daveismyname** [comment]
ok glad it's working, It may just be a case of setting folder permissions.
