### ISSUE TITLE
uniform comments

### ISSUE THREAD

**Issue by nekomajin** [simple-mvc-framework/framework#191]
Hey Guys. I just work on various PR's about the comments, because I think that documentation is very important. I accept that everyone has his own way to post comments. Personally, I agree to the [phpDocumentor](http://phpdoc.org/) standard, which is also used in other projects.

However, little things need to be clarified. For [example](http://phpdoc.org/docs/latest/references/phpdoc/tags/param.html):

```php
 /**
  * Counts the number of items in the provided array.
  *
  * @param mixed[] $items Array structure to count the elements of.
  *
  * @return int Returns the number of elements.
  */
 function count(array $items)
 {
     // lines of code
 }
```

- In many comments the first two ** are missing. This show at GitHub @ tags colored. For example:

```php
/*
 * @param without leading **
 */
```

```php
/**
 * @param with leading **
 */
```

- Sentences are completed in the comments part without a dot, but capitalized at start of the block.

```php
/**
 * This sentence should end with a dot
 */
```

- Another important thing: The proposed syntax looks like this:

```php
/**
 * @param [Type] [name] [<description>]
 */
```

Should between each argument **one** space? Or even more (like **3**)?

```php
/**
 * Minions are small, yellow creatures who have existed since the beginning of time.
 *
 * @param   minion   $Kevin   Minions ipsum tatata bala tu belloo!
 * @param   minion   $Bob     Uuuhhh daa poopayee belloo! Me want bananaaa!
 *
 * @return   Stuart|Gru   Potatoooo potatoooo underweaaar chasy pepete. Tank yuuu! hahaha
 */
```
And should the description of `@return` in line with those of `@param`?

*Addition:* How we behave with single-line comments?

---

The PR's are pushed by folders, e.g.:
- Core
- Helpers (maybe split)
- templates...

What do you think about that?

**Comment by jimgwhit** [comment]
Good to comment correctly. Right now I will be happy if there are no PR's for a while so I can have some peace. Unless it's a good clean easy one of course.  Last one I spent 9+ hours troubleshooting.

**Comment by daveismyname** [comment]
Your right all documentation should be the standard docblock format, single line comments should also be docblock

````
/** single line comment */
````

For multiline comments they should contain a summery line, optional a longer description can be used. Each with a line space between then the tags the format is @attribute type $name description. They can be grouped together lastly the return tag should be separated with a new line:

````
/**
  * A summary informing the user what the associated element does.
  *
  * A *description*, that can span multiple lines, to go _in-depth_ into the details of this element
  * and to provide some background information or textual references.
  *
  * @param string $myArgument With a *description* of this argument, these may also
  *    span multiple lines.
  *
  * @return string returns the textual information
  */
````

A list of all tags is available from http://www.phpdoc.org/docs/latest/guides/docblocks.html

I'll go through the files can ensure all comments are docblock style.

Depending on the PR it's not always possible to limit them to a section.

**Comment by daveismyname** [comment]
I've updated the framework now and generated API docs from the code http://simplemvcframework.com/api/
