### ISSUE TITLE
Router

### ISSUE THREAD

**Issue by jimgwhit** [simple-mvc-framework/framework#201]
@daveismyname I haven't tested on php 7 since august, 2015.  I got a chance to test today, the new Router (all since  #175 @volter9 pr) doesn't work on php 7.  Could you dig into the code of the router and find out why?  All was working in php 7.0.0RC1 after the @volter9 #175 PR.  So far it seems to be the only issue, because when I replaced the new router with that one it worked. Otherwise all I get is a blank screen.

**Comment by jimgwhit** [comment]
@daveismyname sorry, false alarm, in the backup router I had namespace Core commented out, I un-commited and new routers work.  Sorry for any confusion.

**Comment by volter9** [comment]
> @volter9 will get a laugh out of it.

:smile:
