### ISSUE TITLE
password function

### ISSUE THREAD

**Issue by daveismyname** [simple-mvc-framework/framework#203]
Now php 5.4 is deprecated, 5.5 being the minimum supported version I think it make sense to loose the compatibility file and change the password helper to use php's native password functions.

http://php.net/manual/en/function.password-hash.php

Any objections to this?

**Comment by Kingorgg** [comment]
Sounds good to me.

**Comment by volter9** [comment]
:+1:

**Comment by geomorillo** [comment]
+1

**Comment by nekomajin** [comment]
very good decision :+1:

**Comment by adjoines** [comment]
![retina-ready 2x](https://cloud.githubusercontent.com/assets/2178862/10842775/99013c22-7f37-11e5-859c-dd58ede11279.png)

**Comment by jimgwhit** [comment]
I use that anyway. +1

**Comment by jimgwhit** [comment]
@daveismyname will a current password still work?

**Comment by jimgwhit** [comment]
Also @daveismyname I believe php 7 handles passwords a little different, something to do with not using a salt or something like that.  Please make sure that the new helper does work on php 5.5 through the latest php 7.  I'm sure you'll test.  I plan to develop on a php 7, but some host will still be php 5.5 or php 5.6.  I bet you thought of all this already.

**Comment by jimgwhit** [comment]
I just tested the password function from php manual, and it does work I replaced  
```
if (Password::verify($password, $darray[0]->password) == false) {
```
with
```
if(password_verify($password, $darray[0]->password) == false){
```
And I logged in just fine.

**Comment by jimgwhit** [comment]
The PHP 7 changelog says
~~~
password_hash() salt option ¶

The salt option for the password_hash() function has been deprecated to prevent developers from generating their own (usually insecure) salts. The function itself generates a cryptographically secure salt when no salt is provided by the developer - therefore custom salt generation should not be needed.
~~~

**Comment by 834rd** [comment]
+1

**Comment by daveismyname** [comment]
Thanks all that's settles then I'll make the changes shortly.

@jimgwhit Yes existing password will still work as the password helper defaults back to php's methods if they exist ie php 5.5 and up but or older version the custom functions are used. Since support should be for 5.5 and upwards there is no point in keeping them.

I'll opt to use PASSWORD_DEFAULT Note that this constant is designed to change over time as new and stronger algorithms are added to PHP. For that reason, the length of the result from using this identifier can change over time. Therefore, it is recommended to store the result in a database column that can expand beyond 60 characters (255 characters would be a good choice).

PHP 7 is deprecated salts but you should not be setting a salt yourself anywhere let php do that internally it's must more capable then we are unless you have a very deep knowledge of security I know I don't.
