### ISSUE TITLE
PSR-7 with middleware?

### ISSUE THREAD

**Issue by nhymxu** [simple-mvc-framework/framework#204]
I see this is future feature. do you have plan to upgrade framework?

**Comment by daveismyname** [comment]
maybe I'll need to look into this to this what is can offer up to now I've heard of it but not looked into that it actually is.

**Comment by jimgwhit** [comment]
What?

**Comment by jimgwhit** [comment]
I googled PHP middleware, results that came up are mostly Laravel, and slim framework.  https://www.google.com/search?q=php+middleware&oq=php+middleware&aqs=chrome.0.69i59j0l2.8836j0j4&client=tablet-android-google&sourceid=chrome-mobile&ie=UTF-8

**Comment by geomorillo** [comment]
I dont know what this psr7 is or what it does never heard of it, but i think the framework is ok like it is right now i don't wanna over complicated things to do simple things

**Comment by volter9** [comment]
> What? Laravel has too much of that junk, that's why I don't use Laravel

I agree with you and @geomorillo, but HTTP middlewares aren't junk, however, they're over complicated for this framework.

**Comment by jimgwhit** [comment]
And I agree with @volter9 , if someone wanted to use a psr-7 implementation with  they could easily for one in ( a package), with composer without messing with the original framework, this is how it should be done that way the framework stays clean without bloat.

**Comment by daveismyname** [comment]
Thanks everyone like you guys I want to keep the framework focused and simple not a swiss amy knife, there are other frameworks for that.

After looking into this further while it does look useful it's also complex and I think it's a use case by case basis so it won't become part of the core framework.

I've come across a third part tool for those that do want to use middleware called Relay - http://relayphp.com

````
Relay is a PSR-7 middleware dispatcher.
Use it with any PHP framework or container.

composer require relay/relay ~1.0
````
