### ISSUE TITLE
Need help naming a new section

### ISSUE THREAD

**Issue by daveismyname** [simple-mvc-framework/framework#205]
I'm in the middle of writing a new section for the website that will allow users to submit a Github url for adding to the new section.

This section is for listing user created helpers / modules / add-ons / projects I keep referring to it as modules but it's not specific to modules so that's not suitable I'm leaning towards naming the sections Add-ons.

I'm interested in what you all think here are the options I got, feel free to suggest others:

Modules - not really suitable
Bundles
Add-ons
Plugins
Extra
Resources

**Comment by baruchvlz** [comment]
Plugins or add-ons in my opinion work best for this.

**Comment by volter9** [comment]
I think bundles or add-ons would be more suitable.

* Extra - too ambiguous 
* Resources - usually refers to some configs/assets
* Plugins - SMVCF hasn't API that allows load up extensions/modules or modify the behavior of core classes (hooks/EventEmitter)
* Modules - same thing as Plugins

**Comment by Kingorgg** [comment]
I vote for Add-ons

**Comment by collizo4sky** [comment]
Plugin is best imo

**Comment by gabizz** [comment]
What about Custom or Contrib ?

**Comment by kowston** [comment]
I think Bundles best fits the variety of what is available.
Do quite like the Homebrew suggestion too.

**Comment by daveismyname** [comment]
thanks guys I think it comes down to either Bundles or Add-ons, I'm 90% set on Bundles.

**Comment by geomorillo** [comment]
+1 to Addons

**Comment by nhymxu** [comment]
I'm using **bundles**

**Comment by jimgwhit** [comment]
Addon is fine, it covers several types.

**Comment by avenirer** [comment]
add-ons +1

**Comment by nekomajin** [comment]
Up to this point add-on has been called the most. I also find it best.

**Comment by 834rd** [comment]
add-ons

**Comment by KeanePW** [comment]
Extensions.

**Comment by daveismyname** [comment]
Add-ons looks to be a clear winner! thanks everyone! much appreciated.
