### ISSUE TITLE
Optional parameter url

### ISSUE THREAD

**Issue by max21** [simple-mvc-framework/framework#207]
Hi,

It is possible to precise the url parameter is optional ?
For example, I have a route like this : Router::get('galerie/(:num)', 'Controllers\Website@galerie') and I want parameter num become optional.

Thanks

**Comment by volter9** [comment]
I think it's possible by appending `?` after placeholder `:num` and setting default value in action method: 

```php
public function galerie ($page = null)
{
    if ($page === null) {
        // there's no parameter
    }
}
```

**Comment by max21** [comment]
I've test with Router::get('galerie/(:num?)', 'Controllers\Website@galerie');
But it doesn't work

**Comment by daveismyname** [comment]
what I tend to do is create 2 routes that point to the same method:

````
Router::get('galerie', 'Controllers\Website@galerie');
Router::get('galerie/(:num)', 'Controllers\Website@galerie');
````

Making the param optional in the function as @volter9 mentioned.

**Comment by max21** [comment]
Thanks, it works !
