### ISSUE TITLE
Error informations

### ISSUE THREAD

**Issue by max21** [simple-mvc-framework/framework#210]
Hi,

The errorlog.html file is accessible by everyone, it's a security breach because this file give many informations about the website and the database. Moreover this file is executable, why ?

Thanks

**Comment by daveismyname** [comment]
Yes it's a regular html file, it's meant for use in development when in production error reporting should be turned off. Also the logger class has an option to clear the log this can be useful for email the errors as they happen and clearing the log at the same time.

**Comment by max21** [comment]
Ok you have to don't forget to clear the log file 
And I've see other security breach, the composer.json file is also accessible and the file give informations about informations of vendors and used framework. I think the rule in htaccess file to block direct access to .php files isn't the goodest solution, create a public folder with views and app folder inaccessible is not a better solution ?

**Comment by daveismyname** [comment]
yes that's a much better solution, it's always possible depending on the users host, in such cases where multiple projects are being used within the single host account common for shared hosting, to that end it's better to let the end developer change the paths as they see fit.

**Comment by max21** [comment]
ok, you can change this in v3 ;)
