### ISSUE TITLE
Integrate Illuminate\Database on SMVC

### ISSUE THREAD

**Issue by josecarlosweb** [simple-mvc-framework/framework#217]
Anybody tried integrate the package Database of Illuminate on SMVC? I seen this tutorial: http://laravel.io/forum/03-06-2014-using-illuminatedatabase-outside-of-framework. if anybody did is, please tel me your experience.

**Comment by daveismyname** [comment]
I tried it back on 2.1 have a look at this video http://simplemvcframework.com/screencasts/v2.1/using-laravel-s-eloquent-orm

**Comment by josecarlosweb** [comment]
OMG it's amazing. Sorry, i don't search in website of SMVC before of ask. I'll try to did this now. Thank You!!

**Comment by daveismyname** [comment]
no worries :+1:

**Comment by jimgwhit** [comment]
Also there's a post on it at forum, read that.  But really it's not an issue, this should have been on forum.
