### ISSUE TITLE
paths

### ISSUE THREAD

**Issue by jimgwhit** [simple-mvc-framework/framework#233]
@daveismyname when I tested the very latest ver 3 beta on 12/12/2015 at 9:43 est U.S. I ran into this:  
IN the new paths.php file you have
```
define('APP', dirname(__DIR__).'/app/');
define('SYSTEM', dirname(__DIR__).'/system/');
define('PUBLICDIR', dirname(__FILE__).'/');
define('ROOT', dirname(__DIR__).'/');
```
On dev server my test folder is fm3  so htdocs\fm3  
When I loaded at first I got: 
Please install via composer.json

Install Composer instructions: https://getcomposer.org/doc/00-intro.md#globally

Once composer is installed navigate to the working directory in your terminal/command promt and enter 'composer install'  
However if I change paths to below it works
```
define('APP', 'app/');
define('SYSTEM', 'system/');
define('PUBLICDIR', './');
define('ROOT', './');
```

The
```
dirname(__DIR__)
```
is raising dir name to htdocs instead of fm3  
Is this correct or a problem?  Again local dev server.

**Comment by jimgwhit** [comment]
Ok if I change all occurances of
```
dirname(__DIR__)
```
to
```
dirname(__FILE__)
```
it also works.

**Comment by daveismyname** [comment]
bugger I thought that would work with no change required, I'll do more tests on different setups.

**Comment by daveismyname** [comment]
I've updated the paths and index.php can you try this again.

**Comment by jimgwhit** [comment]
I tried several combinations of /, ./, ../  Stil don't work. last try was
```
define('APP', realpath('/app').DIRECTORY_SEPARATOR);
define('SYSTEM', realpath('/system').DIRECTORY_SEPARATOR);
define('PUBLICDIR', realpath('').DIRECTORY_SEPARATOR);
define('ROOT', realpath('').DIRECTORY_SEPARATOR);
```
I echoed out ROOT and got
```
C:\\
Please install via composer.json

Install Composer instructions: https://getcomposer.org/doc/00-intro.md#globally

Once composer is installed navigate to the working directory in your terminal/command promt and enter 'composer install'
```
But changing back to:
```
define('APP', dirname(__FILE__).'/app/');
define('SYSTEM', dirname(__FILE__).'/system/');
define('PUBLICDIR', dirname(__FILE__).'/');
define('ROOT', dirname(__FILE__).'/'); 
```
works.  So far all I tested in welcome page, I haven't put in the  
database part and tested other routes or controllers yet.

**Comment by jimgwhit** [comment]
After looking at the php manual:
```
7.0.0 	Added the optional levels parameter.
5.0.0 	dirname() is now binary safe 
```
```
echo dirname("/etc/passwd") . PHP_EOL;
echo dirname("/etc/") . PHP_EOL;
echo dirname(".") . PHP_EOL;
echo dirname("/usr/local/lib", 2);

The above example will output something similar to:

/etc
/ (or \ on Windows)
.
/usr

```
I think dirname(__FILE__) is what's needed
```
To get the directory of current included file: from php manual

<?php
dirname(__FILE__);
?> 
```
Also another note stated
```
Attention with this. Dirname likes to mess with the slashes.
On Windows, Apache: 
```
I am going to try to research this more.

**Comment by jimgwhit** [comment]
I think I got it try this, works for local, not sure on the move higher dir,
please experiment with.
```
define('APP', realpath(__DIR__.'/app').DIRECTORY_SEPARATOR);
define('SYSTEM', realpath(__DIR__.'/system').DIRECTORY_SEPARATOR);
define('PUBLICDIR', realpath(__DIR__).DIRECTORY_SEPARATOR);
define('ROOT', realpath(__DIR__).DIRECTORY_SEPARATOR);
```
That's local but the move up would be
```
define('APP', realpath(__DIR__.'../app').DIRECTORY_SEPARATOR);
define('SYSTEM', realpath(__DIR__.'../system').DIRECTORY_SEPARATOR);
//NOT SURE ABOUT PUBLICDIR
define('ROOT', realpath(__DIR__.'../').DIRECTORY_SEPARATOR); // NOT SURE ON THIS LINE TEST PLEASE MIGHT GET TWO //
```

**Comment by daveismyname** [comment]
I need to test this out on a local windows server as the following works perfectly for me on my localhost (mac) and on a live server (linux)

````
define('APP', realpath('../app').DIRECTORY_SEPARATOR);
define('SYSTEM', realpath('../system').DIRECTORY_SEPARATOR);
define('PUBLICDIR', realpath('./').DIRECTORY_SEPARATOR);
define('ROOT', realpath('../').DIRECTORY_SEPARATOR);
````

**Comment by jimgwhit** [comment]
See latest reply, I got that from a laravel config file and it works on windows and linux for sure.

**Comment by daveismyname** [comment]
I've not tried on a virtual windows and that works too outputting the constants I get these paths:

````
\\PSF\HOME\Documents\USBWebserver v8.6\root\framework\app\
\\PSF\HOME\Documents\USBWebserver v8.6\root\framework\system\
\\PSF\HOME\Documents\USBWebserver v8.6\root\framework\public\
\\PSF\HOME\Documents\USBWebserver v8.6\root\framework\
````

**Comment by jimgwhit** [comment]
Well after tring several things this worked on local
```
define('APP', realpath('./app').DIRECTORY_SEPARATOR);
define('SYSTEM', realpath('./system').DIRECTORY_SEPARATOR);
define('PUBLICDIR', realpath('./').DIRECTORY_SEPARATOR);
define('ROOT', realpath('./').DIRECTORY_SEPARATOR);
```
The old instructions for local you went from
```
$smvc = '../app/';
$system = '../system/';
$root = '../';
$public = dirname(__FILE__);

``` 
TO
```
$smvc = 'app/';
$system = 'system/';
$root = './';
$public = dirname(__FILE__);
//for local so that is what I tried removing the ../

```
But here I needed
```
./app // like that to work
```
On the virtual windows did you need to change it to ./ instead of ../ to work?

**Comment by daveismyname** [comment]
your paths would imply your have app and system in the same folder as your public files I've been using the setup where the app, system and vendor are in a folder above the public folder.

To have them in the same folder then ./ in the path will mean the current directory.

**Comment by jimgwhit** [comment]
So I have it correct, right?

**Comment by daveismyname** [comment]
Yes looks that way.

**Comment by LuckyCyborg** [comment]
Sorry, but I consider moving of the paths in their file a very unlucky idea. Why? 

This is a personal affair of current index/boot file. For example, I seen usually setups with two applications, living in **/apps**, like **Frontend** and **Backend**, who use **index.php** and **backend.php** to boot them. 

In other hand, if you changed the Proud Path, SMVC, into APP, why not to use this style:

DS - DIRECTORY_SEPARATOR

FCPATH     -> public directory
APPPATH   -> application
SYSPATH   -> system
BASEPATH -> SMVC's root 

For example, we successfully use this code into index/boot file:

```php
// Flag required by Profiling
define('FRAMEWORK_STARTING_MICROTIME', microtime(true));

// Paths definition
define('DS', DIRECTORY_SEPARATOR);

define('FCPATH', dirname(__FILE__) .DS);

define('BASEPATH', dirname(FCPATH) .DS);

define('APPPATH', dirname(FCPATH) .DS.'app'.DS);
```
