### ISSUE TITLE
3.0 beta routes - catch all

### ISSUE THREAD

**Issue by daveismyname** [simple-mvc-framework/framework#235]
@LuckyCyborg how do you create a catch all route?

I have a CMS that I use a catch all to look at the requests, this is what I normally use:

````
//pass anything uncaught to pages
Router::any('(:all)', 'App\Controllers\Pages@fetch');
````

but that fails to match if I add a . to the patten it almost matches but then removed the first letter of the match:

````
//pass anything uncaught to pages
Router::any('.(:all)', 'App\Controllers\Pages@fetch');
````

For instance the url http://mvc:8888/cms/public/ok

returns The page 'k' cannot be found it's stripping out the first letter.

I have a bunch of routes for the admin then this catch all to collect any requests that have not yet matched anything the idea is to pass that to a pages controller, then the controller loads up the correct section.

**Comment by LuckyCyborg** [comment]
Hello, in principle, the (new) Router is compatible point-to-point with the older one, by Design. So, a catch-all route will be, like previous: 
```
//pass anything uncaught to pages
Router::any('(:all)', 'App\Controllers\Pages@fetch');
```

Still, I don't understand  why you need the literal additional point in route pattern. To note that '.' have a meaning for regex. IF really want to start your routes with point, you need to escape it in the REGEX style:

```
//pass anything uncaught to pages
Router::any('\.(:all)', 'App\Controllers\Pages@fetch');
```

That match URI like:

```
/.something/starting/with/point
```

**Comment by daveismyname** [comment]
i don't want to have to put anything in simply:

````
Router::any('(:all)', 'App\Controllers\Pages@fetch');
````

the route does not match when I try to run that I get a 404

**Comment by LuckyCyborg** [comment]
OK, tomorrow I will take a look. To be honest, we aren't used yet a catch-all route (or I don't seen, personally), but, yeah, make sense to use one in a CMS.

In other hand, Sorry, but I consider moving of the paths in their file a very unlucky idea. Why? 

This is a personal affair of current index/boot file. For example, I seen usually setups with two applications, living in **/apps**, like **Frontend** and **Backend**, who use **index.php** and **backend.php** to boot them. 

In other hand, if you changed the Proud Path, SMVC, into APP, why not to use this style:

DS - DIRECTORY_SEPARATOR

FCPATH     -> public directory
APPPATH   -> application
SYSPATH   -> system
BASEPATH -> SMVC's root 

For example, we successfully use this code into index/boot file:

```php
// Flag required by Profiling
define('FRAMEWORK_STARTING_MICROTIME', microtime(true));

// Paths definition
define('DS', DIRECTORY_SEPARATOR);

define('FCPATH', dirname(__FILE__) .DS);

define('BASEPATH', dirname(FCPATH) .DS);

define('APPPATH', dirname(FCPATH) .DS.'app'.DS);
define('SYSPATH', dirname(FCPATH) .DS.'system'.DS);
```

**Comment by LuckyCyborg** [comment]
Hi again, 

While changing nothing to my SMVC installation, I added a new method to ```\App\Controllers\Demo```

```
    public function catchAll($str)
    {
        echo htmlspecialchars($str, ENT_COMPAT, 'ISO-8859-1', true);
    }
```

and a new Route as last:
```
Router::any('(:all)', 'App\Controllers\Demo@catchAll');
```

The results can be seen in:

http://smvc3.giulianaeassociati.com/testing/the/catch/all

**Comment by daveismyname** [comment]
thank you turns out it's working for anything after the project url so for /test works but when nothing is entered ie when going to the root the path contained a / and I was looking for null as it was in the past. 

I've updated my catch to look for a / instead.
