### ISSUE TITLE
PhpMailer in 3.0

### ISSUE THREAD

**Issue by tomvlk** [simple-mvc-framework/framework#236]
FIrst of all, there has been a security patch for PHPMailer. See https://github.com/PHPMailer/PHPMailer/blob/master/changelog.md.

But this also adds a question for maintaining it within the framework or let it be used separately with composer require. (just like Gump can be/already is in 3.0).

**Comment by daveismyname** [comment]
yes it would make sense to include it with compose then have a mail helper to do the custom methods that we currently use so it's got consistent calls and can be adapted without touching the base classes

**Comment by tomvlk** [comment]
With the additional helper it would be cool to have the config also defined in the smvc config. :+1:

**Comment by LuckyCyborg** [comment]
I subscribe to leave the PhpMailer management to Composer and to implement a simple Helper on top of Composer shipped package. That's very useful from a security POV. :+1:

**Comment by tomvlk** [comment]
The helper could also extend PHPMailer so it will function like its on its own.

**Comment by LuckyCyborg** [comment]
@tomvlk Yep, that's idea! :smirk:

**Comment by daveismyname** [comment]
I was quite new to composer at v1.0 so it was bundled together, it really should not have been.

**Comment by tomvlk** [comment]
See my pull request: https://github.com/simple-mvc-framework/framework/pull/244

**Comment by LuckyCyborg** [comment]
Good Job with Mailer refactoring! :+1:

**Comment by tomvlk** [comment]
I had this issue when writing different mailing instances and always having to copy code for the settings only. Now thats solved too :grinning:

**Comment by LuckyCyborg** [comment]
@tomvlk Who take care of **Gump**? You'll step up, we take it us?

**Comment by tomvlk** [comment]
Well. I gotta say, Gump a-like can be made and be fully integrated with the framework. Maybe something to consider. And just for validating $_POST and $_GET body parameters.

**Comment by LuckyCyborg** [comment]
I think about a \Helpers\Validator class. What I don't like to Gump is the lack of internationalization. 

And almost all of our projects need to speak English and Italian, while the speaker of one language usually do not known another one. 

Yet, we managed to extend GUMP to make it INTL. Still, to include it in SMVC, we need to arrive to **\Core\Language**... :smirk:

**Comment by tomvlk** [comment]
And it could be used with much less code (in the controller). Please make it as much object oriented as it's possible :laughing:

**Comment by LuckyCyborg** [comment]
Think we arrive at something like:

```
        $config = array(
            'username' => array(
                'label'  => __d('user', 'User Name'),
                'rules'  => 'required|unique_username|valid_name|max_len,30|min_len,5',
                'filter' => 'trim|sanitize_string'
            ),
            'password' => array(
                'label'  => __d('user', 'Password'),
                'rules'  => 'required|strong_password',
                'filter' => 'trim'
            ),
            'confirm_password' => array(
                'label'  => __d('user', 'Confirm  Password'),
                'rules'  => 'required|equalsfield,password',
                'filter' => 'trim'
            ),
            'firstname' => array(
                'label'  => __d('user', 'First Name'),
                'rules'  => 'required|valid_name|max_len,30|min_len,5',
                'filter' => 'trim|sanitize_string'
            ),
            'lastname' => array(
                'label'  => __d('user', 'Last Name'),
                'rules'  => 'required|valid_name|max_len,30|min_len,5',
                'filter' => 'trim|sanitize_string'
            ),
            'email' => array(
                'label'  => __d('user', 'E-mail'),
                'rules'  => 'required|valid_email',
                'filter' => 'trim|sanitize_email'
            ),
            'userlevel' => array(
                'label'  => __d('user', 'User Level'),
                'rules'  => 'integer|max_numeric,255|min_numeric,0',
                'filter' => 'trim|sanitize_numbers'
            ),
        );

        if(Request::isPost()) {
            if (! Csrf::isTokenValid()) {
                Url::redirect('login');
            }

            $validator = new Validator($config);

            //
            $postData = $validator->run($_POST);

            // Check if validation was successful
            if($postData !== false) { 
                //blah, blah, blah
            }
```

It is **OOP** enough?

**Comment by tomvlk** [comment]
Haha. Ok for me. 
Maybe implement it with a form generator. Reminds me about making that one universal to implement themes etc (bootstrap please 😀)
Ye. A lot of ideas here.

**Comment by daveismyname** [comment]
is this still needed here? I think this topics have been covered in the other issues.
