### ISSUE TITLE
Cannot render view

### ISSUE THREAD

**Issue by jimgwhit** [simple-mvc-framework/framework#237]
On the original ver 3 beta all worked, but in the very latest as of 12-13-2015 1:55 CST U.S. I am getting this error in apache error log:  
[Sun Dec 13 13:44:44.918255 2015] [:error] [pid 6940:tid 1192] [client ::1:50297] PHP Fatal error:  Call to a member function renderTemplate() on null in C:\\BitNami\\wampstack-5.6.2-0\\apache2\\htdocs\\fm3\\app\\Controllers\\Dog.php on line 46  
I have made no other changes except the latest things @daveismyname put in like new router, new index, etc. Welcome page comes up fine.

**Comment by daveismyname** [comment]
are you using $this->view? instead of View:: still as that was removed from the Core\Controller.php

**Comment by jimgwhit** [comment]
Header shows up now, but new error:  
2015-12-13 14:12PM - require(C:\BitNami\wampstack-5.6.2-0\apache2\htdocs\fm3\app\views/dog/index.php): failed to open stream: No such file or directory in C:\BitNami\wampstack-5.6.2-0\apache2\htdocs\fm3\system\Core\View.php on line 34

**Comment by jimgwhit** [comment]
Never mind, when I copy my dogs view folder, I pasted in wrong place my boo boo.

**Comment by daveismyname** [comment]
I removed it as it's not used at all in my tutorial or the release of 2.1 or 2.2 it's back from the original version I believe, it's not a big deal to have that back in if you have projects that do it that way.

**Comment by jimgwhit** [comment]
No big deal, netbeans has a find and replace in projects.  The original ver 3 beta worked that way still.
