### ISSUE TITLE
Paths revisited

### ISSUE THREAD

**Issue by jimgwhit** [simple-mvc-framework/framework#238]
@LuckyCyborg and @daveismyname 
@LuckyCyborg replied on the other issue the following:

Sorry, but I consider moving of the paths in their file a very unlucky idea. Why?

This is a personal affair of current index/boot file. For example, I seen usually setups with two applications, living in /apps, like Frontend and Backend, who use index.php and backend.php to boot them.

In other hand, if you changed the Proud Path, SMVC, into APP, why not to use this style:

DS - DIRECTORY_SEPARATOR

FCPATH -> public directory
APPPATH -> application
SYSPATH -> system
BASEPATH -> SMVC's root

For example, we successfully use this code into index/boot file:

// Flag required by Profiling
define('FRAMEWORK_STARTING_MICROTIME', microtime(true));

// Paths definition
define('DS', DIRECTORY_SEPARATOR);

define('FCPATH', dirname(__FILE__) .DS);

define('BASEPATH', dirname(FCPATH) .DS);

define('APPPATH', BASEPATH.'app'.DS);
define('SYSPATH', BASEPATH.'system'.DS); 
 
My topic starts here:

Since paths can be hard to figure out, when you do go forward with ver 3 
please include the varoius instructions for various setup situations, like  
- All under public_html (www on some, htdocs on some)  
- A setup where you are above htdocs but in a folder and templates are under htdocs 
like:  
```
apache2
        mysite //here above htdocs
                app
                system
                vendor
        htdocs
                mypublic
                        index.php
                        other
```
Instructions were given for the initial realease of the 3 beta, but now with  
this new style of resolving paths
```
define('APP', realpath('./app').DIRECTORY_SEPARATOR);
define('SYSTEM', realpath('./system').DIRECTORY_SEPARATOR);
define('PUBLICDIR', realpath('./').DIRECTORY_SEPARATOR);
define('ROOT', realpath('./').DIRECTORY_SEPARATOR);

```
A good detailed page of instructions in the new docs would be good.  I have a yek of a time
figuring out now is it / or ./ or ../ or ../../  
Not really a problem, but I think resolving paths is very hard.

**Comment by woodsy1** [comment]
Once the tutorial section is up and running I will post my solution for folder structure with Git.
It moves everything into its own folder and all very neat :)

**Comment by jimgwhit** [comment]
Looking forward to seeing how the git uploading works, like Dave I do it manually now.

**Comment by jimgwhit** [comment]
@LuckyCyborg as of now paths are working, I just want good docs on it in case there are more changes. For me resolving paths has always been hard.

**Comment by LuckyCyborg** [comment]
@jimgwhit Your paths now works, but what if your website contains **TWO applications** ?

I seen, no one time, a duet of **frontend / backend apps**, first for the **Frontend** site, another for **Administration**. It is a usual situation in the more complex websites.

Come on, this design is not even specific for MVC, for example, even **Joomla!** sports one!

**Comment by daveismyname** [comment]
closed, due to structural changes.
