### ISSUE TITLE
Is it time to give this framework its own unique name?

### ISSUE THREAD

**Issue by kowston** [simple-mvc-framework/framework#240]
I've been working with this Framework for a long time now and while I think the name Simple MVC Framework has served it well I do feel that as it continues to grow in popularity it may be time for a more distinguishable name. Version 3.0 seems like the right time to make a change like this.

I'm not throwing names out there just yet, but I am curious what the rest community thinks.

Something that sets it apart like the popular frameworks:
Laravel. CodeIgniter. Zend Framework. CakePHP. Symfony. Phalcon. Yii. 
Something that lends itself to a unique style of branding.

**Comment by LuckyCyborg** [comment]
How about **Dave's Framework** ?

**Comment by daveismyname** [comment]
> How about Dave's Framework ?

haha! with things getting a little more advanced maybe it's not so "Simple" anymore. I'm not actively looking to rename the framework but if the right suggestion is made......

**Comment by kowston** [comment]
> maybe it's not so "Simple" anymore

Disagree, it's getting more powerful but essentially a beginner can still come along and pick it up fairly quickly, so simple is still a good description. I'm thinking more about it being generic and easy to confuse with some other framework and being a bit of a mouthful to say. 

Sorry if I sound presumptuous by creating this post that wasn't my intention.

**Comment by BryanYeh** [comment]
Other frameworks are named with 1 word, so call it Simplicity.

**Comment by LuckyCyborg** [comment]
For our projects, we need **a powerful feline**. While are not afraid to tame **Tigers** (Laravel), or **Lions** (CodeIgniter), this time we need a special kind of feline, powerful yet built for speed, a **Cheetah**, small, smart and faster than The Hell. That's why we are there, to tame this special kind of feline.

How about **Cheetah Framework**?

**Comment by daveismyname** [comment]
wow I really like that!! I love the build up too awesome!!

**Comment by daveismyname** [comment]
> Other frameworks are named with 1 word, so call it Simplicity.

it's good but it's used already.

**Comment by kowston** [comment]
That's what I'm talking about, something with a backstory, love it!

**Comment by tomvlk** [comment]
@LuckyCyborg Really nice name indeed.

**Comment by jimgwhit** [comment]
I say keep the current name.

**Comment by LuckyCyborg** [comment]
@jimgwhit As expected from you... :smirk:

**Comment by tomvlk** [comment]
In my opinion it's not simple anymore and the current name is too generic and not ready for v3.0 :laughing:

**Comment by jimgwhit** [comment]
I just wonder if the logo on the sticky note will also have to change  
"Keep it simple"   
Which is why I like the framework. 
I came from a database management background, which are my interest. That is why SMVC worked so great, you could quickly get into managing and dealing with database records. 
You didn't have to worry about entities, repositories, special services, or stuff that had absolutely nothing to do with a database management system.

**Comment by jimgwhit** [comment]
And by the way folks an entity is nothing more than a record from a table, why some people have to come up with modern names just to make themselves sound good, I can't understand.

**Comment by woodsy1** [comment]
New name sounds awesome!

**Comment by tomvlk** [comment]
@jimgwhit Why don't you understand that entity is not a record. Record is database specific on MySQL and other relational databases (you should know with your database background right?!).
When using a document database it's documents, you could name these together as entities...
Also, you could still use the old style database here.
I don't know why you just keep complaining abou things that are not true! So stop firing with facts that are not correct or are just thoughts with no substantiation. 
Instead, what you said earlier, make your own framework if you need it to be that specific, or stay on 2.* when you don't like the new features. 

Also, your opinion is not everyone's... :pineapple:

**Comment by jimgwhit** [comment]
@tomvlk you people don't care about facts, you already made up your mind what you are going to do. I imagine that you are one of those who believe there is really is such thing OOP programming. Well a super fast lesson, all programming is procedural. Yes you can have separate classes, one class may get results from another class, but when all is said and done at the machine language level it's still all broken down procedurally. That's why it cracks me up when someone comes up with five different classes to achieve one thing. Yes I like  MVC,  but I just cannot believe people think that there is true object oriented programming, a separation of code yes but still processed procedurally. And that is an absolute undisputed fact.  
So now my next question is how and where to use (integrate) eloquent query builder, or have you made it to where you cannot integrate and use eloquent any longer?

**Comment by LuckyCyborg** [comment]
@jimgwhit You can use **Eloquent** as always, but I for one, I will look to methods to integrate **Doctrine**, eventually... Don't shoot me, you known, it's something similar with the music, some love  Justin Bieber, I for one, I'm with Metallica... :smirk:

**Comment by geomorillo** [comment]
I really don't like animal names for software, please dont change the topic @jimgwhit @LuckyCyborg

**Comment by jimgwhit** [comment]
I have used doctrine Dbal but not the orm, didn'the like the orm.  But the one I do not like is the one that will be implemented.

**Comment by jimgwhit** [comment]
@geomorillo  you are right dB should be another topic.

**Comment by jimgwhit** [comment]
Tomvlk framework

**Comment by daveismyname** [comment]
@jimgwhit I'm really confused you're constantly talking about Laravel and comparing to Laravel. It sounds like what you want is Laravel.

You can still bring in eloquent just as you have in the past.

**Comment by kowston** [comment]
> why some people have to come up with modern names just to make themselves sound good, I can't understand

This suggestion is about setting the Framework apart from others, not trying to sound good. Sounding good may happen but that is subjective and depending on your own opinion of the name. 

I Searched GitHub for Simple MVC Framework and this framework was not even on the first page, a new name could change that and help it stick in the memory of developers.

> I just wonder if the logo on the sticky note will also have to change

I would expect version 2.2 to remain the same in Name, URL, branding, logo. It's Dave's decision of course.

Re-branding for version 3 I think is a good idea, if done well could help the Framework become more popular and increased popularity has seen the framework evolve into what it is becoming today, something many seem to see as a positive.

**Comment by tomvlk** [comment]
@kowston agree on the name change, we should do it because the current name isn't unique. 
Also, moving a branch to a different repo (technical thinking of rebranding) is not a lot work, just add another remote to git and push to it from the current branch (just technical thinking :gem:)

**Comment by kowston** [comment]
> i dont have any ideas for names right now

@geomorillo same, despite being the one to bring it up, going to try and come up with something.

**Comment by jimgwhit** [comment]
@kowston in my above comment on fancy names I was talking about database and entity nothing to do with the framework name. And if you look I've come up with the name we should use breeze. Point blank case closed. Breeze is the best name.

**Comment by LuckyCyborg** [comment]
To be honest, we don't care how is called the framework, if we have our **Cheetah**... :smirk:

**Comment by jimgwhit** [comment]
Oh one other name idea BUFF Framework. I used to work on b-52's, and the b-52 is Nick named buff, I bet you don't know what buff stands for. 
Big ugly fat fellow. But the B 52 was always beautiful to me. 
So Breeze or Buff.

**Comment by LuckyCyborg** [comment]
Big ugly fat fellow? Uh! Oh! That's Laravel!

**Comment by jimgwhit** [comment]
Now another member has already agreed that they do not like animal names neither.

**Comment by LuckyCyborg** [comment]
We have no interest in the Framework's name. Us we call it **Dave's Framwork**.

**Comment by daveismyname** [comment]
I think a poll would be good with the option to suggest your own name and see what the results are if nothing else it could be interesting.

@licky yeah is a too long I like your suggestion ha but does not encourage community :)

**Comment by LuckyCyborg** [comment]
@LuckyCyborg ,please! This is my pseudonym. :smirk:

**Comment by daveismyname** [comment]
Sorry I realised after posting I got it completely wrong.

OK I'll take a look once back in front of my computer

**Comment by daveismyname** [comment]
> I think a poll would be good with the option to suggest your own name and see what the results are if nothing else it could be interesting.

OK here it is vote away, also you can add your own options too! http://goo.gl/WGFw7k

**Comment by geomorillo** [comment]
I have a name KITS or KITS FRAMEWORK , kits stands for keep it simple

**Comment by kowston** [comment]
@jimgwhit my apologies I missed your other comment so read out of context.

**Comment by kowston** [comment]
Nova / Nova Framework / Nova MVC

I like the idea of using an Astronomy term as often the language used in Astronomy is easy to understand and learn like this framework. Nova - when a star increases in brightness for a period of time.

Magma / Magmatic
Magma - hot and fluid material within the earth crust that can form rock when cooled. The framework is the magma to your project but you create a solid project.

Both names to me suggest transformation and stability

@daveismyname is it possible to add the new suggestions to the poll

**Comment by tomvlk** [comment]
@kowston Really like the Nova Framework and Magmatic suggestions!

**Comment by daveismyname** [comment]
I love Nova! the poll is not editable I'll look for a better service for that.

**Comment by daveismyname** [comment]
I've had to create the poll again so I can now edit it and add new options to here it is again, http://goo.gl/tMcydA

The status unfortunately have been reset so please vote again.

**Comment by ImEmil** [comment]
Seems like Nova is my type of Candy, NovaMVC sounds pretty good if you ask me 😉

**Comment by daveismyname** [comment]
Looks like Nova is the winner!

**Comment by LuckyCyborg** [comment]
@daveismyname BTW, you need a new namespace for your System...

How about **\Nova** ? We arrive to something like:
```php
use Nova\Net\Router;
```

**Comment by daveismyname** [comment]
Yes absolutely thank you.

**Comment by LuckyCyborg** [comment]
OK! I will do it today.

Also, stay tuned, I'm about to do a pull-request containing Nova's Validator class. In several minutes is UP.

**Comment by daveismyname** [comment]
:+1:

**Comment by LuckyCyborg** [comment]
@daveismyname Pull request for System's namespace changing incoming in several hours, max.

And my and my colleagues, we want to say you **Congratulations for Nova Framework!**

**Comment by geomorillo** [comment]
Really awesome work

**Comment by volter9** [comment]
@tomvlk and @LuckyCyborg you did a great job! :)
