### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by jimgwhit** [simple-mvc-framework/framework#246]
The readme or instructions for 3.0 beta is not staying caught up with all the latest changes that's happening every 2.5 minutes,  prior to this moment here I have been testing the heck out of this thing for @daveismyname  but without the instructions Being caught up as changes are made how can I get it going properly and continue testing? People people slow down if you make some change in your pull request also update the readme at least put something in there for crying out loud you getting out of hand. Just a quick note about the change would be nice but put it in the readme.md real quick.

**Comment by jimgwhit** [comment]
@daveismyname in case you didn't see it in the other issue, is the way of using the database helper completely gone now, is there a whole new way to have to set up and use databasing? Will eloquent still work with SMVC?

**Comment by jimgwhit** [comment]
@daveismyname  why is the code from database helper in the framework twice now.  And are you seriously going to keep that new database stuff in there when already if people did not want to use the database helper they could use eloquent right now, you even did a video on that.

**Comment by tomvlk** [comment]
In the current branch you can still use the Smvc\Helpers\Database. But it's recommended to move away from it as I think it will be removed. (And I hope so).

About the documentation, I agree we should update it, but I did wrote some instructions inside of the closed pull requests.
You should take a look there:
https://github.com/simple-mvc-framework/framework/pull/241
https://github.com/simple-mvc-framework/framework/pull/243

Why not provide multiple options, and stay open for the developer too choose the one he wants....

**Comment by daveismyname** [comment]
there's been a lot of activity today I'm at work so cannot fully test it but I DO PLAN TO test these, I've said in the readme the instructions will be updated once these changes are finalised to make it easier for you once have all the information.

**Comment by jimgwhit** [comment]
@tomvlk  the database helper will be replaced with what?

**Comment by LuckyCyborg** [comment]
@jimgwhit  With our own **DBAL** written by @tomvlk ?

**Comment by jimgwhit** [comment]
@daveismyname I know I have no say so, but I beg you to please slow down that service stuff should have nothing to do with databases at all. Look at how laravel uses the query builder, services has nothing to do with that. Services are supposed to be specialized classes. I  already gave a good example of how laravel uses service classes did people just not to understand that?
 I think @tomvlk means well, but we would be better off just using eloquent and the query builder if @tomvlk wants to kill off the database helper which I like using. The key to the framework was the easy to use database helper by Killing that Dave you will killing the framework.

**Comment by jimgwhit** [comment]
What was wrong with Dave's DBAL?

**Comment by LuckyCyborg** [comment]
@jimgwhit No one kill your beloved Database, it is just somewhat enhanced, from what I seen. 

You can use, as always, your favorite coding style, you just have to call the Database in a different way. And while this thing is done in **\Smvc\Core\Model**, you can practically ignore the changes.

**Comment by jimgwhit** [comment]
In previous comment you said replaced.

**Comment by tomvlk** [comment]
I think it will be replaced before 3.0 release, or at least that would be good to prevent it from not working anymore after some changes. 
And just because 3.0 is a major new version with breaking changes..

**Comment by LuckyCyborg** [comment]
@jimgwhit While right now you use:

```php
$database = new \Smvc\Helpers\Database::get();
```

In future you have to write:

```php
$database = \Smvc\Core\Database\EngineFactory::getEngine();
```

That's all! From there you use your style coding as always.

**Comment by jimgwhit** [comment]
Where does this line go
~~~
$database = \Smvc\Core\Database\EngineFactory::getEngine();
~~~

**Comment by LuckyCyborg** [comment]
@jimgwhit Right what **\Helpers\Database::get()** used to do...

**Comment by woodsy1** [comment]
@jimgwhit please try to read and understand others comments before you get upset about what is coming. You are creating alot of noice over what is not a big deal as lucky has pointed out a number of times.
