### ISSUE TITLE
The method load() contains an exit expression.

### ISSUE THREAD

**Issue by tomvlk** [simple-mvc-framework/framework#250]
#### Occurred on:
+ **Commit**:  5e33bb09392aae79fc27ce069d233df95ccbfcea
+ **File**:    [app/Core/Language.php](https://github.com/simple-mvc-framework/framework/blob/5e33bb09392aae79fc27ce069d233df95ccbfcea/app/Core/Language.php)
+ **LineNum**: [39](https://github.com/simple-mvc-framework/framework/blob/5e33bb09392aae79fc27ce069d233df95ccbfcea/app/Core/Language.php#L39)
+ **Code**:    `            die;`

    
#### Currently on:
+ **Commit**:  33f1632afadc6f92abfa4b73178c18750085c061
+ **File**:    [system/Core/Language.php](https://github.com/simple-mvc-framework/framework/blob/33f1632afadc6f92abfa4b73178c18750085c061/system/Core/Language.php)
+ **LineNum**: [45](https://github.com/simple-mvc-framework/framework/blob/33f1632afadc6f92abfa4b73178c18750085c061/system/Core/Language.php#L45)

## Solution
Should be better to throw a Exception instead, so it will be captured by the Logger or any other try catch block.

**Comment by LuckyCyborg** [comment]
Take easy, my friend. On our next refactoring is targeted right on **\Smvc\Core\Language**, then lets the actual class to die peacefully... :smirk:

**Comment by tomvlk** [comment]
:+1: 
Just came across this one in Codacy :laughing:

**Comment by LuckyCyborg** [comment]
@tomvlk The class on discussion on this thread doesn't exists anymore. I suggest you to close this thread, not being actual now.

**Comment by tomvlk** [comment]
:+1:
