### ISSUE TITLE
Framework

### ISSUE THREAD

**Issue by jimgwhit** [simple-mvc-framework/framework#251]
How about an honest opinion, if SMVC did not exist which framework would you use?

**Comment by nhymxu** [comment]
Slim for quick API and sometime for quick site with simple structure.
Sometime cakephp and sometime Yii2

**Comment by daveismyname** [comment]
If it wasn't around then I would look around and think nope and build my own....oh wait! lol

**Comment by kowston** [comment]
Honestly don't think I would have tried a Framework if it hadn't been for Dave's influence.

Code Igniter is the only one I was ever close to trying just because it seemed easy to get started and had plenty of getting started resources, coming from a design background here though so cannot give technical reasons.

**Comment by Kingorgg** [comment]
Before I used SMVC, I used Code Igniter, seemed easy enough for what I wanted.

**Comment by jimgwhit** [comment]
Well I have used laravel for one project and I have used cake in past, what drew me to SMVC is it was simple and to the point. I am just hoping it doesn't become the monster that the previous two I mentioned became. I definitely like it simple and easy.  It should not take thousands of lines of code in the background to query and return a list of database records.  
I just feel I am alone here, it seems a lot of you want it to be a much larger framework now like the above mentioned ones. 
Am I really wrong for wanting Dave to keep it simple and easy to use?

**Comment by jimgwhit** [comment]
@daveismyname , I know how to implement illuminate / eloquent in ver 2.2, can you give me a quick synopsis on implementing it in version 3. I am on mobile device now will ask more detailed when I am on desktop.

**Comment by daveismyname** [comment]
@jimgwhit your not wrong for keeping things easy to use, but change does not always mean it's going to be difficult to use.

It's should be no different, include with composer, instantiate in the core model and then use in models. 

I'll be able to look over this better later in the week need to spend some time testing as time allows I have other commitments this week that's making this not so easy to do.

**Comment by jimgwhit** [comment]
@daveismyname Thanks, and thanks for the select thing also.

**Comment by jimgwhit** [comment]
Thanks to all who replied.

**Comment by geomorillo** [comment]
Well im late, just arrived to nederlands, but before i used codeigniter
