### ISSUE TITLE
Temp instructions

### ISSUE THREAD

**Issue by jimgwhit** [simple-mvc-framework/framework#261]
I know the finalized instructions aren't out yet, but it sure would be nice to have some quick temp instructions after all the changes to set up and test, with the new bootstrap as part of the config, and two config files I have no idea on how to setup and test the thing.

**Comment by LuckyCyborg** [comment]
@jimgwhit There is no need to be Sherlock Holmes for setting-up a website in the current SVMC 3.0 tree. 

Just look at those config files and think 10 seconds...  

So, **bootstrap.php** is well, the framework's bootstrap file, like you are suspecting. Nothing now for a Laravel or CakePHP veteran, right?

Remain the mistery of new files. Which, really, are for configuration just two of them, like you already suspect.

We have **config.php** and **constants.php**, then concentrate on second one. What that name, containing just the word **constants** will suggest you?

Use the Force, Jim! What the name **constants** suggest you?

**Comment by daveismyname** [comment]
I've downloaded the updated files and installed almost instantly I'll do a proper write up later but as mentioned above its not that different inside constants set your path and in config set your db settings

I've got my local version with the templates along with everything else above the doc root leaving only index.php and .htaccess in the doc root I need to try that out on a real server become committing that to the framework.

**Comment by LuckyCyborg** [comment]
@daveismyname Nice addition! I can wait to see it! 

BTW, I hope that there are no conflicts between Routing's Assets Serving and Assets's files pre-processing.

**Comment by daveismyname** [comment]
I only tried it briefly but everything seemed to be running fine, obviously I need to do deeper testing.

**Comment by jimgwhit** [comment]
@LuckyCyborg and @daveismyname do the same files and folders get moved from public to same folder as app and system for local development? Like original 3.0 instructions, that's what I meant.

**Comment by LuckyCyborg** [comment]
@I have a better idea. We should don't move nothing. With a **.htaccess** we can redirect on-fly all request to **/public** with no other modifications. 

Then, both from framework's root and **/public** the site will behave the same. I will add it in the actual pull-request.

**Comment by jimgwhit** [comment]
@LuckyCyborg What! I use
~~~
Site/dog
~~~
Not
~~~
Site/public/dog
~~~
And if the folders and files aren't in main folder then you can see folder list, that's not good.

**Comment by LuckyCyborg** [comment]
@jim Don't worry! This setup is used by us with great success. When youtr Framework ROOT in site webroot, you can use as usual **Site/dog**, nothing changed. :smirk:

Practically do not see changes in behavior.

**Comment by jimgwhit** [comment]
@LuckyCyborg and @daveismyname  but if htaccess is in public not root and you type site/ dog you will get folder listing. And I'm referring to local development and shared host where everything has to be under htaccess and not moved up one like a dedicated server.  
Dave's first version of 3.0 beta took care of this, now you saying it's different.  
Leaving htaccess in public will cause security problems on some shared hosts. It appears you are making 3.0 only for people who are using dedicated servers and can move some folders higher than htdocs.

**Comment by LuckyCyborg** [comment]
Don't worry, In my case, the last tests I do with SMVC are in a real website:

http:://smvc3.giulianaeassociati.com 

And in a modern framework, it is **supposed** to be behind the **webroot** access, which should point to **/public** directory, in SMVC case.

I believe that you mix the production with the development stages...

**Comment by jimgwhit** [comment]
@LuckyCyborg but doesn't have to be. @daveismyname you really need to see what's going on with this leaving htaccess and index under public. The framework will be in usable for a lot of people.  
There's even blogs about setting up Laravel where all has to be under HTDOCS, and htaccess and index is moved to root. 
Some shared hosting requires it this way. @daveismyname when 3.0 beta first came you said you would make it so both ways would work, that is your words.

**Comment by LuckyCyborg** [comment]
@jimgwhit Amaze me, what advantage you have, running the Framework from its ROOT in a production server?

And for local testing **usually** we create and use virtual-hosts, something like **www.smvc3.dev**.

It is a trivial thing to configure that, for a person who know barely Linux.

**Comment by jimgwhit** [comment]
@LuckyCyborg and @daveismyname not every freaking person users a virtual host some use a WAMP stack. And I do not know what you are calling root in the above comment, but I'm referring to a whole structure like
~~~
HTDOCS
        Mysite // all of mysite here.
~~~
For crying out loud all of this is covered in detail in the beginning of issue #222. Read all top parts of that issue.  
Cake and Laravel can all be installed under one folder under HTDOCS.

**Comment by tomvlk** [comment]
You can use virtual hosts in a wamp stack.
We could make it that all situations are possible, right?

**Comment by LuckyCyborg** [comment]
@jimgwhit  Oh, now you talk about **development**!

I say again: SMVC, with my modifications, support every bit of those installation styles which you talk about.

I even tried to help you in **development** and I given you an **server.php** file, just like in frakking Laravel. You know what do **server.php**? Same thing do in SMVC, too...

**Comment by LuckyCyborg** [comment]
@tomvlk Yep, Tom, you can use virtual hosts even in WAMP, but is more simple to dump everything in a directory, even you have dozen sites in development. And this thing still WORKS as expected. :smirk:

**Comment by daveismyname** [comment]
> @LuckyCyborg and @daveismyname do the same files and folders get moved from public to same folder as app and system for local development? Like original 3.0 instructions, that's what I meant.

When I did my testing first thing this morning all I had to do was alter the paths so it will work in any place you want it to.

> @LuckyCyborg and @daveismyname but if htaccess is in public not root and you type site/ dog you will get folder listing. And I'm referring to local development and shared host where everything has to be under htaccess and not moved up one like a dedicated server

You can turn directory browsing off to prevent listings, also I use a shared server and can put files above the htdocs folder so that's not true either. I'm not claiming all hosting accounts are the same.

> Leaving htaccess in public will cause security problems on some shared hosts. It appears you are making 3.0 only for people who are using dedicated servers and can move some folders higher than htdocs.

This is also not true. 

> I feel you are moving so fast with changes you're forgetting about various setup scenarios. And that is not a good thing.

It's been mention many times it's still flexbile and will still work in different cases.

> @LuckyCyborg but doesn't have to be. @daveismyname you really need to see what's going on with this leaving htaccess and index under public. The framework will be un-usable for a lot of people.

Give me chance this all happened while I was at work.

**Comment by LuckyCyborg** [comment]
@daveismyname Considering that our friend Jim will continue its claims, following the style "pics or din't happen", I made some case studies with screenshots, in a range of usual situations, in the **SMVC Restructure**.

**Comment by jimgwhit** [comment]
@LuckyCyborg in an earlier comment you said to leave htaccess in the public folder, that confused me, my question then becomes-
If all is going to be under htdocs, doesn't it make more since to still do as in @daveismyname video and move everything that's in public to top level?  When I tried it I changed the index from
```
define('PUBLICDIR', realpath('./').DS);
define('ROOT', realpath('../').DS);
define('APP', ROOT.'app'.DS);
define('SYSTEM', ROOT.'system'.DS);
```
to
```
define('PUBLICDIR', realpath('./').DS);
define('ROOT', realpath('./').DS);
define('APP', ROOT.'app'.DS);
define('SYSTEM', ROOT.'system'.DS);
```
And it worked just like it did in Dave's video.  But you stated that in the newly re-factored version (the one I tested, got from your branch) that I had to leave htaccess in public.  I tested with everything "cut" from public and "pasted" in the site folder in this case
```
apache2
        htdocs
                smvc3
                     moved here
                     index.php
                    .htaccess
                     other
```
Now if it works just like Dave's original instructions and video in issue #222 towards top, then what is the issue with taking .htaccess from public to the smvc3 folder?

**Comment by LuckyCyborg** [comment]
@jimgwhit SMVC3 works, like you haven possibility to see in another thread, in almost all imaginable styles, even without web-server.

You are try to do a configuration, just like in my first case study. like you seen, it works. How to do it:

1 .Nuke from orbit everything from **htdocs/smvc3**, then install SMVC3 in this directory.
2. Move the files from htdocs/smvc3/public to htdocs/smvc3
3. edit htdocs/smvc3/index.php as paths
4. edit htdocs/smvc3/.htaccess where: RewriteBase /smvc3/
5. edit htdocs/smvc3/app/Config/constants.php look to DIR to be: /smvc3/

That should boot your SVMC3

**Comment by jimgwhit** [comment]
@LuckyCyborg that is  exactly what I did already.  Basically followed the video Dave made on the subject.  What confused me is you saying .htaccess had to stay in the public folder now, I take it (I am guessing) it doesn't. So Daves original video and instructions still apply.

**Comment by jimgwhit** [comment]
@LuckyCyborg I think we were on the same page, but a mis-communication happened concerning the .htaccess and public.

**Comment by LuckyCyborg** [comment]
@jimgwhit Then everything is OK now?

**Comment by jimgwhit** [comment]
@LuckyCyborg and @daveismyname not quite, My first test was just to get the welcome page up. 
I tryed to access my database, my url is
```
http://localhost/smvc3/dog
```
Which is supposed to return a list of dogs, like before. But all I am getting 
is a white page with the word dogs at the top now.  I changed out the namespaces
in my Dog controller and DogModel.  Will continue to troubleshoot.

**Comment by LuckyCyborg** [comment]
@jimgwhit See that I added some commits to PR #265 . Re-download it, directly from my fork, for example.

**Comment by jimgwhit** [comment]
@LuckyCyborg wouldn't you know it was Dave's CatchAll Route causing the problem, now @daveismyname what are we going to do with you.

**Comment by jimgwhit** [comment]
@LuckyCyborg see this link
```
http://tjhs.taylorjoneshumane.com/tjhs/dog
```
that is the real production ver 2.2, 
That's what I see now in the ver 3.0 dev after commenting out 
```
//Router::any('(:all)', 'App\Controllers\Demo@catchAll');
```
I can rest good again.  But you folks need to have ver 3 ready by or before Christmas.

**Comment by LuckyCyborg** [comment]
@jimgwhit So, your dogs wasn't for testing, they are for real? Nice!

Well, I can't talk about Dave's and his fellows, but I reassure you that the code pushed there is well tested, discussed and verified, firstly in our Office. And we know very precisely where we want to arrive.

Yet, we have no intention to "hijack" SVMC and transform it in a Dedicated Server Only software. What we want is just to enhance it a little, to be able to sport, as *Base Framework*, our in-house applications, who are not so simple. :smirk:

**Comment by jimgwhit** [comment]
@LuckyCyborg found one thing not working, In some of my headers I use a session to
return user to page they left off on like
```
<?php
     use Smvc\Helpers\Session;
    $spage = Session::get('dogpage');
    $spsch = Session::get('dogsearch');
    echo "<a href=" . DIR . "dog/index?p=" . $spage . "&psch=" . $spsch . ">Back to List</a>";
 ?>
```
This returns a user from view page back to list page, now the link is missing entirely.
Notice I used the new namespacing.

**Comment by jimgwhit** [comment]
@LuckyCyborg if you had already read one I just deleted about session, I got it fixed, it wasn't namespaced right at another place.

**Comment by LuckyCyborg** [comment]
@jimgwhit In theory, we aren't touched yet **Smvc\Helpers\Session**, then the things are supposed to works as usual. A note, if you are our latest push-request:

Now, the old **\Smvc\Helpers\Request** and **\Smvc\Helpers\Url** are in another namespace:

**\Smvc\Net\Request**
**\Smvc\Net\Url**

**Comment by jimgwhit** [comment]
@LuckyCyborg the only other thing is I don't use assets.php and hooks, so to make my headers work right I have to in Url.php:
```
public static function templatePath($custom = false)
    {
        return DIR.'templates/';
    }
```
instead of
```
public static function templatePath_back($custom = TEMPLATE)
    {
        return DIR.'templates/'.$custom.'/';

    }
```
and in a header I
```
<link href="<?php echo Smvc\Net\Url::templatePath(); ?>default/css/style.css" rel="stylesheet">
```
Does that look right to you, I just don't like to use the hooks and assets.php file.

**Comment by daveismyname** [comment]
> @daveismyname what are we going to do with you.

just love me :) that doesn't need to be in there it's specific I have an awful lot of testing to... not to mention docs!

@LuckyCyborg just trying out the standalone server is this correct:

1) download the files
2) navigate to server.php in terminal
3) run php -S localhost:8080 server.php
4) go to localhost:8080 in a browser

if that's it then I've found a problem doing the above:

````
Warning: require_once(/smvc/public/index.php): failed to open stream: No such file or directory in /smvc/framework/server.php on line 22
````

**Comment by jimgwhit** [comment]
@daveismyname is vendor folder there? I had to do a composer install.

**Comment by LuckyCyborg** [comment]
@jimgwhit Looks OK you syntax. And there is no **/vendor** anymore. Composer alone shall manage it.

@daveismyname the standalone server is supposed to be run from **/public** as:

```
 php -S localhost:8080 ../server.php
```

But, if you wish to be run in this style, from ROOT, I will modify it, no problems.

**Comment by daveismyname** [comment]
I've gone into public and tried it from there same error when going into the browser

**Comment by LuckyCyborg** [comment]
I will make a pull-request right now. :smirk:

**Comment by LuckyCyborg** [comment]
Pull-request done.

**Comment by daveismyname** [comment]
yep fixed, now gettings:

Notice: Constant DS already defined in /smvc/framework/public/index.php on line 5

**Comment by LuckyCyborg** [comment]
We fix this too. pull-request

**Comment by daveismyname** [comment]
putting a 

if (!defined('DS')) {
    define('DS', DIRECTORY_SEPARATOR);
}

sorted it for me in server and index.

**Comment by LuckyCyborg** [comment]
Simpler is:

```
defined('DS') || define('DS', DIRECTORY_SEPARATOR);
```

You have it as pull request

**Comment by daveismyname** [comment]
perfect.

**Comment by LuckyCyborg** [comment]
Talking about defines, to be honest, I don't like too much PUBLICDIR, APP, SYSTEM and ROOT. I can give you a rationale, but firstly, they just don't looks good. How about:

WEBPATH or WEBROOT
APPPATH
SYSPATH
BASEPATH

Those defines are usual in MVC applications

**Comment by daveismyname** [comment]
I don't mind if the constants are changed to the above WEBPATH to be consistent.

What's the purpose of the .htaccess in the root? how would this be place in a typical shared server now?

**Comment by jimgwhit** [comment]
@daveismyname  that's where you said to put it for a local development or a shared host where everything has to go under htdocs. It's in one of your videos.

**Comment by jimgwhit** [comment]
@daveismyname sorry misunderstood question you're talking about the other htaccess. Again Sorry.

**Comment by LuckyCyborg** [comment]
@daveismyname The .htaccess from the ROOT is a development thing, to permit to test/develop in a shared hosting or virtual host, with installation direct in webroot.

So, practically, this file transparently redirect the requests to /public path. See the screenshots with www.smvc3.dev on #222 , my last posts.

**Comment by jimgwhit** [comment]
@LuckyCyborg OK to delete if not using, right?

**Comment by LuckyCyborg** [comment]
@jimgwhit Of course

**Comment by woodsy1** [comment]
@LuckyCyborg I would be interested in your process for deployments from local envr to prod servers.
Here is the tutorial I wrote for SMVC forums of how I use Git ftp for deployment.
http://simplemvcframework.com/forum/viewtopic.php?f=11&t=3279

What do you guys use?
