### ISSUE TITLE
About the Events Management in SMVC 3.0

### ISSUE THREAD

**Issue by LuckyCyborg** [simple-mvc-framework/framework#264]
Hello to all!

Sure, everyone known that the **Events** are nice things, and very useful on writing consistent contexts on complex applications. The idea is simple: 

You have, for example an **AbstractEvent**, from where you make a derivative, your punctual required one, incorporating some useful data. Then, you have an **EventManager** who dispatch your **Event** to a series of **Listeners**, who execute different jobs, triggered by this unique **Event**.

The **Listeners** can be **Closures** or **Class Methods**, second one being **static** ones or not. While the static Class Methods can be called in a way almost similar with the Closures, see how our new Routing works, for example; to call the normal Methods another style is applied:

The EventManager keep a list of the instances of Classes who have Methods registered as Listeners, to one or more of its Events. When an Event is deployed, the EventManager recursive call all this (long) instances list with specified methods. Eventual, when there is no available Class instance, the EventManager will instantiate an appropriate one.

That's make us to go to another concept: **ClassRegistry**, practically a Manager who keep the track of the Class instances, all simultaneous loaded in memory. And that's bad, because keeping the track to all Classes instances and instantiating  those in demand will go to a spectacular increase of memory consumption and considerable Framework's slowdown.

So, in my opinion, the auto-instantiating of **Listerner Classes** on Event Deploying is a **BIG NO-NO**, if we want to keep the things simple and our SMVC to not eat memory like a Pig.

Then what? What remain?

Our suggestion is to use as **Event Listeners** the following objects:

- the Closures
- the static Class Methods
- a select list of Class instances and their appropriate Methods, who are already instantiated from another reasons.

This way, we can have a useful Events Management, while keeping a low profile as source code complexity and memory consumption; affecting the Framework speed overall.

Thoughts?

**Comment by tomvlk** [comment]
This can be used for implementing observable pattern. Would be a good solution for complicated controller code and copy-paste code when something happend. 
For example when a client email is changed you can hook an event to send a mail with informing that the email has been changed, right?

**Comment by LuckyCyborg** [comment]
@tomvlk Sure, that thing can be done. In fact, just that was an example which I given in the **Restructure** thread. 

And, yes; I for one, I consider right on the *Observer* pattern, to be this one appropriate for us. Both as simplicity of implementation and ability to extend the Events information and Management structure.
