### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by woodsy1** [simple-mvc-framework/framework#270]
@LuckyCyborg I would be interested in your process for deployments from local envr to prod servers.
Here is the tutorial I wrote for SMVC forums of how I use Git ftp for deployment.
http://simplemvcframework.com/forum/viewtopic.php?f=11&t=3279

What do you guys use?

**Comment by LuckyCyborg** [comment]
@woodsy1 Well, locally we use **SVN repositories**, then we generate **stable releases**, who are uploaded/deployed by the lead webmaster via RSync or FTP, as secondary choice.

Usually, the more complex applications have everyone an **Update Engine**, capable to manage those updates.

In advanced stages of development, we use live (development) website, accessed via RSync. 

Rationale is about having possibility to do small changes at 2AM, if at that hour come The Idea, or to have the possibility to present to Final User (Owner), the website in its final stages of development for "last minute" changes.

For example, I use for working on SVMC3, as live devsite: http://smvc3.giulianaeassociati.com

I read you article, very interesting; to see how it can apply in our team.

**Comment by woodsy1** [comment]
Git is a really nice version control process much much better then old svn
haha! You are living in the stone ages! :p

**Comment by LuckyCyborg** [comment]
@woodsy1 In other hand, SVN exists from, well... stone ages. Then a Company can have a long time to train and prepare its infrastructure.

Git is cool, but you'll be amazed to see how much is used the SVN in Corporate Environment. In other hand it is a Mission Impossible to explain to a Manager the advantages of GIT, to replace the old good SVN repositories, who deserved well the Company since ... Stone Age. Trust me! :smirk:

**Comment by woodsy1** [comment]
We just started using git for all new projects at my company and slow
phased out the svn server. Haven't looked back :)

**Comment by bastian-w** [comment]
i use capistrano. check it out :)

**Comment by LuckyCyborg** [comment]
Nice to known the alternatives, but... well, I not in a position to be able to propose the restructure of Company's Development Repositories, thought. :+1:

**Comment by bastian-w** [comment]
capistrano works with SVN, but only in version 2.

**Comment by geomorillo** [comment]
Really interesting reading... lol

**Comment by woodsy1** [comment]
@bastian-w I think that only works if you have access to the server (ie not in shared low budget instances?)
