### ISSUE TITLE
Force SSL .htaccess

### ISSUE THREAD

**Issue by bastian-w** [simple-mvc-framework/framework#271]
Hey, 
i am a total .htaccess Rewrite Rule noob... can anyone provide me a valid .htaccess version for a forcing https?

    RewriteEngine On
    RewriteBase /
    # Force to exclude the trailing slash
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.*)/$
    RewriteRule ^(.+)/$ $1 [R=307,L]
    
    # Restrict php files direct access
    RewriteCond %{THE_REQUEST} ^.+?\ [^?]+\.php[?\ ]
    RewriteRule \.php$ - [F]
    
    # Allow any files or directories that exist to be displayed directly
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    
    RewriteRule ^(.*)$ index.php?$1 [QSA,L]

**Comment by daveismyname** [comment]
here is the rule I use to force SSL:

````
RewriteCond %{HTTPS} !on
 RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
````

**Comment by bastian-w** [comment]
thx i will try this

**Comment by daveismyname** [comment]
Did that work for you?

**Comment by bastian-w** [comment]
yes, sorry for the late reply! Works Perfect!

Von meinem iPhone gesendet

**Comment by daveismyname** [comment]
No problem glad it did.
