### ISSUE TITLE
ive tried to setup this version locally to test some things,  not working

### ISSUE THREAD

**Issue by geomorillo** [simple-mvc-framework/framework#293]
Its complaining about
 Please install via composer.json

Install Composer instructions: https://getcomposer.org/doc/00-intro.md#globally

Once composer is installed navigate to the working directory in your terminal/command prompt and enter 'composer install'

Where are the instructions?

**Comment by daveismyname** [comment]
there aren't any I've been waiting for the recent developments to complete so I can go through the changes and make sure everything is working and write up the new docs.

I'll download it now and see what the steps are.

**Comment by daveismyname** [comment]
OK I've downloaded it put it into my local server ran composer install within terminal to create the vendor and it's repos.

Then configured public/.htaccess and app/Config/constants.php

**Comment by geomorillo** [comment]
Ah i see i forgot there is no vendor folder in my setup....

**Comment by daveismyname** [comment]
no it's not, due to using third party dependencies. Instead it will be created on install.

**Comment by geomorillo** [comment]
How is this going to work on shared hostings? Sorry i have never used composer so i am a little confused here. Normally what i used to do was copy the files by ftp and that was it. Also on localhost.

**Comment by daveismyname** [comment]
you would install locally or at least run composer install locally then upload the files via ftp so on the shared hosting it would be as it is now from the vendor perspective

**Comment by geomorillo** [comment]
Thanks i will look into it i get it now.

**Comment by LuckyCyborg** [comment]
My Spanish friend, say quickly how are those strings in Spanish:

```
'Elapsed Time: <b>{0}</b> sec | Memory Usage: <b>{1}</b> | SQL: <b>{2}</b> {3} | UMAX: <b>{4}</b>' => '',
'queries' => '',
  'query' => '',
```

**Comment by geomorillo** [comment]
'Elapsed Time: <b>{0}</b> sec | Memory Usage: <b>{1}</b> | SQL: <b>{2}</b> {3} | UMAX: <b>{4}</b>' => 'Tiempo transcurrido: <b>{0}</b> seg | Uso de memoria: <b>{1}</b> | SQL: <b>{2}</b> {3} | UMAX: <b>{4}</b>',
'queries' => 'consultas',
  'query' => 'consulta',

**Comment by LuckyCyborg** [comment]
@geomorillo Thanks!
