### ISSUE TITLE
3.0. Propose using semver

### ISSUE THREAD

**Issue by tomvlk** [simple-mvc-framework/framework#303]
I think it would be a good idea to follow semver from version 3. 
http://semver.org

So the first 3 release should be 3.0.0. And the next bug fix should be 3.0.1. Next feature update should be 3.1.0 and next breaking change update should be 4.0.0. 
When following this we should be able to make it clear when we only update because of a bug fix. Or also feature update. 

Only downpoint is that this can create 3.18.0 fast when releasing on a regular and short time.

**Comment by daveismyname** [comment]
Agreed, since 3.0 will be going through a good level of testing most bugs should be caught but bugs are to be expected.

I try to keep the documentation in line with the changes too.

**Comment by LuckyCyborg** [comment]
We have an long term supported application on **11.537.432**, right now, if that matter...

And, yes, I subscribe to that Idea!
