### ISSUE TITLE
About deploying the Nova Framework as a StarterKit - aka our idea for a NovaIgniter

### ISSUE THREAD

**Issue by LuckyCyborg** [simple-mvc-framework/framework#324]
The **StarterKit** concept is about to have an Application skeleton, ready to be specialized, who offer the usual multi-tenant infrastructure for **Frontend**, **Backend** and **API**, built on top of the Framework.

What is good for?

Well, everyone love to write his own **Users Management**, with shiny **User Groups** and **Authorization**, also his **Backend** too.

But, writing again and again the same structures is not fun anymore, if you have several Applications in the work. Eventually, you can even propagate some Management mistakes.

Having a minimal but well defined structure for your **Backend** permit you to concentrate on real things to do: you custom Application infrastructure.

In other hand, having that  **multi-tenant infrastructure** ready-to-go can be an excellent example about how to implement the things and, not lastly, a real help for developers, who work on "real thing", not hopping that some (questionable) **Tests** will save their bottom.

In the Nova Framework case, this **multi-tenant infrastructure** can be easily implemented as Modules, who are self-contained by excellence, and, eventually permitting nuking overall thing simply, by deleting the Modules.

Our proposal is to introducing and shipping with **Nova Framework** a series of **Modules** who create that **multi-tenant infrastructure**, in a simple but efficient and recommended way, without making it obligatory.

Practically, it is about shipping several Modules, called: **API, Cron, MediaManager, Menu, Page, System, User**, who form together a ready-to-go **Mini-CMS** and a new Template, called **Backend**, with obviously use, written on top of the Premium (and Free) Theme **AdminLTE**.

We arrive for **Backend** / Administration area at something similar to:

<img width="695" alt="adminlte2" src="https://cloud.githubusercontent.com/assets/13488485/12010340/9c67b5a6-aca2-11e5-9389-84de1087f865.png">

Finally, this concept we call it **NovaIgniter**, in honor to a Sci-Fi device (used as super-bomb) able to make an Star to go SuperNova.  Device which we suspect to be inspiration of the name of **CodeIgniter**, too. But us, we will use right on the real thing... :smirk: 

In our case, we believe that **this concept** will produce a spectacular explosion of the number of applications written on Nova Framework.

**Comment by sisnox** [comment]
Agree 100%

**Comment by daveismyname** [comment]
I love this idea, I'm really interested in the modules, I use the AdminLte theme for my CRM / CMS projects it's a great and very flexible theme!

**Comment by LuckyCyborg** [comment]
@daveismyname Thanks! 

Also us we make a huge accent on Modules, and we hope to improve them further... :smirk: 

To be honest, this will be the way to create our applications on top of Nova Frameworks: Modules on top of it, with additional Composer Packages, too.

Also, having some real infrastructure to deal with development, will considerable simplify the consolidation of the code... :+1:

**Comment by daveismyname** [comment]
totally agree for my projects I have a base system everything else comes from a module.

**Comment by LuckyCyborg** [comment]
@daveismyname Yeah! We have a common pathway.

That's why we believe that having a bunch of Modules, who implement the Base Structure, ready to be extended, yet in the public eye, then anyone able to look for bugs, is a good thing.

If you agree, we will start to implement the **StarterKit** part, aka those Modules, in January.

**Comment by LuckyCyborg** [comment]
@daveismyname Also, look there:

http://smvc3.giulianaeassociati.com/demos/models

Our **BaseModel** playing the things. And the Members Model is:

```php
class Members extends BaseModel
{
    protected $table = 'members';


    public function __construct()
    {
        parent::__construct();
    }
}
```

 Not only CodeIgniter guys have a shiny **BaseModel** to play with. :+1: 

Now, also Nova Framework sports one... :smirk:

**Comment by daveismyname** [comment]
wow I'm overwhelmed that is truly awesome!!! Thank you, I can't wait to look through everything in detail in late January.

Oh and Yes I do agree lets have the starterkit.

**Comment by LuckyCyborg** [comment]
@daveismyname BTW, if you are in a trip, still use we will continue our tasks, after 4th January.

How about to give us (to me, of course) write access on the **3.0-beta** branch ?

That's why, we can accept our push-requests into your tree. Maybe also thing, to have write access on beta branch, can be useful for having Tom too... :smirk:

**Comment by LuckyCyborg** [comment]
@daveismyname Talking about StarterKit, we see it just a series of Modules shipped by default by Nova Framework, who eventually the end-user can simply cancel them and all is gone, if he want a bare tree...

**Comment by tomvlk** [comment]
Would be useful. I have limited time upcoming few days. But be able to do something later on. 
At least staying into making pull requests is the best way to discuss and see changes as a summary.

**Comment by LuckyCyborg** [comment]
@daveismyname and @tomvlk After all, our friend Jim already arrived to conclusion that your Framework "now looks like it's been spun around in a blender"... :smirk: 

We promise to not destroy it further! :smile:

**Comment by daveismyname** [comment]
I've added you and @tomvlk with write access now, I'll be checking my emails while away but I'll be 6 hours in front of my normal timezone so I would guess when most things is being done I'll won't be available to see.

Both of you have done an amazing job and trust your judgements for anything really radical please contact me first.

**Comment by LuckyCyborg** [comment]
@daveismyname Okay, Dave!

And thanks for our kind words! But, we promised to improve the **SMVC**, right? :smirk: 

And, I wish you to have a nice trip!

**Comment by daveismyname** [comment]
thank you :smirk:

**Comment by LuckyCyborg** [comment]
@daveismyname Tomorrow will be my deadline to conclude the Final Phase, and to give us and yours a functional Framework, in the new style. Then my colleagues will start to build thing on top of now Nova Framework, and you will enter in **beta2** or **RC**, or what you want to be called.

Still, I believe that I was successful on my designed tasks. :smirk:

**Comment by daveismyname** [comment]
OK great I'll be traveling tomorrow so won't be around much. When ready I suggest setting a new release I think RC is more suitable.

**Comment by LuckyCyborg** [comment]
@daveismyname Okay, Dave!

**Comment by LuckyCyborg** [comment]
@daveismyname Talking about (maybe) some "major changes" in close Future, eventually you'll see the **BaseModel** will be able also to **Validate** alone its input Data, because there are some talks about this thing, right now... :smirk:

**Comment by daveismyname** [comment]
OK that sounds good!

**Comment by webineh** [comment]
very thanks
