### ISSUE TITLE
MySQL Demo broken

### ISSUE THREAD

**Issue by daveismyname** [simple-mvc-framework/framework#340]
@LuckyCyborg http://smvc3.giulianaeassociati.com/demos/database/engine/basic/mysql

the mysql pages result in an error been generated.

**Comment by LuckyCyborg** [comment]
@daveismyname I will look right now, but those are Tom's Demos!

I hope that he have nothing against to touch its code... :smirk:

**Comment by LuckyCyborg** [comment]
@daveismyname Nope, it is not broken, I missed to import its **cars** table into database. Sorry!

I will fix it now.

**Comment by daveismyname** [comment]
ah great thanks.

**Comment by LuckyCyborg** [comment]
@daveismyname Done, now the Tom's Demos works.

**Comment by LuckyCyborg** [comment]
@daveismyname If you want to play with **3.0-beta** be warned that I moved default shipping of **config.php** and **constants.php**, from **app/Config** into example files, which should be renamed and configured, just like in the ol'good days with **Config.example.php**.
