### ISSUE TITLE
About moving the Nova's Database Engines to Doctrine DBAL

### ISSUE THREAD

**Issue by LuckyCyborg** [simple-mvc-framework/framework#352]
The proposal is about to use **Doctrine DBAL** instead of "pure" **PDO** for our own **Database DBAL** (aka **Engines**). The Doctrine DBAL is built on **TOP** of PDO, and offer everything which PDO offer, with a big PLUS.

Advantages? 

- Considerable simplify our own **Database DBAL**, who simply pass the hard work to **Doctrine**'s one.
- Powerful **QueryBuilder** being native into **Database DBAL**; and that will be a huge advantage to **BaseModel** who literally can hugely improve its offered **API**.
- Ability to further integrate the **Doctrine Migrations** into Future can be considered as a huge advantage.
- **Annotations**, shiny and powerful consolidating our Entities. Our **Database Services** do not use this things yet, but they can do in Future.
- Future ability to simply integrate the powerful **Doctrine ORM** in Nova Framework, while working with **ORM** Models or **DBAL** based ones.

See those links for details:

http://www.doctrine-project.org/projects/dbal.html
http://www.doctrine-project.org/projects/migrations.html

@daveismyname  and @tomvlk I wait your opinions...

**Comment by tomvlk** [comment]
I personally think that this is a step that's too big for now. I like the Doctrine. But requires even more knowledge and isn't really easy to start learning. 
Also I really like that it's just an PDO encapsulated engine. How it is now and how it was before. Also for large and complex queries the current would be better and easy to simply do the stuff. 

Maybe it's a better option to let the user/end developer decide one of the two by just implementing a cross package for composer. 
When doing that we could let the user decide if they want the more advanced and more features doctrine or the simple and fast to learn and use build in engines. 

I would really like to choose between the two because I have some small projects that really are way to small for complete doctrine structure. And some big projects I really like to do it but lack the structure right now.

**Comment by LuckyCyborg** [comment]
@tomvlk I'm afraid you confuse **Doctrine DBAL**, who is something like a PDO on steroid, with **Doctrine ORM**, which is, well ... most powerful **ORM** known in literate World.

**Comment by tomvlk** [comment]
@LuckyCyborg O wait I'm confused indeed. Instead of encapsulating the PDO (like how it is right now) you propose to encapsulate the Doctrine DBAL?

I still think we should really look into how much work is needed and if the learning curve isn't too hard. Also if this isn't a bit too much.

**Comment by tomvlk** [comment]
I'm looking into the API of the DBAL. But it's almost exactly the same as PDO. It has some additional and generic methods. Just like we have right now, isn't it?
But that would mean that we could transform our engines into the doctrine engines with almost no big changes right?

**Comment by LuckyCyborg** [comment]
@tomvlk The **Doctrine DBAL** is just an Hugely Enhanced **PDO**, with (part of) API much similar with our actual Database Engines style, having as plus a powerful QueryBuilder and other shiny things.

Then, instead of relying directly on **PDO** to do the things, we can just wrap-up the **Doctrine DBAL** to do the things. From the end-user perspective there will be almost no difference, but there will be huge advantages.

Like I said, I don't propose to ship **Doctrine ORM** by default into Nova Framework.

**Comment by LuckyCyborg** [comment]
@tomvlk 

>But that would mean that we could transform our engines into the doctrine engines with almost no big changes right?

Well, you got right on the point. :smirk:

**Comment by tomvlk** [comment]
Ye indeed. The orm is the nasty one :laughing: haha. 
how much work would this be approximately?

**Comment by LuckyCyborg** [comment]
For us, several days; next week will be ready. Maybe, you can be afraid that we will try to introduce our POV alone, then how about to go with us in this journey?

**Comment by tomvlk** [comment]
And how exactly about the services/small orm we have (the services)? Because that's still very small and easy to use when implementing entities. 
I think it would be great to make good plans before beginning. I'm also really interested in the plans and I can also do a lot work from next Tuesday. (And a bit in between now and Tuesday).

**Comment by geomorillo** [comment]
Ah i really like this query builder.

**Comment by LuckyCyborg** [comment]
@tomvlk In theory, the **Services** will happily live with using the **Doctrine DBAL** based Engine, instead of directly **PDO** based ones.  

Further, the **Services** can hugely profit from the **Annotations** support, useful thing when you talk about **Entities**.

**Comment by LuckyCyborg** [comment]
@tomvlk 

> Ah i really like this query builder.

And image that shiny **QueryBuilder** exposed directly into **BaseModel**... :smirk:

**Comment by tomvlk** [comment]
I was thinking about the annotations earlier and yes that would be great. Even for table generating with column name type and stuff. 

Could you think more for the design idea, and maybe express it. I really want to work on this too.

**Comment by LuckyCyborg** [comment]
@tomvlk Well, the integration can be spectacular simple:

We make a **\Nova\DBAL\Manager** which use a method called **getLink** to map our Database Configurations to Doctrine's DriverManager ones and return the DBAL Driver.

That's all!

Further, there is no need for **Database Engines** and the **Database Services** and **BaseModel** shall be ported in using the new API.

In other hand, Doctrine DBAL comes with an well tested Caching, which can be reuse for our interest, and even with another... **Events Manager**. Yeah, you are read right! :smirk:

**Comment by tomvlk** [comment]
Please no \Nova\DBAL. Just leave it as Database then haha. 

Ok. Let's wait on other opinions too. I can even implement this very easily :laughing:

**Comment by LuckyCyborg** [comment]
@tomvlk On **\Nova\DBAL** we can keep only our glorified DBAL **Manager**, then the **Services** we will keep into **\Nova\Database**, as usual ...

Eventually we can make, as backward compatibility, the **\Nova\Database\Manager** to ask the **\Nova\DBAL\Manager** for the current Database Link.

**Comment by tomvlk** [comment]
Or maybe make a Nova Global Manager that will do the work for multiple namespaces. Like DBAL, services and events manager

**Comment by LuckyCyborg** [comment]
@tomvlk 

> Ok. Let's wait on other opinions too.

I hope you do **NOT** expect our friend **Jim** executing his own style of **Happy Dance** there, while knowing about this idea, right?

**Comment by tomvlk** [comment]
But anyway I would like to do some work on this. 
But before it would be better to wait until we have more opinions and from Dave too.

**Comment by LuckyCyborg** [comment]
@tomvlk 

> Or maybe make a Nova Global Manager that will do the work for multiple namespaces. Like DBAL, services and events manager 

You think about a **Managers Registry** ? Well, not bad one, but while we have a handful of Managers, we should keep that for the times when.. well, the Nova will be more complicated.

**Comment by tomvlk** [comment]
Jim's opinion is predictable....

Like facade a like.

**Comment by LuckyCyborg** [comment]
@tomvlk 

> Jim's opinion is predictable....

Yep, as in:

#### The end is near! Repent, ye sinners!

**Comment by LuckyCyborg** [comment]
@tomvlk BTW, we promised to Dave to not introduce major structural changes without asking him first or to "blend" the Framwork further. 

That I understand as : 

#### Do not introduce half of Symfony, the Doctrine ORM or Laravel's Eloquent by DEFAULT, without asking me first!

Well, the Doctrine DBAL is more like an ingredient in our kitchen...

**Comment by tomvlk** [comment]
Implementing the doctrine DBAL has almost zero changes to the end developer. It has a bit different API. But our engine API already was new for the biggest part. 

The big change is in composer file and the manager implementation. 

Still it's better to discuss, but it's not that much work as I can predict right now.

**Comment by mickacz** [comment]
Why Nova can not have only a basic database support as it is now?
When I will want to use Eloquent or Doctrine, just install from Composer.

Is it possible add additional engines in the options?

$engine = \Nova\Database\Manager::getEngine();
$engine = \Nova\Database\Manager::getEngine('sqlite');
$engine = \Nova\Database\Manager::getEngine('eloquent');
$engine = \Nova\Database\Manager::getEngine('doctrine');
$engine = \Nova\Database\Manager::getEngine('othersupaorm');

**Comment by tomvlk** [comment]
Ye @mickacz has a point there. The current engines will also do the same thing. And is pretty low code if you compare with Doctrine DBAL. 


Also, we could make it so that you could use doctrine optional with our manager. So not on by default. But an option encapsulation and setting injection for the doctrine DBAL. Make it optional this way.

**Comment by LuckyCyborg** [comment]
@mickacz 

> Why Nova can not have only a basic database support as it is now?

Well, again, you **confuse** Doctrine DBAL with Doctrine ORM or another ORMs like Laravel's Eloquent. There is no such thing as an ORM which I propose to introduce to Nova Framework.

What us we call a **Database Engine** is in fact a specialized **Wrapper** for one of types of Databases supported by **PDO**,  all of Engines offering the same API. Nothing more and no ORM there...

In other hand, **Doctrine ORM** can be seen the same **Wrapper**, improving the **PDO**, but it is not equal with our Engines.

**Doctrine ORM** offer, for example, support for a **MySQLi** driver, or even a **SQL Anywhere** driver.

If you are just a Nova end-user, while using the Database APIs you should expect minimal and trivial changes in your code, to port it to new one. Others, who need a more advanced usage, there will be the required support for their needs.

@tomvlk 

> Ye @mickacz has a point there. 

Nope! Eventually @mickacz make a confusion there, having no point there from a end-user POV.

> The current engines will also do the same thing. 

With all respect: **Nope!** Please give me a similar **QueryBuilder** to use in our **BaseModel**, support for i.e. **SQL Anywhere** and **SQL Server** and other shiny things included, then i will be glad to miss this Idea!

**Comment by tomvlk** [comment]
So it's no option. We must convert to doctrine? 
But anyway. We will make another external dependency with updates and stuff. We should also consider the fact that we need to update it when security updates are available. And I don't mean the GitHub repo. But more inform our developers to keep updated etc.

**Comment by LuckyCyborg** [comment]
@tomvlk It is not about to became Doctrine believers, but to reuse already existent and well managed code and spend our (available) time for better objectives instead to reinvent the wheel.

In other hand, talking about the **Composer packages**, it is supposed that the end-user, as in Developers or Administrator, should manage his Composer packages updates.

And, after all, it supposed that the number of Composer Packages to be managed/updated in a Production ready Application to easily arrive at hundreds...

**Comment by LuckyCyborg** [comment]
@tomvlk BTW, Tom, you know that our **Routing** use for serving files, for example; a helper called **Inflector**, who is just a basic wrapper for **Doctrine Inflector** ?

**Comment by tomvlk** [comment]
Ok. After some more checking on the API of doctrine DBAL. 

I think we can use the DBAL from doctrine but still with our current API of engines above it. Just for the easy and fast inserting with just an array and instead of doing that manually. We could look into a form to combine the Engine (with specific driver) and make a single engine that will use the doctrine QueryBuilder (which is very good) to insert select update and delete. 
With this way you create an easy API. With zero SQL queries or even SQL word for selecting, inserting, updating and deleting records.

**Comment by LuckyCyborg** [comment]
@tomvlk Well, there is a delicate problem in using a custom Class, aka our specialized Engine, together with Doctrine DBAL.

In fact, to get an instance of worker **Doctrine\DBAL\Connection** from DBAL you should use the static method **Doctrine\DBAL\DriverManager::getConnection** .

Sure, there a parameter option, to ask for returning a custom Wrapper Class, called, well... **wrapperClass**, but this custom Wrapper should be a subclass of **Doctrine\DBAL\Connection** .

Then, we can make a **\Nova\DBAL\Connection** as subclass of **Doctrine\DBAL\Connection**, and ask for it from DBAL's DriverManager.

In other hand, the **QueryBuilder** come as option from **\Nova\DBAL\Connection**, asking for it with 

```php
$queryBuilder = $conn->createQueryBuilder();
```

Then, all we need is that the Models flow to propagate the Database Link/Connection, then the BaseModel can obtain a QueryBuilder instance from the Database instance, and do shiny things.

Finally, while we can create and configure our shiny custom **\Nova\DBAL\Connection**, the question is: what this Wrapper will do, as PLUS from the Doctrine DBAL one?

**Comment by tomvlk** [comment]
@LuckyCyborg I think we don't need more methods or any other new stuff into our custom connection.

But first, why do we need that, we can fully manage our \Doctrine\DBAL\Connection in our Manager.
And let the manager return an instance of our Engine, with the injected connection and querybuilder. I think that we mostly only need our querybuilder.

Extending the Doctrine classes would be a bit too much I think. And it's unneeded, we only need to inject config to the connection, we can handle that in our manager.

**Comment by LuckyCyborg** [comment]
@tomvlk Well, in principle, what we call **Engine**, they call **Connection**. As to note that their **Connection** is **not** a subclass of **PDO**.

In other hand, the **Doctrine\DBAL\DriverManager** is not too complicated to be replicated in our own Manager, yet we should go to using **Doctrine\DBAL\Connection** or one of its sub-classes, to properly use of the DBAL.

Eventually, even we call this sub-class as **Engine**, it should extend **Doctrine\DBAL\Connection**.

**Comment by tomvlk** [comment]
We could have two options. Plain Doctrine connection or our Engine. 
Our manager will interact with the manager of doctrine that holds instances of doctrine connections. We hold engine instances. 

This would be possible.

**Comment by LuckyCyborg** [comment]
@tomvlk Well, it is possible, but can confuse someone, who will start use both of them, arriving to having to connections to **Database Server**.

In other hand, the actually existent Engines are super-seeded by Doctrine **DBAL** ones...

**Comment by tomvlk** [comment]
Ye. We won't have two connections. The engine would use the connection from doctrine manager (the same one when the user just wants a doctrine connection)

**Comment by LuckyCyborg** [comment]
@tomvlk Then, in that case, please explain what you understand by **Plain Doctrine connection or our Engine**  ?!

**Comment by tomvlk** [comment]
Just the doctrine DBAL connection instance or the engine in our nova database namespace.

**Comment by LuckyCyborg** [comment]
@tomvlk And what will do, as PLUS, our **\Nova\Database\Engine** instance compared i.e. with **\Nova\DBAL\Connection** instance ?

**Comment by tomvlk** [comment]
The current API (we have on engine) will be implemented above the Doctrine DBAL Connection. 
The way of inserting isn't available in the doctrine for example. Right?

**Comment by LuckyCyborg** [comment]
@tomvlk Well, as methods, the **batch** ones are missed (I said that the Database DBAL's do not go **multi-pass**), and my favorite: the **Query Counter**, then there is need to extend the **Doctrine\DBAL\Connection**, to add the **queryCounter** thingy, at minimum.

**Comment by tomvlk** [comment]
But there are no select update insert delete methods we currently have (and the batches). I think those would be very useful. Especially when using the QueryBuilder in the back of those selects. Because on that way it would be one generic engine for all Doctrine Drivers.

**Comment by LuckyCyborg** [comment]
@tomvlk **update, insert, delete** live fine and well under Doctrine DBAL, while the batch one are avoided by Design. Is not sane to play batches with your data, as I seen as general opinion.

**Comment by tomvlk** [comment]
Okay. I see. Then only maybe select and batches.

**Comment by LuckyCyborg** [comment]
@tomvlk This is the style in case of Doctrine DBAL, for select:

```php
$stmt = $conn->executeQuery('SELECT * FROM articles WHERE id IN (?)',
    array(array(1, 2, 3, 4, 5, 6)),
    array(\Doctrine\DBAL\Connection::PARAM_INT_ARRAY)
);
```

Thing equivalent with our **BaseModel::findMany**, and which I can wrap-up in 3 minutes. :smirk: 

In other hand, instead of batches are used Transactions with **transactional()** , and please stop believing that batches are some spectacular things! Almost all others believe to be some unlucky inventions.

**Comment by tomvlk** [comment]
Batch is peanuts :laughing: 
But we need to override all methods, implement counter++ and hit the parent method (overrided method).

**Comment by LuckyCyborg** [comment]
@tomvlk Nope. Some of them. For example, a best way to implement/override the Connection::executeUpdate and few ones, to implement the Query Counting...  :smirk:

**Comment by tomvlk** [comment]
That's the executing method aha ok.

**Comment by LuckyCyborg** [comment]
@tomvlk Yep, one of them. The second candidate to override is **Connection::executeQuery**, like it looks... :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg great. That would be a bit less override there 🤓

**Comment by volter9** [comment]
> You think about a Managers Registry

Manager managing managers :)

![yo dawg](http://i.imgur.com/58kv7tT.jpg)

I need to check out what a huge amount of work you've done. On the topic, however, I have few thoughts:

Is Nova really needs core DBAL support? I mean, well yeah, it would simplify the code, I think (presumed based on @LuckyCyborg comments), but for end-user it's: 

1. Learn framework 
2. Learn ~~another framework~~ external library

Is it worth it? Also I have few questions:

* Is Nova is completely new framework? Or it's going to be Nova 3.0? :)
* Is it still going to be simple?

**Comment by LuckyCyborg** [comment]
@volter9 

> Is Nova really needs core DBAL support?

On our POV, the response is: **Yes**.

But, to remember that we aren't the classic SMVC Users, instead being a team of programmers, which its Manager choose to use a Micro-Framework to build a hugely complex Portal, from speed reasons. Then, we have to push this Micro-Framework of choice (SMVC) until it is able to support our application built in its top. 

In other hand, we strive to keep the things simple and to be backward compatible. Well, almost...

For example, **Doctrine DBAL** permit us to use shiny things like **Cached Queries**, while still offering an API almost identical with PDO. Sure, there is a Learning Path, but **Doctrine DBAL** is well documented, there is a huge amount of articles on subject and other documentation resources.

Still, already introduced our OWN **DBAL**, which is slightly different from the old one, then end-user will have to learn something new anyway.

> Is it worth it?

**Doctrine DBAL** is one of most powerful, yet versatile and simple DBALs known. Surely, is it worth it.

> Is Nova is completely new framework? Or it's going to be Nova 3.0? :)

We like to call **Nova Framework** as being **version 3.0**, yet the only common things having with the **SVMC 2.2** are some of the **Helpers**. Everything else was rewritten, then it is practically new.

> Is it still going to be simple?

To be honest, **SVMC 2.2** was something what we call **Micro-Framework**.  Yet, the new **Nova Framework** can be called in a heartbeat as being a **Mini-Framework**. 

It is visible more complex than **SMVC 2.2** but still being enough simple to be called... well, **simple**.

**Comment by jimgwhit** [comment]
@LuckyCyborg and @daveismyname Wouldn't the querybuilder / database from Laravel be better, not the orm part. In dbal you have to use the ? For bindings. Check out update examples in dbal.  
But of course once again I'm wasting my breath here. I have used dbal in past.

**Comment by jimgwhit** [comment]
And a rather smashing idea we'll call the framework LuckyCyborg framework, @daveismyname is letting him guide everything going into the new framework.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> Wouldn't the querybuilder / database from Laravel be better, not the orm part. In dbal you have to use the ? For bindings. Check out update examples in dbal.

Sadly, the only possibility to use Laravel/Illuminate "DBAL" is that:

https://github.com/illuminate/database

The bad news are that **Illuminate Database** come with all shiny things, like a full fledged **ORM**. Sure, it's about **Laravel's ORM**.

In other hand, for somw low level jobs it use, guess what? Right on the **Doctrine DBAL**.

Let's see... While I propose a punctual enhancement, to use that Doctrine DBAL to improve (and simplify) our own **DBAL**, you propose right on a new level of complexity, a complete **ORM** solution. :8ball: 

Please, understand that I do not have nothing against the Laravel's ORM, considering it one of the best, but adopting it by default will be something like forcing our end-users into this Laravel thingie.

> And a rather smashing idea we'll call the framework LuckyCyborg framework, @daveismyname is letting him guide everything going into the new framework.

Well, Jim... Let's see the cold reality:

I written almost everything on Nova Framework, as Routing, Controllers, Views, Models, Events Manager,  Modules Management, even the Configuration, while the Tests, our own DBAL and our Micro-ORM (aka the Services) are written by Tom; only some Helpers still being from **SMVC 2.2**, with some adjustments.

Where were you when these things happened? You played with your cats?

**Comment by tomvlk** [comment]
@jimgwhit :  @LuckyCyborg  and me are both just contributing to a framework, if we really would like our own name as the framework name we would create our own I think. We are creating with knowledge we gained by working with the framework and improve it to be not the tiny tiny framework but to have a bit more, and still be a micro a like (small) framework, that the users will be able to use with almost no intense learning curve.

Doctrine DBAL is really a good one for having even more driver support, and even more backend drivers (not only PDO).
@LuckyCyborg When do we start :laughing:

**Comment by LuckyCyborg** [comment]
@tomvlk Well, as a propose, I will start pushing into **\Nova\DBAL** namespace.

When the things are completed and Doctrine based DBAL is ready to replace the current one, we talk and see what decision we do about the **\Nova\Database** components targeted for replacing... :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg Okay, Please inform me about any work todo, I really want to something on this!

**Comment by LuckyCyborg** [comment]
@tomvlk Be sure, I expect to have detailed discussions into pull-requests... :smirk: 

And I suspect that you will have to make your hands dirty on porting your Services to the native new API, instead of using some compat one, from speed reasons. :sake:

**Comment by tomvlk** [comment]
@LucktCyborg Great, we will still keep the services, thats great! And maybe make it so that you could use Doctrine ORM too, but thats way to complicated for the framework. The micro orm a like will be included ;)

**Comment by LuckyCyborg** [comment]
@tomvlk Worry not! I do not intend to nuke your Services. Eventually, maybe we enhance somewhat them and transform them in our own small but complete ORM. :smirk: 

I intend to leave the real full fledged ORMs, like the Doctrine or Laravel ones, at end-user pleasure.

**Comment by tomvlk** [comment]
Just make a lite version of a ORM :laughing:. Ye, with the query builder we could so even more on the Services I think, maybe implement the query builder so you could do it like the BaseModel we have, but implement that in the Entity class, in combination with our Services.

**Comment by tomvlk** [comment]
And even do like $car->save(); or $car->update();

**Comment by LuckyCyborg** [comment]
@tomvlk 

> And even do like $car->save(); or $car->update();

Be careful what you wish!

If you really want that, we will give you. But there will be some conditions... :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg :open_mouth: Lets first do the DBAL, then Services, tests etc. Lots of work, but this is a really good improvement, its also capable of Microsoft SQL, PostgreSQL and even Oracle!

**Comment by jimgwhit** [comment]
@LuckyCyborg  and @tomvlk and @daveismyname you people just aren't getting it, the user of the framework should have the choice of database back ends to use, whether it be the original helper, Dbal, or eloquent query builder / database. Now what part of that is so complex that you do not understand?

**Comment by LuckyCyborg** [comment]
@jimgwhit Amaze me! What make the End-User unable to use its **Database or DBAL** of choice?

BTW, there you can watch a preliminary Example for our "Indoctrinated" **DBAL** who is five time more simple as code and hundred times more powerful...

http://smvc3.giulianaeassociati.com/demos/doctrine

**Comment by jimgwhit** [comment]
@LuckyCyborg and @tomvlk and @daveismyname furthermore, if you going to include dball as default the framework instructions should include how to use the original or the illuminate database as an alternative. I consider these being the main two alternatives to dbal.

**Comment by jimgwhit** [comment]
On mobile now will give example later.

**Comment by LuckyCyborg** [comment]
@jimgwhit Worry not, Jim! The **Doctrine DBAL** do the **dirty work** for you beloved **Illuminate Database** too. Perfect Compatibility between our native **DBAL** and Laravel's shiny one. :smile: 

Everything else is just playing with classes... :smirk:

**Comment by jimgwhit** [comment]
@LuckyCyborg and @tomvlk and @daveismyname 
From dbal site
~~~
By default the Doctrine DBAL does no escaping. Escaping is a very tricky business to do automatically, therefore there is none by default. The ORM internally escapes all your values, because it has lots of metadata available about the current context. When you use the Doctrine DBAL as standalone, you have to take care of this yourself. The following methods help you with it:
~~~
But the original database helper took care of this because of bindings and prepared statements.

**Comment by LuckyCyborg** [comment]
@jimgwhit Worry not, Jim!

It is about a shiny thing which only **Doctrine ORM** is able to do: to pre-process **your raw SQL Query**, and to escape on-fly the values.

Meantime, if you use **only** Doctrine **DBAL**, like on using **PDO**, you should always use **the parameters binding**.

**Comment by LuckyCyborg** [comment]
Okay, guys!

I finished the Example for our new **DBAL**, bilt on top of **Doctrine DBAL**, showing the basic CRUD operations. There you can see the Example, on-line:

http://smvc3.giulianaeassociati.com/demos/dbal

Comments? It is complicated? Looks familiar of Chinese for you?
