### ISSUE TITLE
About implementation of a (small) ORM native into Nova Framework 

### ISSUE THREAD

**Issue by LuckyCyborg** [simple-mvc-framework/framework#365]
Sure, there are plenty of powerful **ORM**s... Some are "indoctrinated", other are "illuminated". :smirk: 

But sometimes, while still you want to use an ORM, from habits or even from necessity, those "indoctrinated" or "illuminated" ORMs are overwhelming for your current project.

Then, I and @tomvlk , we decided to write a small one for Nova Framework.

But, in your opinion, what you expect from a small **ORM**?

I for one, I see an small **ORM** essentially as a **DataMapper** who manage **Entities**.

I even find one which looks right on as the Design I have in mind, it is called **Spot**:

http://phpdatamapper.com/

Sure, make no sense to integrate directly it, using yet another Events Manager (and we already have three), and wanting its own dedicated Connection; still, it use for Database Connection, guess what? **Doctrine DBAL**.

In other hand, it have nice Events, very similar with our **BaseModel**, known about **Relations** and other nice things. I'm about opinion that if we reuse its code to write our ORM, will rise something good.

Your opinion? You will like something like/similar with **Spot** included into Nova Framework?

**Comment by tomvlk** [comment]
save,insert and finds by the orm is required, and is currently the aim I think.
Using annotations for the table and column names, types etc.

**Comment by LuckyCyborg** [comment]
How about **Relations** ?

I.e. An User **hasMany** Posts, but **hasOne** Profile.

**Comment by tomvlk** [comment]
Maybe, Dunno.

**Comment by LuckyCyborg** [comment]
Study that **Spot**, from the given link, is small, works on top of Doctrine DBAL and have lots of shiny things.

But I guess we can't integrate it directly in Nova Framework...

**Comment by tomvlk** [comment]
Well, it uses return arrays, not really entity in my opinion. It's just a define of structure and not a real object class.

**Comment by LuckyCyborg** [comment]
@tomvlk Study better the thing. It use **Entities** as in **Entities**. :smirk:

**Comment by tomvlk** [comment]
The method of defining isnt nice. You just return an array that defines the columns, it's better to just make fields in a class. Like I'm making.

**Comment by LuckyCyborg** [comment]
@tomvlk It is his own vision, works even that way... :smirk: 

In other hand, I do not said to import literally that ORM in our tree. 

I said **to reuse** its concepts and its code, to develop our ORM.

**Comment by tomvlk** [comment]
I think annotations (what I'm working on) are better for this.
But I don't have that much time today, will have more tomorrow.

**Comment by LuckyCyborg** [comment]
@tomvlk Okay, let's see...

**Comment by tomvlk** [comment]
@LuckyCyborg Could you please look into https://github.com/tomvlk/php-framework/commits/3.0-db-orm this commit history for some implementations.

Currently I only have the Car::get($id) method up and working. But you can see the way to define the entity table and columns.

**Comment by tomvlk** [comment]
@LuckyCyborg Btw, I'm in love with the QueryBuilder. It's pretty cool, and we should use it in the ORM Entity stuff to support all drivers.

**Comment by LuckyCyborg** [comment]
@tomvlk Then, I think that you understand that choosing to migrate to **Doctrine DBAL** was a well thought strategic move... :smirk:

**Comment by LuckyCyborg** [comment]
@tomvlk Looking at your ORM, looks good for a starting point. Congratulation! :+1: 

But to remember that **ORM** stands for **Object-Relational Mapper** and the **Relations** between objects, also the lazy loading of related objects, are essentials characteristics for an **ORM**.

**Comment by LuckyCyborg** [comment]
@tomvlk For naming consistency you can rename:

```php
    public static function find()
    {
        return self::getLink()->createQueryBuilder();
    }
```

AS

```php
    public static function getQueryBuilder()
    {
        return self::getLink()->createQueryBuilder();
    }
```

**Comment by LuckyCyborg** [comment]
@tomvlk BTW, Big attention at QueryBuilder!

Never pass data got from user input to QueryBuilder (string) fields, because nothing is (and can't be) escaped by automatically. You should always use parameter bindings or to build expressions, like you already made.

**Comment by LuckyCyborg** [comment]
@tomvlk Another thing:

Please learn to use:

```php
use PDO;
```

And stop using ROOT **\**, as in **\PDO::FETCH_CLASS**, for example. It is more simple. :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg Look once again, I've made the save() method, that inserts or update the entity in the database. (Warning, the mysql db will not be cleared when executing tests yet).

**Comment by tomvlk** [comment]
@LuckyCyborg Stuff that isn't done yet is simple finding methods. (only get with the primary key(s) is done).

**Comment by tomvlk** [comment]
@LuckyCyborg And indeed, I read about the QueryBuilder, it's very dangerous, nothing is auto escaped by default. You have to do it indeed. Like I did already in the **Car::get()**

**Comment by LuckyCyborg** [comment]
@tomvlk In other hand, I wonder why you use internally the QueryBuilder; sure, for fun is OK, but I suggest you to pass on 'orthodox' methods, being slightly faster.

And, BTW, I prepared into **\Nova\DBAL\Connection** some methods specially for you, to simplify your work in ORM. Go a look.

**Comment by tomvlk** [comment]
@LuckyCyborg I'm using it for the different dialects of SQL for selecting and inserting/updating. This will have maximum support for all drivers.

**Comment by LuckyCyborg** [comment]
Worry not! Under Doctrine DBAL you should not care about SQL Dialects... :smirk: 

Or you write right commands and they are accepted, or the DBAL will nuke the fridge.

**Comment by tomvlk** [comment]
@LuckyCyborg Theres an error in ``` public function fetchClass($statement, array $params = array(), array $paramTypes = array(), $className = null) ```

Look at line 112, It's refering to the undefined $sql.


You mean to use the SELECT on the ``` get($id); ``` method? (And then fetchClass you prepared :tada: ?)

**Comment by LuckyCyborg** [comment]
@tomvlk A minute to take a look!

**Comment by tomvlk** [comment]
@LuckyCyborg I can fix it but it won't be included for now.

**Comment by LuckyCyborg** [comment]
@tomvlk In few seconds you have a fix into repo.

**Comment by LuckyCyborg** [comment]
@tomvlk Done, please update your fork! :smile:

**Comment by tomvlk** [comment]
@LuckyCyborg Done

**Comment by tomvlk** [comment]
@LuckyCyborg :laughing: Nova is fast, you see :laughing: :rocket:

**Comment by LuckyCyborg** [comment]
@tomvlk He he! Let's say that this is working in team. When every one know its part of code. :smirk:

**Comment by LuckyCyborg** [comment]
@tomvlk **autoIncredimental** ?

**Comment by tomvlk** [comment]
@LuckyCyborg Thats for auto incredimental columns, Will be filled with the lastInsertId() value when inserting.

Btw, something is wrong with your fetchClass, I get exception No valid Entity Name is given: , line 62 of connection.php. I think your not giving the class to the connection.

**Comment by tomvlk** [comment]
@LuckyCyborg A I see , parameter order is not good in the return $this->select(...).

**Comment by LuckyCyborg** [comment]
Yep, sorry! Fixed now, PR incoming.

**Comment by LuckyCyborg** [comment]
@tomvlk Please update your fork!

**Comment by tomvlk** [comment]
@LuckyCyborg Already done :rocket:

**Comment by tomvlk** [comment]
@LuckyCyborg Next error :laughing: 
```
PDOStatement::fetch() expects parameter 2 to be integer, string given
```

The fetch isn't having a second parameter, instead, use this before the fetch() on the statement:
```php
$statement->setFetchMode(PDO::FETCH_CLASS, $className);
```

**Comment by LuckyCyborg** [comment]
@tomvlk Update your fork, please!

**Comment by LuckyCyborg** [comment]
@tomvlk But something is strange...

setFetchMode(PDO::FETCH_CLASS);

have a single parameter

**Comment by tomvlk** [comment]
@LuckyCyborg For PDO maybe, but for DBAL's (doctrine/dbal/lib/Doctrine/DBAL/Driver/ResultStatement.php) it has a few optional args.

**Comment by tomvlk** [comment]
@LuckyCyborg Look at my last commit btw.

**Comment by LuckyCyborg** [comment]
@tomvlk Looks good. 

And BTW, in the second array you can specify the binding types for parameters, that's improve the security and you can obtain them from Entity

In other hand, there is a last minute change on **\Nova\DBAL\Connection**

**Comment by LuckyCyborg** [comment]
@tomvlk Same thing for your **insert** and **update**. You can prepare the parameter types from Entity Annotations. 

And is more safe.

**Comment by tomvlk** [comment]
@LuckyCyborg Indeed, Will implement that once DBAL is stable (or is it already?).

**Comment by tomvlk** [comment]
@LuckyCyborg And the delete is incomming!

**Comment by LuckyCyborg** [comment]
@tomvlk I supose that is in RC, at minimum.

Was just about to add some convenience method on **Connection**.

And the last (untested) method was **fetchClass**, thing happened now. You have all the shiny things from \Doctrine\DBAL\Connection there. :smirk:

**Comment by tomvlk** [comment]
@LuckyCyborg This is going to look sexy! :laughing:

**Comment by LuckyCyborg** [comment]
@tomvlk To remember to prepare the **paramTypes** for second array!

You should be able to get them from Annotations.

**Comment by LuckyCyborg** [comment]
@tomvlk 

> This is going to look sexy! :laughing:

Yep, that's a sexy **DataMapper**. To arrive to an **ORM** will be need also for **Relations**...

**Comment by tomvlk** [comment]
@LuckyCyborg Indeed, relations needs to be implemented too, but first things first.

**Comment by LuckyCyborg** [comment]
@tomvlk But, be warned! **Relations** without **lazy loading** its a nuclear bomb!

As in, while loading one Entity from Database, you can to hundreds and hundred of Database Server Requests and memory consumption will explode.

**Comment by tomvlk** [comment]
@LuckyCyborg I know, Lazy loading is a requirement!

**Comment by tomvlk** [comment]
@LuckyCyborg I think this would be enough for merging the current progress. Agree on it?

**Comment by LuckyCyborg** [comment]
@tomvlk Looks OKay for pushing.

I have only to argue about **getColumnArray** . Is not meaningful for me.

Why not **getColumns** ?

**Comment by LuckyCyborg** [comment]
@tomvlk Also **getPrimaryArray** ?

**Comment by LuckyCyborg** [comment]
Also, for a common style with **BaseModel**, how about to have instead of **get($id)** -> **find($id)**

**Comment by LuckyCyborg** [comment]
@tomvlk Also I seen usually used **find($id)** into ORMs...

**Comment by tomvlk** [comment]
Ye...

**Comment by tomvlk** [comment]
@LuckyCyborg We got a problem btw, the pdo fetch as class creates the Entity, but then it doesn't know that it's fetched, (the state).

**Comment by tomvlk** [comment]
@LuckyCyborg For now I'm going to resolve this by setting the _state in the find($id) method. But we need to check for a better solution.

**Comment by LuckyCyborg** [comment]
@tomvlk Well, cache the result, if is instanceof Entity set the state and return the result

**Comment by tomvlk** [comment]
@LuckyCyborg Doing that now, but we should take care of this when searching for multiple records too.

**Comment by LuckyCyborg** [comment]
@tomvlk 

```
if($result instanceof Entity) {
    $result->_state = 1;
}

return $result;
```

**Comment by tomvlk** [comment]
@LuckyCyborg Anyway, pull is open, will merge. and work on it later, can't continue right now unfortunately.

**Comment by LuckyCyborg** [comment]
@tomvlk OKay, push it.

Also, talking of multiple records, of course we need **findMany** and **findAll**

**Comment by LuckyCyborg** [comment]
@tomvlk I believe that instead of the strange **autoIncredimental** you should use *autoIncrement**, which is similar with the name used into SQL commands.

**Comment by tomvlk** [comment]
@LuckyCyborg ye, autoIncrement would be better indeed :laughing:

**Comment by LuckyCyborg** [comment]
@tomvlk I do not understand a thing:

Why you need multiple primary keys for defining a single **Entity** ?

There is no need, and results in huge complications in an **ORM** case, while defining the **Relations** between the **Entities**.

To properly manage an **ORM** system, without going nuts, always should have an unique ID, usualy, being the fastest, an (LONG)INTEGER, called **id**, while, for example, the **belonging to** Entity have its **id** stored as lowercase "entityname_id". 

This way is defined an **belongsTo** definition into Database Record.

To complete the example, think something like Posts with Categories.

The Entities are called **Post** and **Category**.
The associated tables are called **posts** and **categories**

Using the Relation **belongsTo**, in the **Post** record we have a column called **category_id** who store an INT

When you load the Entity **Post** from Database, is initialized the field **category_id**.
When the user ask for **belonging to**, usually via magic method **__get** read the **Category** entity and give to user.

Then, when the end-user do:
```php
$category = $post->category
``` 
Practically, is loaded and initialized an instance of associated Entity (Category), on demand.

That's is so called **the lazy loading**, and the Design of **belongsTo**.

The inverse, the Categories **hasMany** Posts. Knowing that, the ORM use a JOIN, to prepare an array of **ID**s of Posts belonging to this Category.

When the User asks for Posts from that Category:

```php
$posts = $category->posts;
```

Practically, the ORM, via the magic method **__get**, or even better **__call**, to simulate **$category->posts()** do an **findMany** and return the array of Posts defined by their previously prepared IDs. 

That's already a **lazy loading**, because the Posts are retrieved in demand, when User asked for, and if he ask to Category Name, nothing happen in plus, as Database Requests.

If you want, I will tell you how it works all usual **Relations**, but, very important to understand: 

### STOP PLAYING WITH MULTIPLE KEYS IN AN ORM!

**Comment by tomvlk** [comment]
Everything you wrote down there was already in my head as an idea. Still in development.

**Comment by LuckyCyborg** [comment]
@tomvlk Was a comment along your code. :smirk:

**Comment by tomvlk** [comment]
You can't read my mind of course :laughing:

**Comment by LuckyCyborg** [comment]
@tomvlk Sure thing... :smirk:

**Comment by LuckyCyborg** [comment]
@tomvlk Your **Service Demos** nuke the fridge, right now!

The shiny Log Message:

```
Message: SQLSTATE[42S22]: Column not found: 1054 Unknown column '_state' in 'field list'
```

**Comment by tomvlk** [comment]
@LuckyCyborg Thats the old service, you can disable it for now or ignore it for now.

**Comment by LuckyCyborg** [comment]
@tomvlk OKay.

**Comment by LuckyCyborg** [comment]
@tomvlk BTW, I already switched to **DBAL** the **Nova\Core\Model**, then same to our **\App\Core\BaseModel** (which started to behave crazy, BTW).

What we do with those **Database Demos** ?

**Comment by LuckyCyborg** [comment]
@tomvlk Just a note:

Looks like your **Car::find** supports also the finding by other fields than **primaryKey**.

That's strange. Normally, the **find** execute the find after the (unique) ID. then will be **Car::find($id);**

The tasks for searching after another fields are assigned usually to **findBy**. Then we should have:
```php
$searched = Car::findBy('model', 'Framework_ORM_Test_Search_1');

$searched = Car::findBy(array('model' => 'Framework_ORM_Test_Search_1', 'costs' => 50000));
```

**Comment by LuckyCyborg** [comment]
@tomvlk Another note: usualy is nice to have:
```php
Entity::find($id);
Entity::findBy($wheres);
Entity::findMany($id); // List of IDs
Entity::findManyBy($wheres);
Entity::findAll();
```

**Comment by tomvlk** [comment]
@LuckyCyborg I just reworked, I was doing the static variables all wrong, saving into Entity abstract isn't the same as the called class. (for all static methods). So the Entity fully rely on Structure for getting table and column infos.

There is a better solution for this, but currently this is the method I'm using, feel free to come with any suggestions for it.

For the calls, I will follow the following public api interface:
```php
Entity::find($id);
Entity::findBy($where); // This can be either array('key' => 'value') or even array('key => array('LIKE' => '%test%'). Would be better I think?
Entity::findMany($id); // List of IDs
Entity::findManyBy($wheres); // Same as findBy wheres var
Entity::findAll(); 
```
Agree?

**Comment by tomvlk** [comment]
@LuckyCyborg After implementing that api I will open pull again to merge the progress, then lets focus on Relations ;). Any suggestions for the Annotations are still welcome. You already proposed something indeed.

**Comment by LuckyCyborg** [comment]
@tomvlk Okay, some comments there...

First of all, I will argue against your **Entities** to be aware about the DBAL Connection's **linkName** ! That's an inutile complication, generating spectacular errors and just **NOPE!**

Also, I do not see the sense to have the DBAL Connections **Configuration** names into **Annotations**. Again, **NOPE!**

And, lets be honest! When you need to specify the second Database Connection? Almost no one need that thing, and please do not give me the argument of SQLite Tests, because the DBAL have a common and well defined API, beyond its Drivers.

That's WHY there no exists shiny MySQL-ismes, aka your favorite **multi-pass** thingies. :smirk:

So, please nuke those things beyond of **getLink/setLink**

**Comment by tomvlk** [comment]
@LuckyCyborg What solution are you looking at for this? Only using annotations? The linkname there? 
We can spoof the Table instance (annotation) and fake it for tests, it not only for tests. I will do that I think.

**Comment by LuckyCyborg** [comment]
@tomvlk Even in Annotations shall not be coded the Connection Configuration name...

Eventually, into tests, you go with **::setLink()**, or, much much better, switch the Configurations, thing very possible considering that there are only arrays of arrays.

So, the DBAL see only the 'default' configuration.

**Comment by LuckyCyborg** [comment]
Eventually, we add a new configuration option, called **default_config**, where we can select the working setup and it is simple to switch via **Config::set()**.

**Comment by LuckyCyborg** [comment]
@tomvlk For the Tests, I think is better to switch the Configurations, in full way. Practically, for the SQLite tests, just insert a full **Config::set('database', array(...));** to spoof the DBAL.

**Comment by tomvlk** [comment]
Okay. Idea, set the default config in different phpunit configs. And run 2 phpunits. Let the bootstrap inject the env variables into the Config class.

**Comment by tomvlk** [comment]
Or leave as it is but clear the connection instances in our manager, spoof the config and let the manager create a new connection with our spoofed default link.

**Comment by LuckyCyborg** [comment]
@tomvlk Even this way is perfect! One for standard setup, one just only to test your SQLite thingies.

**Comment by LuckyCyborg** [comment]
If you want, I will add and **nukeConnection** into DBAL\Manager.

**Comment by tomvlk** [comment]
@LuckyCyborg letting two phpunits run isn't really pretty and useful for local test execution. So please. Yes. I will make a test utility class that will take care of this injection and nuke at runtime. 
Maybe clearConnections is a better name. Make sure you close them too ;)

**Comment by LuckyCyborg** [comment]
@tomvlk Okay, I added a new static method:

**\Nova\DBAL\Manager::clearInstances()**

Which, you suspect what do! :smirk:

**Comment by tomvlk** [comment]
Thanks. I'm on the move right now. I will refactor the current shit soon tonight :laughing:

**Comment by LuckyCyborg** [comment]
@tomvlk Okay!

BTW, the final method is called **clearConnections**,you will figure you...

**Comment by tomvlk** [comment]
@LuckyCyborg Okay, it's active now.

**Comment by LuckyCyborg** [comment]
@tomvlk What it's active now?

**Comment by LuckyCyborg** [comment]
@tomvlk Please look how I implemented into BaseModel the **findBy** method!

It is a usual way for advanced models and Entities.

**Comment by LuckyCyborg** [comment]
@tomvlk My **findBy**  works something like:
```
findBy('color', 'black'); // WHERE color = 'black'
findBy('color !=', 'black');  // WHERE color != 'black'
findBy(array('color' => 'black')); // WHERE color = 'black'
```

**Comment by LuckyCyborg** [comment]
@tomvlk Give me a reason to not nuke right now the old Engines and old Services.

I ported everything (I think) to DBAL. :smile:

**Comment by tomvlk** [comment]
Nuke the service. Please let the engine in for few seconds. 
The method I implemented for where operator is better in my opinion. It's seperated from the column name and could be better when testing for column name or using the IN like I also support in the current implementation. (Although the findBy should return only one!)

**Comment by LuckyCyborg** [comment]
@tomvlk **findBy** and **findManyBy** should support both array (as first param) or two params.

That's the usual style for Models and Entities.

**Comment by tomvlk** [comment]
I meant the operator IN

**Comment by LuckyCyborg** [comment]
@tomvlk That's Okay, but it should support two parameters, as in:
```php
Car::findBy('color !=', 'black');
```

**Comment by tomvlk** [comment]
Why should it? I don't think it has any extra functionality. 

You can simply do:
findBy(['color' => ['!=' => 'black']])
It makes way more sense. And well known syntax.

**Comment by LuckyCyborg** [comment]
@tomvlk Because it is an usual style and lots of programmers have habits to; and practically is an union of **find** with an **where**.

Just do it like I say, trust me!

After all is not so complicated to implement, comparative with your mega-where-parser... :smirk:

**Comment by mickacz** [comment]
Will it be possible?
``
Car::findBy('color', '!=', 'black');
Car::findBy('year', '>', 2000);
``

**Comment by tomvlk** [comment]
@LuckyCyborg the example @mickacz is way more better, that is reasonal to implement!

**Comment by LuckyCyborg** [comment]
@tomvlk Tom, if you don't give me that style, as one of supported, then for us, your ORM's utility lower substantially.

You believe that someone have fun to write around of 50000000 characters in plus, just for your fun, in a single application? 

We need concise commands or we have to write us what we need. Sorry!

**Comment by tomvlk** [comment]
@LuckyCyborg Wait @mickacz has a way better syntax, it's not always about short code and syntax, then you should also short some more methods in all the code around, making some stuff really unusual.

Its more about the **maintainability** and **understandably** here. The way you are proposing, giving the operator in a column field is really **unclear** and is **confusing**, is also a very bad design.

And sorry, but it's not meant to be a framework only specific with your requirements, I know that you are spending hours in it, same for me, but please don't put some stuff in it that doesn't really help the **community** but more yourself. And just by saying its useless without this is really insane!
But this is about nice **style** and **consistent**, **clear parameter names** and **values** that belong to the parameters without needing to regex it, with all the troubles you could have with it...

**I hope that others agree with me about this fact,** @mickacz

**Comment by tomvlk** [comment]
@LuckyCyborg Please have a look at our big examples here:
http://knexjs.org/#Builder-where (not really ORM, but has a good where syntax)
http://symfony.com/doc/current/book/doctrine.html#fetching-objects-from-the-database

**Comment by mickacz** [comment]
@tomvlk I agree

**Comment by LuckyCyborg** [comment]
@tomvlk Sorry, Tom, if you want to argue with us about what we consider "common sense" for a small project, well, I wish to remember you that we are busy persons, and we prefer to do our tasks instead to open debates over Internet about childish things. 

Do your ORM as you wish, I will stop now to comment about this subject, having another tasks assigned.

Good look! :+1:

**Comment by jimgwhit** [comment]
@LuckyCyborg earlier in this thread it was mentioned that the query builder doesn't escape, but doesn't it when prepared statements are used like:
~~~
$queryBuilder
    ->select('id', 'name')
    ->from('users')
    ->where('email = ?')
    ->setParameter(0, $userInputEmail)
;
~~

**Comment by tomvlk** [comment]
@jimgwhit yes it does in your example. But only with that style of binding.

**Comment by jimgwhit** [comment]
@tomvlk  and @LuckyCyborg that is what I like about the laravel query builder, from laravel docs:
~~~
Note: The Laravel query builder uses PDO parameter binding to protect your application against SQL injection attacks. There is no need to clean strings being passed as bindings.
~~~

**Comment by LuckyCyborg** [comment]
@jimgwhit Let's do not compare guns with cannons!

There is about **Doctrine DBAL**, while you talk about **Laravel ORM**. Worry not! The **Doctrine ORM** is even more powerful than Larevel one... :smirk:

**Comment by LuckyCyborg** [comment]
@tomvlk BTW, I merged you latest PR, that with PHPDOC and fix into '\Exception'. :smirk:
