### ISSUE TITLE
3.0 - Easy Tasks: You would like the Nova to nuke the fridge (go Exception), while yelling in your Language?

### ISSUE THREAD

**Issue by LuckyCyborg** [simple-mvc-framework/framework#416]
## So, you would like the Nova to nuke the fridge, while yelling in your Language?

That's easy, but you need to made some simple but numerous modifications, to internationalize the Exceptions. What to do:

Look into source code for Exceptions, then you should modify, as example:

```php
throw new \Exception("No valid Query Building Method given");
```
BECOME:
```php
throw new \Exception(__('No valid Query Building Method given'));
```

Notice the change into string definition, from double quote into single one, and the function **__()**. 

That function called **__()** is a convenience one, for the Language Domain called **App**.

What you do when you should compose the message with other strings/components? Because we use the native PHP **INTL** based on **ICU**, This way:
```php
throw new \Exception("No valid Entity Name is given: " .$className);
```
BECOME:
```php
throw new \Exception(__('No valid Entity Name is given: {0}', $className));
```

Note the sequence **{0}** .This is the first parameter, in order will be **{1}**,  **{2}**,  **{3}**, etc.

When you change the strings into INTL ones, from **System, Modules and Templates**, you should specify literally the Language Domain, identical with snake_case variant of Module, Template or System, like into this example:
```php
throw new \UnexpectedValueException('Config and Options parameters should be Arrays');
```
BECOME:
```php
throw new \UnexpectedValueException(__d('system', 'Config and Options parameters should be Arrays'));
```

Note the use of the function **__d()**

Finally, is it nice to use, after all your changes, the script **/scripts/makelangs.php** to update the Language files.

What cannot be internationalized? Only few files:
```
public/index.php
system/Config/bootstrap.php
system/Config/functions.php
```

Have fun and I wait your questions, if any! :smile:

**Comment by volter9** [comment]
I don't think that it's a good idea to internationalize exception messages. PHP parser and interpretator don't translate exception and error messages (at least for me), then why should the framework do that? 

Also, for different errors you have (preferably) use different subclasses of exceptions, but not basic (`\Exception`).

**Comment by LuckyCyborg** [comment]
@volter9 Well, I talk about framework messages, or the message strings set in Exceptions just before to nuke the fridge. And this will work.

Also, depending of Server configuration, it is very possible to set the PHP to speak completely into Russian or Italian. :smirk: 

In other hand, there are used already different Exception subclasses, please look into code...

**Comment by tomvlk** [comment]
And how about the developer that wants to check the exception message for some containing words and with changing languages it's maybe a bit weird. 
I'm not really used to translated exception messages. Also. Why should it?

**Comment by LuckyCyborg** [comment]
@tomvlk He he, just to see PHP speaking Italian! :smirk: 

> Why should it?

Because there is an entire World beyond **USA** and **UK**!

And, generally speaking, from my experience, the French, the Germans and Italians love the programs to speak their Language.

**Comment by volter9** [comment]
> see PHP speaking Italian! :smirk: 

Oh, I don't want to see it :D

> please look into code...

I'll take a look later, after stable release, but sorry for inconvenience.

**Comment by LuckyCyborg** [comment]
@volter9 No problem! :smirk: 

BTW, just saying...

I suppose that will feel strange to see in a Russian Server, eventually owned right on by your proud **FSB**, some **Error Messages** into Capitalist English, right?

**Comment by volter9** [comment]
> I suppose that will feel strange to see in a Russian Server, eventually owned right on by your proud FSB, some Error Messages into Capitalist English, right? :smirk:

Ohoho, you're talking in stereotypes, comrade :)
Although, it would be really awkward to see PHP notices on FSB website, like, really really awkward :laughing:

**Comment by nekomajin** [comment]
@LuckyCyborg @volter9 I'll do my very best at translating ([Miss Sophie :kissing_heart:](http://www.dailymotion.com/video/xncnyt_dinner-for-one-hdtv-720p-der-90-geburtstag_fun)). But I admit @volter9 right that there are different interpretations of one and the same word in different languages. Also in Germany.

On the other hand: as long as there are messages to the user / developer, emanating from the incorrect use of a command, it should be fine.

**Comment by LuckyCyborg** [comment]
@nekomajin @volter9 @tomvlk Trust me, my friends, there is enough to appear in a Italian website, a page with this content:

```
An error occurred. The error has been reported.
```

Then there will be hundreds and hundreds of calls from guys afraid that the website is hacked. Because the typical Italian do not speak English. For them, the World speak Italian, just like an American think that the World speak (American) English. :smirk:

**Comment by geomorillo** [comment]
i hate "An error occurred. The error has been reported." i agree with @LuckyCyborg  i would prefer "Ha ocurrido un error. El error ha sido reportado" so nice to know you are thinking on us,

**Comment by LuckyCyborg** [comment]
@geomorillo Then I can add also the **Spanish** as the people who love the programs to talk in their Language... :smirk:

**Comment by daveismyname** [comment]
I think it does make sense to let developers set the language or errors to their own language, not everyone uses English after all.
