### ISSUE TITLE
Which one we will keep by default? The Doctrine based DBAL or our own PDO based (Mini-)DBAL ?

### ISSUE THREAD

**Issue by LuckyCyborg** [simple-mvc-framework/framework#435]
Dear friends,

like I said, I received instructions to improve the **\Nova\Database** as a lightweight alternative to **\Nova\DBAL**, targeted for (very) small websites.

Now, its API is much more consistent, probably being strong enough to support even the  Tom's **ORM**, have even an integrated a nice **QueryBuilder**, on top of **FluentPDO** and other nice things, while keeping a small profile as code dimensions.

It is also slightly faster than the Doctrine based DBAL, about **40-50%**, as expected, considering that is much more lightweight (as dependencies).

Sure, if we talk about drivers support, the Doctrine DBAL is definitively superior, our mini-DBAL having right now support for only **TWO**: the PDO's **MySQL** and the PDO's **SQLite3**, and also, the first one having another nice components like the **Schema** and being Event driven.

Yet, right now we have, in the tree, two **DBAL**s able to support a small site, yet one, our PDO based mini-DBAL sporting **764KB** as total size, including its dependencies, while the Doctrine based one sports a venerable **64MB**. :smile:  

Our proposal is not to nuke the Doctrine based **\Nova\DBAL**, but to move into a separate project, living momentary in one of our branches, then, after Dave returns, we will be happy to maintain it as a **Project of Nova Framework**. 

Worry not, we intend to use ourselves, in our projects the Doctrine based **\Nova\DBAL**, so its future is guaranteed.  :smirk: 

And maybe, in future, we will develop yet another **DBAL**, for example based into **Laravel Database**, as our end-users (and us) to have a galore of **DBAL**s of choice and alternatives.

Still, after considering and testing well the things, we are on opinion to leave **\Nova\DBAL** alone to live in its own Project.

Then, what is your opinion into this? You are about to keep the **\Nova\DBAL** into main tree or to move into its Project?

PS. We can keep the **Doctrine Common** and its **Annotations** with no problems, then the Tom's **ORM** can work directly on top of **\Nova\Database** with slightly modifications, as today.

**Comment by jimgwhit** [comment]
@LuckyCyborg one possiblity is to have the smaller one default, and not have dbal in composer, but give instructions on how to pull in dbal if someone wanted to use it.  Like I showed, I had already tested dbal in ver 2.2.  
You could have the framework dbal ready, but of course it would be disabled since not installed, and to use a person just add the requirements in the composer file and it's there.  
But since you came this far, why not just use dbal?  It is a good strong and also easy to use database layer.  
And yet another option is have both, but does that make sense?  
Well that's my thoughts on it.

**Comment by LuckyCyborg** [comment]
@jimgwhit Jim, if you like to know how we see the Doctrine based DBAL as separate Project, well, will be a **Module**.

A modules, in our POV, is not only a MVC isolated component. We see them as a mini-App or Extension.

Then, the future Doctrine based DBAL module can even sports, beyond the API, its very own **Demos** and other shiny thins. The user who want it, will install the Module and activate it in Application Configuration and Voila!

There is the shiny **DBAL** which can be used by another modules, or even for custom developments.

We just need to find a nice and meaningful name for Module.

**Comment by jimgwhit** [comment]
@LuckyCyborg If you can only do one by default, may as well be doctrine Dbal.  But I don't know how @daveismyname feels about it.  In all reality, I like the way I showed using dbal in ver 2.2 also.  I guess I just like being able to have some control, like the css thing, I don't like the assets, hooks, and all that stuff.  To me I just like the:
```
<link href="<?php echo site_url('/assets/css/style.css'); ?>" rel="stylesheet">
```
way of doing it.

**Comment by LuckyCyborg** [comment]
@jimgwhit We prefer to move to Modules the Doctrine one, being still huge for mini websites.

But, why you prefer the Doctrine **DBAL** one? For its **QueryBuilder** ? Well, also **\Nova\Database** sports one, and it is very efficient, in our opinion. :smirk: 

In other hand, if you don't like 
```
<link href="<?php echo site_url('/assets/css/style.css'); ?>" rel="stylesheet">
```
you can write 
```
<link href="/nova/assets/css/style.css" rel="stylesheet">
```

But hardcoding those things will be bad when you  move the site in the final position. The **site_url** was invented right for helping when you develop in a sub-directory, then you have to move the site.

We, personally, always we develop in Virtual Hosts, then we can use even the direct style, with no problems.

**Comment by jimgwhit** [comment]
@LuckyCyborg  so after all of the DBAL discussions, now it's not going to be included in the framework?  But can it still be pulled in with composer and used the way we discussed in the other issue?

**Comment by LuckyCyborg** [comment]
@jimgwhit Have importance if Doctrine based **DBAL** live in:

```php
namespace Nova\DBAL
```

or if it live in:

```php
namespace App\Packages\DBAL
```

I talk about dividing it i its very own Nova Project, not about nuking it. Ourselves we intention it together with Nova in some projects. 

Like another projects will be better for using the small DBAL one. And another projects to use a full **Doctrine ORM**.

**Comment by jimgwhit** [comment]
@LuckyCyborg but my question is will Nova as downloaded and installed from the site be able to use doctrine Dbal?  Remember you are the one who originally wanted it included.

**Comment by LuckyCyborg** [comment]
@jimgwhit It is about a better organization of the things. 

For example, for some, the DBAL is overkill, and the **\Nova\Database** is more than enough for a site with ten pages and a three administrator on **Backend**.

Me and you, we want the do use the DBAL based on Doctrine. Easy, we download, install in its path, and we have everything out-of-box, with its **BaseModel**, etc.

Others, maybe will want **Doctrine ORM** into their Nova. Easy, they download, install in its path, and they have everything out-of-box, with its **BaseModel**, etc.

Yet, others, maybe will want **Laravel Database** into their Nova. Easy, they download, install in its path, and they have everything out-of-box, with its **BaseModel**, etc.

You see the light?

BTW, we talk about that it is better to use very important components into namespace **App\Packages** instead of **App\Modules**

**Comment by LuckyCyborg** [comment]
@jimgwhit To undestand what will be with Doctrine based DBAL moved in it own Package, look now in my branch:

#### https://github.com/simple-mvc-framework/framework/tree/3.0-beta

download the ZIP and look into:

#### app/Packages/DBAL

**Comment by jimgwhit** [comment]
@LuckyCyborg I don't see a app/Packages folder on that site.

**Comment by LuckyCyborg** [comment]
@jimgwhit Sorry, it is about:

#### https://github.com/LuckyCyborg/simple-mvc-framework/tree/3.0-beta

**Comment by LuckyCyborg** [comment]
@jimgwhit Still I do not have a better name for DBAL's **Package**. Maybe will be better **Doctrine** or even **Dottrina**  (in Italian) :sake:

**Comment by jimgwhit** [comment]
@LuckyCyborg  So from the way we used dbal in issue #364 how would it be used in 
app/Packages/DBAL?  
Also from what you described above, it appears the framework will be able to use other database management tools, such as meedo, a generic PDO wrapper, illuminate database, etc. Is that now the case?

**Comment by LuckyCyborg** [comment]
@jimgwhit 
> So from the way we used dbal in issue #364 how would it be used in
app/Packages/DBAL?

It is simple, just you use instead of:

```php
use Nova\DBAL\Manager as Database;
```
as

```php
use App\Packages\DBAL\Manager as Database;
```

or, much better:

```php
use App\Packages\DBAL\Model as BaseModel;

class MyShinyModel extends BaseModel
{
...
}
```

> Also from what you described above, it appears the framework will be able to use other database management tools, such as meedo, a generic PDO wrapper, illuminate database, etc. Is that now the case?

Overall, you got the idea! :smirk: 

We try to make the Framework more flexible, and of course!, if someone (want and) write a Package on top of **Meedo** or **Illuminate Database**, they can be used into Framework.

**Comment by jimgwhit** [comment]
@LuckyCyborg you said 
a Package on top of Meedo or Illuminate Database, they can be used  
Are you saying a package would have to be written, or can illuminate database be used by simply overriding the current database like in version 2.2? Also like demonstrated an issue #364 where the model was simply overwritten by the dbal information.

**Comment by LuckyCyborg** [comment]
@jimgwhit Of course that someone would have to write a **Package** for Meedo, for it to work, for example. :smirk: 

Think about **Packages** as some extensions, similar with the **Modules**, but **without** Routing, Controllers and Views support.

**Comment by tomvlk** [comment]
I will work on the orm today. Tell me if I have to move to the old engine a like.

**Comment by LuckyCyborg** [comment]
@tomvlk About what old Engine you talk? :smile: 

I refactored the **\Nova\Database** as small **DBAL**.

In other hand, right now I mussing about moving the **ORM** to a Package. 

In other hand, if you want the **ORM** to remain into System, aka **\Nova\** namespace, you should rely, in future, only into **\Nova\Database** services and **Doctrine Annotations**.

**Comment by mickacz** [comment]
@LuckyCyborg for example. I installed from Composer:
```
"illuminate/database": "*",
```
What now needs to be done in Nova to use this?

**Comment by LuckyCyborg** [comment]
@mickacz Probably to write some Wrapper or Package to integrate it? :smirk: 

For example, one can want your Illuminate Database to read our Configuration style, to have a dedicated base Model, a Database instance, etc...

It is simple: the **system** is only for Nova's System and no one should touch it, adding or changing something. everything else should go into Application.

And, if someone want to write some more complex but reusable work, he should use Packages or Modules for that.

**Comment by LuckyCyborg** [comment]
@tomvlk And another thing, about your **ORM**.

If your ORM API do not support also WHERE conditions something like:

```php
where('username != ?', 'admin');
```

Again, if it do not support that type of conditions, as one of the accepted variants, our interest into your **ORM** is very small, it having no use for us.

Then, I strongly recommend to move it to a Package. :smirk:

**Comment by mickacz** [comment]
@LuckyCyborg When you will have some time, can you prepare a sample package for Illuminate Database? :)

**Comment by LuckyCyborg** [comment]
@mickacz Sure, probably we will do it.

To be honest, it is one of the Packages interested into. Another one being **Doctrine ORM**.

But we see the Illuminate Database as a whole, including its **ORM**, then it will be not soo simple... :smirk:

**Comment by LuckyCyborg** [comment]
And there is the Demo of the **DBAL** from **App\Packages\DBAL** :+1: 

### http://smvc3.giulianaeassociati.com/demos/models/dbal_model

Like you can see, a Package can be properly used by another Components.

**Comment by jimgwhit** [comment]
@mickacz  watch the prior video Dave did on using illuminate database, and study issue #364 where dbal was used, it's similar. Also in the forum there are instructions. Basically you have to override the default database helper with the illuminate database.

**Comment by jimgwhit** [comment]
@LuckyCyborg you keep speaking of the term packages, in reality don't you just mean a class, or classes? I mean at the end of the day all of the special terms are just classes doing something, I don't believe in putting special names on them like the laravel folks do.  
I mean for crying out loud, recently I saw a post about mutatets, I thought to myself what in the blankety blank, they were talking about getters and setters. Why do modern people had to have pretty specialized terms for something, a sanitation engineer is a garbage man. Another one, a custodian engineer, is a janitor, now is that so hard to accept?

**Comment by jimgwhit** [comment]
@LuckyCyborg how come @tomvlk mimi dbal looks similar to meedo, and it doesn't look like in the background prepared statements are used, are prepared statements used, if not that's a bad thing.  
Will normal query statements still be available like doctrine Dbal uses?

**Comment by jimgwhit** [comment]
@LuckyCyborg you know you could just use the illuminate database as the default database for Nova, that does not mean the ORM has to be used, this would make things so simple, and we all know the illuminate database is real real real real good. Plus it is very very easy to use. And of course have an option available to use doctrine Dbal if that's what someone wanted to do.  

But really instead of messing with that mini dbal thing, why don't you ask Dave to let's just use doctrine Dbal, I think that would be a good way to go, it's also easy to use. Plee with Dave if you have to, beg him,  talk him into it somehow. @daveismyname read this.

**Comment by daveismyname** [comment]
I'm overwhelmed with the changes right now, I need to look at the different database setups that seem to now exist! 

Without looking into them my initial thought is to use the helpers database then make the others optional add-ons or packages but I can't be sure right now without looking through the files and trying them out.

**Comment by jimgwhit** [comment]
@daveismyname don't forget to check out issue #364  where there is an in depth doctrine Dbal example, @LuckyCyborg originally was including doctrine dbal but then changed his mind. And good to hear from you again how was your little trip? I hope you had a good time.

**Comment by LuckyCyborg** [comment]
@jimgwhit I not changed my mind. I just try to organize the things. Yet I'm ashamed to see an **Illuminated** like you to be so... "indoctrinated" ! 

PS. That's your choice, Dave's here. If you convince him, I will integrate completely, finishing with Models, at you choice, the Doctrine ORM or Laravel ORM... :smirk: 

Go out and fight, man! :+1:

**Comment by jimgwhit** [comment]
@LuckyCyborg  I will try,  @daveismyname  PLEASE let's use doctrine Dbal.  
Well @LuckyCyborg  you need to beg him to, I think we both like doctrine Dbal.

**Comment by daveismyname** [comment]
Like I've said I need to look at things before I can understand fully what we are discussing.

**Comment by LuckyCyborg** [comment]
@daveismyname In principle, what Nova sports now is a mini-DBAL into namespace **Nova\**, and the full blown Doctrine based **DBAL** as a Package. 

The users can chose to use the lightweight one, written by us (and it is literally faster, around **40-50%**) or the powerful one, based into Doctrine DBAL, living as Package, like I said.

**Comment by jimgwhit** [comment]
@daveismyname please test the mini-DBAL good, does it use prepared statements and binding? Your original database helper did these things since it was based right on PDO. Family safety standpoint I'd be leery have anything that didn't Auto use prepared statements and data binding in the background.

**Comment by LuckyCyborg** [comment]
@daveismyname and @jimgwhit 

To this question I can give myself a response... :smirk: 

One of the reasons of the demise of Doctrine based DBAL as Package was that while powerful, it is clearly designed to be used as base for a "machine processing style", like the eventually Doctrine ORM. Then you have to use a well defined style for ensuring the parameters quoting and  binding.

In contrast, the now **\Nova\Database** it is much more noob-friendly and have more relaxed specs, automatically binding the variables under prepared statements and, after all, giving a more clean syntax under the small websites case.

Before to blame **\Nova\Database** to note that right now permit syntax like:

```
$data = array(
    'activated' => true,
    'activated_by' => $userid
);

$where = array(
    'id' => array(2, 3, 4, 6),
    'activated' => false,
    'username != ?' => 'virgil'
); 

$result = $connection->update('users', $data, $where);
```

**Comment by jimgwhit** [comment]
@LuckyCyborg and @daveismyname but will regular queries be able to be written like the original database helper, sometimes and especially for me I like using regular SQL queries. And of course with the data binding and prepared statements. Please make sure this functionality is included.

**Comment by daveismyname** [comment]
> automatically binding the variables under prepared statements

@jimgwhit yes is the answer to both those questions just scanned the class I can see the methods make use of a select method which internally does the prepare and bind.

**Comment by jimgwhit** [comment]
@daveismyname whew thank goodness.

**Comment by jimgwhit** [comment]
@LuckyCyborg and @daveismyname will doctrine Dbal or illuminate database be able to be used like we discussed in issue #364 ?

**Comment by daveismyname** [comment]
I'm confused where can I see an example of the doctrine dbal being used? unless I'm mistaken the demo module is using Nova\Database

**Comment by LuckyCyborg** [comment]
@daveismyname The Doctrine DBAL based was that Demo where you switched fetchAssoc -> fetchArray and changed to Database\Manager from DBAL\Manager

Wondering if is better to ship the Doctrine based DBAL as a Module, including its own Demos...

**Comment by LuckyCyborg** [comment]
@daveismyname BTW, for the Doctrine based DBAL you are kind to choosee a proper name for Package, eventually Module?

Right now, the Package  is called **DBAL**, and that is soooo generic.

**Comment by jimgwhit** [comment]
@daveismyname look mid way in issue #364 where I had made an app\Dbl folder, and used doctrine dbal siimilar to your video you did on illuminate database. However this was done in Nova.  
Another way of asking this is will medoo, doctrine dbal or the illuminate database still work in Nova if pulled in with composer, what files would have to be overwritten?  
Or will Nova be restricted to using only the database helper that's included?

**Comment by daveismyname** [comment]
since there compose based they will be able to work like I did in earlier videos I would imagine, I don't see anything that would stop that from running.

Looking at the module demo so far I'm liking demos/dbal this is using system/Database/Connection which is why I'm confused I thought doctrine was the one in the package directory

**Comment by LuckyCyborg** [comment]
@jimgwhit About what "database helper" you talk Jim? 

Stop calling the **Nova's Database Abstraction Layer** as "database helper", please!

The single existent "database helper" is a legacy wrapper one, adapting \Nova\Database to the old/legacy style.

> Another way of asking this is will medoo, doctrine dbal or the illuminate database still work in Nova if pulled in with composer, what files would have to be overwritten?

Go figure! We are talked about this subject for days!

> Or will Nova be restricted to using only the database helper that's included?

Nope! You can't be restricted to a nonexistent "database helper".

**Comment by LuckyCyborg** [comment]
@daveismyname 

> Looking at the module demo so far I'm liking demos/dbal this is using system/Database/Connection which is why I'm confused I thought doctrine was the one in the package directory

The Demo for Doctrine based DBAL is right now:

http://smvc3.giulianaeassociati.com/demos/models/dbal_model

**Comment by daveismyname** [comment]
ah that explains my confusion right now I like http://smvc3.giulianaeassociati.com/demos/dbal

with http://smvc3.giulianaeassociati.com/demos/models/dbal_model how would joins work? nearly all my queries require joins from usually 3 or 4 tables.

**Comment by jimgwhit** [comment]
@daveismyname no matter what we need a database abstraction layer where you can write regular style queries. @LuckyCyborg I just got my terminology wrong, but you know what I meant. Also the new question was asked because you said doctrine dbal will not be included now where originally you said it would be included. If you do include it, you can write regular queries in doctrine dbal so why not include it?  
@LuckyCyborg please remember it was originally you that wanted doctrine dbal, so what gives here, why pull it all of a sudden?

**Comment by LuckyCyborg** [comment]
@daveismyname Both the Mini-DBAL, aka the **\Nova\Database** and the Doctrine based DBAL, aka **App\Packages\DBAL**, supports the JOINS like a charm.

To note that on the QueryBuilder shipped by **\Nova\Database**, based into FluentPDO the support for joins is at a epic level. You can write complicated joins in few commands!

@jimgwhit The Doctrine based DBAL does not go anywhere! We will maintain it, eventually in a separate repository, and we will use it ourselves. 

 In other hand, we arrived to conclusion that it is too big for small projects and asking for strict building style. Then, we suppose that it will create confusions to the beginners...

**Comment by jimgwhit** [comment]
@LuckyCyborg question still not answered can it still be used in Nova after all the changes?

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> @LuckyCyborg question still not answered can it still be used in Nova after all the changes?

Considering that it is specially designed for Nova, go figure!

**Comment by jimgwhit** [comment]
@LuckyCyborg why would doctrine dbal be too hard for beginner, when the regular queries are written the same as Dave's original database helper, just minor changes. Furthermore even a beginning  has to learn to use harder things. Remember you are the one who wanted it in the beginning for nova.

**Comment by LuckyCyborg** [comment]
@jimgwhit I said hundreds times, the Doctrine based DBAL does not go anywhere! :smile: 

We prefer to make it a (optional) Package because for small Projects, all we need it is **\Nova\Database** , which is faster (around 40-50%), more simpler and permit to use a more relaxed syntax.

We will use the Doctrine based DBAL for more complex projects, then it will be always available for us, if is need.
