### ISSUE TITLE
Load 404

### ISSUE THREAD

**Issue by daveismyname** [simple-mvc-framework/framework#460]
@LuckyCyborg I've noticed if I turn off the catchall route and go to a url that does not exist I'm getting an error instead of the 404 page:

````
Exception information:

Date: Jan 10, 2016 15:56PM

Message: Unknown Views Path for the Class: \App\Controllers\Error

Code: 0

File: system/Core/Controller.php

Line: 83

Stack trace:

#0 system/Net/Router.php(219): Nova\Core\Controller->initialize('\\App\\Controller...', 'error404', Array)
#1 system/Net/Router.php(248): Nova\Net\Router->invokeController('\\App\\Controller...', 'error404', Array)
#2 system/Net/Router.php(296): Nova\Net\Router->invokeObject('\\App\\Controller...', Array)
#3 system/Config/bootstrap.php(76): Nova\Net\Router->dispatch()
#4 public/index.php(70): require('/Users/davidcar...')
#5 {main}
````

The error controller has this:

````
View::renderPage('error404', $data);
````

I'm unsure of how the views now work.

**Comment by LuckyCyborg** [comment]
@daveismyname I will take a look right now.

**Comment by LuckyCyborg** [comment]
@daveismyname BTW, we talk about **\Nova\Net\Router** or about **\App\Core\ClassicRouter**, as being used in Configuration ?

**Comment by daveismyname** [comment]
It's using the default \Nova\Net\Router

**Comment by daveismyname** [comment]
After your PR I'm still getting "Unknown Views Path for the Class: \App\Controllers\Error"

**Comment by daveismyname** [comment]
Does the viewPage need the path to start with Error so it becomes Error/error404?

**Comment by LuckyCyborg** [comment]
@daveismyname 

The View path for app/Controllers/Error.php @error404 should be /app/Views/Error/error404.php

**Comment by LuckyCyborg** [comment]
@daveismyname Please wait some minutes, I work into right now.

**Comment by LuckyCyborg** [comment]
@daveismyname Look there:

http://smvc3.giulianaeassociati.com/demos/models/dbal_models

I will commit right now...

**Comment by daveismyname** [comment]
thanks

**Comment by daveismyname** [comment]
perfect.
