### ISSUE TITLE
No ORM in base, but as package.

### ISSUE THREAD

**Issue by tomvlk** [simple-mvc-framework/framework#474]
@LuckyCyborg @daveismyname 
As discussed yesterday, there should be no default ORM in the Nova base.
Or wasn't that the purpose of the new Packages?

@daveismyname

**Comment by LuckyCyborg** [comment]
@tomvlk 

> As discussed yesterday, there should be no default ORM in the Nova base.

Tom, who decided that **there should be no default ORM in the Nova base.** ?!

#You?

Please note that I've stated clearly that we will take over and implement us the **Nova\ORM**, and @daveismyname asked clearly about.
