### ISSUE TITLE
How to propertly use Modules?

### ISSUE THREAD

**Issue by mickacz** [simple-mvc-framework/framework#490]
I'm building a new version webpage based on SMVC/Nova and wondering how split it into modules.

Page will include;
- timeline of current events
- places (restaurants/clubs etc..)
- users can write review, have groups, can like, love, make friends etc...
- validated (paid) user can admin her place (write new events etc...)
and more....

any suggestions? :wink:

**Comment by LuckyCyborg** [comment]
@mickacz I'm not sure that I understand well... 

You want suggestions for designing the structure of your website, or you want details about the inner work of the Modules concept into Nova Framework?

**Comment by mickacz** [comment]
@LuckyCyborg More about structure.
Should I split for example: 

app/Modules/Event
app/Modules/User
app/Modules/Place
app/Modules/(...)

or how else to be better?

**Comment by LuckyCyborg** [comment]
@mickacz Probably yes. This is the main concept of Modules.
