### ISSUE TITLE
send null parameter to from router to controller

### ISSUE THREAD

**Issue by webineh** [simple-mvc-framework/framework#593]
hi , i need send null parameter to controller if not set Language code in URL

i have two router =
1=Router::any('home/(:any)','Controllers\login\home@index');
2=Router::any('home/(:any)/(:any)','Controllers\login\home@index');

-----------
in controller home

public function home($lang,$slug){

} 
----------
in need use router 2 by just one parameter like

site.com/newpost
in controller get 
$lang = null
$slug = newpost

===================

please help me

**Comment by webineh** [comment]
i solve this by adding new pattern in Rother.php in core folder

':lang'=>'[a-z]{2}',

by this technic SMVC just give language code by two characters like fa,en,es

very thans.

webineh.net

**Comment by daveismyname** [comment]
Thanks for letting me know, with your new patten what are you entering into your routes?

**Comment by LuckyCyborg** [comment]
@webineh and @daveismyname We talk there about SMVC version **2.2**, right?

In that version, the optional parameters aren't available into Routing and after all, even you point to that class method (Controllers\login\home@index) two or more Routes, to simulate the optional parameters, the parameters orders looks wrong. We should have:

```php
public function home($slug, $lang)
{
}
```

OR, another solution, to use two methods:

```php
public function home($slug)
{
}

public function homeWithLang($lang, $slug)
{
}
```

**Comment by webineh** [comment]
by this technic we can add multi language by 2 route  

1= default language 
2= other langauage

for frontend controller i have to controller like router
and in templete by each language code we have structure like bellow

templete 
|-default
|--fa
|---header.php
|---footer.php
|--en
|---header.php
|---footer.php

and common view for all language LTR,RTL just in View in controllers we need set $lang code to DIR folder

```
	$this->language->load('home',$data['lang_code']);
	$data['titel'] = $this->language->get('titel');
	View::renderTemplate($data['lang_code'].'/header', $data);
	View::renderModule('Site/Views/Frontend/index', $data);
	View::renderTemplate($data['lang_code'].'/footer', $data);
```
