### ISSUE TITLE
database helper ver 2.2

### ISSUE THREAD

**Issue by jimgwhit** [simple-mvc-framework/framework#613]
I had an issue when trying to use PDO::FETCH_ASSOC.  I had nothing in an array to pass so I tried
```
$stmt = $this->db->selectAssoc("SELECT * FROM checks ORDER BY checkid", "", PDO::FETCH_ASSO, "");
```
I figured I needed quotation marks where there for missing arguments.  
I got various errors:  
~~~
[Wed Feb 24 11:30:02.398273 2016] [:error] [pid 5964:tid 1184] [client ::1:55180] PHP Fatal error:  Cannot use object of type stdClass as array in C:\\BitNami\\wampstack-5.6.2-0\\apache2\\htdocs\\crudv22\\app\\Models\\CheckModel.php on line 61, referer: http://localhost/crudv22/check/index?page=2&osch=
[Wed Feb 24 11:43:45.260296 2016] [:error] [pid 5964:tid 1188] [client ::1:55452] PHP Fatal error:  Class 'Models\\PDO' not found in C:\\BitNami\\wampstack-5.6.2-0\\apache2\\htdocs\\crudv22\\app\\Models\\CheckModel.php on line 58, referer: http://localhost/crudv22/check/index?page=2&osch=
[Wed Feb 24 11:45:55.767313 2016] [:error] [pid 5964:tid 1176] [client ::1:55476] PHP Fatal error:  Class 'Models\\PDO' not found in C:\\BitNami\\wampstack-5.6.2-0\\apache2\\htdocs\\crudv22\\app\\Models\\CheckModel.php on line 58, referer: http://localhost/crudv22/check/index?page=2&osch=
[Wed Feb 24 11:56:44.976948 2016] [:error] [pid 5964:tid 1188] [client ::1:55511] PHP Fatal error:  Class 'Models\\PDO' not found in C:\\BitNami\\wampstack-5.6.2-0\\apache2\\htdocs\\crudv22\\app\\Models\\CheckModel.php on line 58, referer: http://localhost/crudv22/check/index

~~~
The only way to get it working is copy the select function like so:
```
public function selectAssoc($sql, $array = array(), $fetchMode = PDO::FETCH_ASSOC, $class = '')
    {
        $stmt = $this->prepare($sql);
        foreach ($array as $key => $value) {
            if (is_int($value)) {
                $stmt->bindValue("$key", $value, PDO::PARAM_INT);
            } else {
                $stmt->bindValue("$key", $value);
            }
        }

        $stmt->execute();

        if ($fetchMode === PDO::FETCH_CLASS) {
            return $stmt->fetchAll($fetchMode, $class);
        } else {
            return $stmt->fetchAll($fetchMode);
        }
    }
```
and in model I still got errors, til finally at top of model I put
```
use PDO;
```
So basically the select isn't working if you need to pass PDO::FETCH_ASSOC, and why didn't it work without use PDO; at top of model.  
To recap what worked in model:
~~~
use PDO;
//other code
public function checkRecalc()
    {
        $k = 0;
        $vsum = 0;
        $stmt = $this->db->selectAssoc("SELECT * FROM checks ORDER BY checkid");
        foreach ($stmt as $row) {
            $k = $k + 1;
            $tid = (int) $row['checkid'];
            echo $tid . "===";
            if ($k == 1) {
                $vsum = $vsum + $row['deposit'];
            } else {
                $vsum = $vsum - $row['widthdraw'] + $row['deposit'];
            }
            $postdata = array(
                'runsum' => $vsum,
            );
            $where = array('checkid' => $tid);
            $this->db->update("checks", $postdata, $where);
        }
        return;
    }

~~~
And adding this in database helper
~~~
public function selectAssoc($sql, $array = array(), $fetchMode = PDO::FETCH_ASSOC, $class = '')
    {
        $stmt = $this->prepare($sql);
        foreach ($array as $key => $value) {
            if (is_int($value)) {
                $stmt->bindValue("$key", $value, PDO::PARAM_INT);
            } else {
                $stmt->bindValue("$key", $value);
            }
        }

        $stmt->execute();

        if ($fetchMode === PDO::FETCH_CLASS) {
            return $stmt->fetchAll($fetchMode, $class);
        } else {
            return $stmt->fetchAll($fetchMode);
        }
    }
~~~

**Comment by tomvlk** [comment]
Well, have you already tried to change your code:
```php
$stmt = $this->db->selectAssoc("SELECT * FROM checks ORDER BY checkid", "", PDO::FETCH_ASSOC, "");
```

Into this one:
```php
$stmt = $this->db->selectAssoc("SELECT * FROM checks ORDER BY checkid", "",  PDO::FETCH_ASSOC, "");
```
(See the \ before PDO, this means it will use PDO class on the root namespace).

**Comment by jimgwhit** [comment]
@tomvlk it is the same statement repeated in you reply, except your bottom statement has an extra space.
```
$stmt = $this->db->selectAssoc("SELECT * FROM checks ORDER BY checkid", "", PDO::FETCH_ASSOC, "");
$stmt = $this->db->selectAssoc("SELECT * FROM checks ORDER BY checkid", "",  PDO::FETCH_ASSOC, "");
```

**Comment by tomvlk** [comment]
Sorry, see my edit :laughing:

**Comment by jimgwhit** [comment]
@tomvlk I figured the editor just wasn,t showing the slash, I tried
```
$stmt = $this->db->select("SELECT * FROM checks ORDER BY checkid", "", \PDO::FETCH_ASSOC, "");
```
got this error
```
$stmt = $this->db->select("SELECT * FROM checks ORDER BY checkid", "", \PDO::FETCH_ASSOC, "");
```

**Comment by tomvlk** [comment]
@jimgwhit i see no error xD Also copy paste failure :laughing:

**Comment by tomvlk** [comment]
@jimgwhit Btw, look at your function declare and the call to it

```php
$stmt = $this->db->selectAssoc("SELECT * FROM checks ORDER BY checkid", "", \PDO::FETCH_ASSOC, "");
```
Is not correct, you pass a string, where array is needed. Maybe this is not the main issue but will resolve in errors too.

```php
$stmt = $this->db->selectAssoc("SELECT * FROM checks ORDER BY checkid", array(), \PDO::FETCH_ASSOC);
```
Should be better

**Comment by jimgwhit** [comment]
@tomvlk 
```
Invalid argument supplied for foreach() in C:\BitNami\wampstack-5.6.2-0\apache2\htdocs\crudv22\app\Helpers\Database.php on line 92
```

**Comment by tomvlk** [comment]
@jimgwhit Ye, try my last comment

**Comment by jimgwhit** [comment]
@tomvlk ok I used your last statement with
```
$stmt = $this->db->select("SELECT * FROM checks ORDER BY checkid", array(), \PDO::FETCH_ASSOC);
```
It worked, but questions:
Why do you need to pass array() if using PDO::FETCH_ASSOC?  
But if using PDO::FETCH_OBJ then this would work
```
$stmt = $this->db->select("SELECT * FROM checks ORDER BY checkid");
```
With PDO::FETCH_OBJ I don't need to pass array().  
And why is a slash needed if using PDO::FETCH_ASSOC like
```
\PDO::FETCH_ASSOC
```

**Comment by tomvlk** [comment]
the array is a parameter in your function...

**Comment by jimgwhit** [comment]
@tomvlk I know that, but if I had the same query  
This wil work if using PDO::FETCH_OBJ
```
$stmt = $this->db->select("SELECT * FROM checks ORDER BY checkid");
```
But if using PDO::FETCH_ASSOC I have to
```
$stmt = $this->db->select("SELECT * FROM checks ORDER BY checkid", array(), \PDO::FETCH_ASSOC);
```
In other words I have to pass a dummy array and use a slash before PDO, why?

**Comment by tomvlk** [comment]
Because of the declaration of the select function......
You will less common change the default fetch mode then giving parameter array.. thats the whole story behind it I think. And I agree with the positions of the parameters.

**Comment by jimgwhit** [comment]
ok, what is the last parameter ever used for
```
public function select($sql, $array = array(), $fetchMode = PDO::FETCH_OBJ, $class = '')
```
the $class parameter?

**Comment by tomvlk** [comment]
When you do a FETCH_CLASS in PDO you should give the full class name in the last parameter.

**Comment by jimgwhit** [comment]
Ok so the last parameter is a special one, I will probably never need, thanks. Also, @daveismyname if you have any in-sight, let me know, I will leave this issue open for a while.  
And thank you @tomvlk for your help.

**Comment by daveismyname** [comment]
By default the select uses:

$sql, $array = array(), $fetchMode = PDO::FETCH_OBJ, $class = ''

so you only need to pass in the sql and an array when using prepared statements this will return an object to return assoc you need to pass the sql and the 2nd param before you set the third.

**Comment by jimgwhit** [comment]
@daveismyname and  @tomvlk All is working with that advice, but still puzzled on why a slash is needed if using assoc
````
\PDO::FETCH_ASSOC
```
The query will not work without the slash in front of PDO.

**Comment by daveismyname** [comment]
because when using inside a controller the system is looking for a class of pdo inside the current class but won't find it so it needs the \ to tell it to look in the global namespace. 

Using an alias will stop the need of a \

**Comment by jimgwhit** [comment]
@daveismyname thank's for the quick reply, I will close issue tomorrow, leave it for a bit maybe help someone else.
