### ISSUE TITLE
Analysis

### ISSUE THREAD

**Issue by jimgwhit** [simple-mvc-framework/framework#615]
@daveismyname I was looking at the branches and saw one named. 
analysis-XlKEKQ, is this some automated program you are using or is it some kind of hijacking of the site thing going on, just wondering and making sure everything is OK, the whole site was
 https://github.com/simple-mvc-framework/framework/tree/analysis-XlKEKQ 
If it is some program you are using sorry I bugged you about it.

**Comment by daveismyname** [comment]
It's a tool for checking psr compliance :)

**Comment by jimgwhit** [comment]
@daveismyname  OK, I kinda figured it was some tool you were using, just wanted to make sure thanks.

**Comment by jimgwhit** [comment]
@daveismyname I noticed it removed some lines that may need to be there like in app/core/controller
it removed. 
~~~
 use Core\View;
 use Core\Language;
~~~
Just one of the places I noticed.
Is this program something new you are trying? And just wondering if it is working correctly.

**Comment by daveismyname** [comment]
Oh drat can't be doing it correctly thanks I'll sort it out!
