### ISSUE TITLE
New ver 3 templates

### ISSUE THREAD

**Issue by jimgwhit** [simple-mvc-framework/framework#630]
@daveismyname and @LuckyCyborg 
In my header I have
```
<link href="<?php echo Helpers\Url::templatePath(); ?>css/style.css" rel="stylesheet">
```
I noticed the css wasn't loading, so I echoed out 
```
<?php echo Helpers\Url::templatePath(); ?>
```
Just to see if was echoing out correctly.
And found it's returning the current route name then template path.
Here's the two routes
```
Router::any('dog', 'App\Controllers\Dog@index');
Router::any('dog/index', 'App\Controllers\Dog@index');
```
It echos
```
dog http://localhost/novadave/templates/default/
instead of 
http://localhost/novadave/templates/default/
```
Even changing to http://localhost/novadave/dog/index?p=1 it still echos out
```
dog http://localhost/novadave/templates/default/ 
```
What is causing it to pickup the name of the route also? How to fix?

**Comment by LuckyCyborg** [comment]
@jimgwhit That should not be.

BTW, you have a new definition in nova/system/Core/Config.php called **SITEURL** and used by **Url::templatePath()**. 

It should contains the full url to site root, I.e. , In your case:

```
http://localhost/novadave/

PS. Sorry for messing with your post in the other thread.
```

**Comment by jimgwhit** [comment]
@LuckyCyborg I changed the siteurl, now it echos
```
http://localhost/novadave/templates/default/ 
```
which still not loading the css.  
Here is the line 
```
<link href="<?php echo Helpers\Url::templatePath(); ?>/css/style.css" rel="stylesheet">
```
That doesn't work, but if I use
```
<link href="http://localhost/novadave/templates/Default/css/style.css" rel="stylesheet">
```
It works.  Is the templatePath function Default to default (small letter)?

**Comment by LuckyCyborg** [comment]
@jimgwhit Come on! You do not have your installed site up to date! When you downloaded that?

In the latest tree, the **Url::templatePath()** should return:

```
http://localhost/novadave/templates/default/assets
```  

And you should have to keep all css and js into a directory called Assets. More details there:

https://github.com/simple-mvc-framework/framework/tree/3.0

**Comment by jimgwhit** [comment]
@LuckyCyborg you said In the latest tree, the Url::templatePath() should return:
```
http://localhost/novadave/templates/default/assets/
```
That woud still be wrong, you are miss app.  Should be
```
http://localhost/novadave/app/Templates/Default/assets/css/style.css"
```
And capital T and capital D as in the framework.
Or did you refer to moving Templates up a folder?  But I did a composer update 2 hours ago, things should be up to date. Why wouldn't the composer update, update?

**Comment by LuckyCyborg** [comment]
@jimgwhit The URL of your file should be:

```
http://localhost/novadave/templates/default/assets/css/style.css
```

If configured correctly, the Routing will known how to find the file, in the right path, which should be:
```
<SNIP>novadave/app/Templates/Default/Assets/css/style.css
```

WTF? You moved the **nova**'s contents to site root? You should say that first! How you expect help when you mess with framework in unknown modes?

> But I did a composer update 2 hours ago, things should be up to date. Why wouldn't the composer update, update?

OMG! I will leave to Dave the pleasure to explain you why **composer update** will still not update your site but its dependencies...

**Comment by jimgwhit** [comment]
@LuckyCyborg I updated the url file.  Still did not work.  And why would thet part concerning templates be in a router, that makes no sense.  
I had to change 
```
return SITEURL .'templates/' .$template .'/assets/';
```
to 
```
return SITEURL .'app/templates/' .$template .'/assets/';
```
Now it works correctly.  THE ROUTER SHOULD HAVE NOTHING TO DO WITH LOADING A CSS FILE.  So why would the router have to know that.  The router should just deal with the routes via the controllers.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> THE ROUTER SHOULD HAVE NOTHING TO DO WITH LOADING A CSS FILE. So why would the router have to know that. The router should just deal with the routes via the controllers.

Huh? Then I have news for you: the Dave's Nova Routing deal with the assets files and know about them. Because Dave wanted to. Ask him why.

BTW, when your framework is outside of web root, from security reasons, guess what give you access to files behind the web access? The Routing.

But, how you mess with important things on the framework, as in site structure, URL/URI critical functions, that's just your personal Jim Framework right now, and I can't help you more. 

All the best!

**Comment by jimgwhit** [comment]
@daveismyname why do we need that nova folder, you wanted testing, so I am just saying by moving files up a folder, like you could in your first version of 3.0 is so much better, and that prevents seeing folder structure.  I don't even know which folder to run composer from.  Of course I ran composer from root folder, and moved everything in nova to root.  That is the logical place for index and htaccess anyway.  But then @LuckyCyborg says that messes up the assets folder.  Your first version of 3.0 with the video you did was easier to work with and enabledmoving the files up a folder.  
But in a case where I don't want the nova folder is changing the template in url.php to
```
return SITEURL .'app/templates/' .$template .'/assets/';
```
a ok fix, should everything else work?

**Comment by LuckyCyborg** [comment]
@jimgwhit BTW, I made a installation into sub-directory, on **localhost**, under Slackware Linux (current), of the current **3.0** framework tree.

Also, like I seen that you made, I moved the content of **nova** directory into site root, also there the files from **public_html**.
  
 It still works perfectly, **even the files serving via Routing**, after the usual configuration, like it is seen in the attached screenshot. 

Then, with all respect, you report an **invalid issue** and **there is nothing to fix**.

![snapshot3](https://cloud.githubusercontent.com/assets/13488485/13715191/7fa3162e-e7d3-11e5-8276-c77f8ad03145.png)

**Comment by jimgwhit** [comment]
@LuckyCyborg I had the verson just prior to pr #628 is where the problem came in.  I want to stay up to date without constantly re-downloading, and composer update doesn't update those files, I have a fork of master, but can't figure out how to fork the branch. But that is where the problem came in. You want testing, but I need to fork.

**Comment by daveismyname** [comment]
> @daveismyname why do we need that nova folder, you wanted testing, so I am just saying by moving files up a folder, like you could in your first version of 3.0 is so much better, and that prevents seeing folder structure. I don't even know which folder to run composer from. Of course I ran composer from root folder, and moved everything in nova to root. That is the logical place for index and htaccess anyway. But then @LuckyCyborg says that messes up the assets folder. Your first version of 3.0 with the video you did was easier to work with and enabledmoving the files up a folder.
> 
> But in a case where I don't want the nova folder is changing the template in url.php to
> 
> return SITEURL .'app/templates/' .$template .'/assets/';
> a ok fix, should everything else work?

I used the nova folder as a way to group files so they don't get mixed in with other folder when placing above the document root if you don't want to use the nova folder remove it and remove the nova reference from the paths in index.php that should be all you need to do for that.

My origianl 3.0 forced templates and modules with be in the public this one is better as it allows them be work above the public route making it much safer.
