### ISSUE TITLE
index.php and linux vs windows

### ISSUE THREAD

**Issue by jimgwhit** [simple-mvc-framework/framework#633]
@daveismyname I have noticed on windows development machine the folllowing. We will just use
APPDIR as example so as not to have to cover all and I am testing by:
```
echo APPDIR;
```
And folder structure of  
~~~
+htdocs
    +mysite
      +app
      -stuff under app
      +system
      -stuff under system
    -index.php
    -.htaccess
    -etc etc
~~~

If I have this line in index:
```
define('APPDIR', dirname(__DIR__).'/app/');
``` 
It echos out
```
C:\BitNami\wampstack-5.6.2-0\apache2\htdocs/app/
```
It completely skip mysite.  
However if I use this in the index 
```
define('APPDIR', __DIR__ .DS. 'app/');
```
It echos out:
```
C:\BitNami\wampstack-5.6.2-0\apache2\htdocs\mysite\app/
```
And all works fine.  So does 
```
dirname(__DIR__)
```
need to be changed to
```
//just
__DIR__
```
For compatibility with windows and linux?  Or what is the proper way for all servers?  
Not a bad issue here, I can easily get it to work, but why does the dirname(__DIR__) get the folder above and the folder below skipping mysite?  
And remember your first 3.0 beta version:
```
define('APP', dirname(__FILE__).'/app/');
```
Also worked.  
 And @LuckyCyborg what do you make of this?  Had the same trouble in the first 3.0 beta version on a windows machine.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> And @LuckyCyborg what do you make of this? Had the same trouble in the first 3.0 beta version on a windows machine.

Jim, you want to simplify your life? In the name of your favorite God, stop installing Dave's Framework in a sub-directory and messing around with its folders and configuration. 

Instead, use a **Virtual Host**, with its webroot pointing to **public_html** folder. Even your WAMP support that thing, and a simple googling give very complete tutorials on that subject. I.e.

https://www.kristengrote.com/blog/articles/how-to-set-up-virtual-hosts-using-wamp
https://john-dugan.com/wamp-vhost-setup/

**Comment by jimgwhit** [comment]
@LuckyCyborg a virtual host has nothing to do with this question. I believe that
~~~
dirname(__FILE__)
~~~
Acts different on Linux vs. Windows.  Now I enjoy developing on Windows and I enjoy my netbeans. Are you saying to only develop on Linux?  Wouldn't it be better to fix the dirname(__FILE__) command?  
Look again carefully at my example it doesn't matter where the files are located my Ponting to the files is correct.  I don't see how developing in a virtual host would be any different. Unless it's a Linux virtual host.

**Comment by LuckyCyborg** [comment]
@jimgwhit 

> @LuckyCyborg a virtual host has nothing to do with this question. 

I beg to differ. Using a virtual host, you do not need to edit the framework's paths and everything will work out of box, without moving around the folders.

The problem is not that the command **dirname(__DIR__)** behave different between Windows and Linux (it doesn't), but that you have trouble with figuring the right path values.

Then, using Virtual Hosts the need of hand-made configuration of those paths is eliminated and you can enjoy you Windows hosted development instead.
